#!/usr/bin/env python3
"""Generate Rust code for JSON helpers in wasm_emit.rs"""

def p(line):
    print(line)

# ===== Constants =====
p("const INPUT_BUF: i64 = 16384;  // 16KB for input JSON args")
p("")
# ===== json_get_int =====
p("    /// Emit WASM to read input JSON to INPUT_BUF, scan for \"key\": pattern, return i64 value.")
p("    fn json_get_int(&mut self, key: &str) -> Result<Vec<Instruction<'static>>, String> {")
p("        self.need_host(7); self.need_host(0); self.need_host(1);")
p("")
p("        let mut pattern = vec![b'\"'];")
p("        pattern.extend(key.as_bytes());")
p("        pattern.extend_from_slice(b\"\\\":\");")
p("        let pat_off = self.alloc_data(&pattern);")
p("        let pat_len = pattern.len() as i64;")
p("")
p("        let pos = self.local_idx(\"__js_pos\");")
p("        let ilen = self.local_idx(\"__js_ilen\");")
p("        let mi = self.local_idx(\"__js_mi\");")
p("        let jj = self.local_idx(\"__js_j\");")
p("        let res = self.local_idx(\"__js_res\");")
p("        let ng = self.local_idx(\"__js_ng\");")
p("        let dg = self.local_idx(\"__js_dg\");")
p("        let ma8 = wasm_encoder::MemArg { offset: 0, align: 0, memory_index: 0 };")
p("        let ib = INPUT_BUF as i64;")
p("")
p("        let mut v = Vec::new();")
p("")
p("        // Read input: input(0) -> register 0")
p("        v.push(Instruction::I64Const(0));")
p("        v.push(Self::host_call(7));")
p("        // register_len(0)")
p("        v.push(Instruction::I64Const(0));")
p("        v.push(Self::host_call(1));")
p("        v.push(Instruction::LocalSet(ilen));")
p("        // read_register(0, INPUT_BUF)")
p("        v.push(Instruction::I64Const(0));")
p("        v.push(Instruction::I64Const(ib));")
p("        v.push(Self::host_call(0));")
p("")
p("        // pos = 0")
p("        v.push(Instruction::I64Const(0));")
p("        v.push(Instruction::LocalSet(pos));")
p("")
p("        // Scan loop")
p("        v.push(Instruction::Block(BlockType::Empty));")
p("        v.push(Instruction::Loop(BlockType::Empty));")
p("        // if pos + pat_len > ilen, break")
p("        v.push(Instruction::LocalGet(pos));")
p("        v.push(Instruction::I64Const(pat_len));")
p("        v.push(Instruction::I64Add);")
p("        v.push(Instruction::LocalGet(ilen));")
p("        v.push(Instruction::I64GtS);")
p("        v.push(Instruction::If(BlockType::Empty));")
p("        v.push(Instruction::Br(2));")
p("        v.push(Instruction::End);")
p("")
p("        // Compare pattern bytes")
p("        v.push(Instruction::I64Const(1));")
p("        v.push(Instruction::LocalSet(mi));")
p("        v.push(Instruction::I64Const(0));")
p("        v.push(Instruction::LocalSet(jj));")
p("")
p("        v.push(Instruction::Block(BlockType::Empty));")
p("        v.push(Instruction::Loop(BlockType::Empty));")
p("        v.push(Instruction::LocalGet(jj));")
p("        v.push(Instruction::I64Const(pat_len));")
p("        v.push(Instruction::I64GeS);")
p("        v.push(Instruction::If(BlockType::Empty));")
p("        v.push(Instruction::Br(2));")
p("        v.push(Instruction::End);")
p("")
p("        // Load input_buf[pos + j]")
p("        v.push(Instruction::I64Const(ib));")
p("        v.push(Instruction::LocalGet(pos));")
p("        v.push(Instruction::I64Add);")
p("        v.push(Instruction::LocalGet(jj));")
p("        v.push(Instruction::I64Add);")
p("        v.push(Instruction::I32WrapI64);")
p("        v.push(Instruction::I32Load8U(ma8.clone()));")
p("        // Load pattern[j]")
p("        v.push(Instruction::I64Const(pat_off));")
p("        v.push(Instruction::LocalGet(jj));")
p("        v.push(Instruction::I64Add);")
p("        v.push(Instruction::I32WrapI64);")
p("        v.push(Instruction::I32Load8U(ma8.clone()));")
p("        // Compare")
p("        v.push(Instruction::I64Eq);")
p("        v.push(Instruction::I32WrapI64);")
p("        v.push(Instruction::If(BlockType::Empty));")
p("        v.push(Instruction::Else);")
p("        v.push(Instruction::I64Const(0));")
p("        v.push(Instruction::LocalSet(mi));")
p("        v.push(Instruction::Br(2));")
p("        v.push(Instruction::End);")
p("")
p("        v.push(Instruction::LocalGet(jj));")
p("        v.push(Instruction::I64Const(1));")
p("        v.push(Instruction::I64Add);")
p("        v.push(Instruction::LocalSet(jj));")
p("        v.push(Instruction::Br(1));")
p("        v.push(Instruction::End);")
p("        v.push(Instruction::End);")
p("")
p("        // If mi==1, found")
p("        v.push(Instruction::LocalGet(mi));")
p("        v.push(Instruction::I64Const(1));")
p("        v.push(Instruction::I64Eq);")
p("        v.push(Instruction::I32WrapI64);")
p("        v.push(Instruction::If(BlockType::Empty));")
p("        v.push(Instruction::Br(3));")
p("        v.push(Instruction::End);")
p("")
p("        v.push(Instruction::LocalGet(pos));")
p("        v.push(Instruction::I64Const(1));")
p("        v.push(Instruction::I64Add);")
p("        v.push(Instruction::LocalSet(pos));")
p("        v.push(Instruction::Br(1));")
p("        v.push(Instruction::End);")
p("        v.push(Instruction::End);")
p("")
p("        // pos now at start of match. Value at pos + pat_len")
p("        v.push(Instruction::LocalGet(pos));")
p("        v.push(Instruction::I64Const(pat_len));")
p("        v.push(Instruction::I64Add);")
p("        v.push(Instruction::LocalSet(pos));")
p("")
p("        // Skip whitespace")
p("        v.push(Instruction::Block(BlockType::Empty));")
p("        v.push(Instruction::Loop(BlockType::Empty));")
p("        v.push(Instruction::LocalGet(pos));")
p("        v.push(Instruction::LocalGet(ilen));")
p("        v.push(Instruction::I64GeS);")
p("        v.push(Instruction::If(BlockType::Empty));")
p("        v.push(Instruction::Br(2));")
p("        v.push(Instruction::End);")
p("        v.push(Instruction::I64Const(ib));")
p("        v.push(Instruction::LocalGet(pos));")
p("        v.push(Instruction::I64Add);")
p("        v.push(Instruction::I32WrapI64);")
p("        v.push(Instruction::I32Load8U(ma8.clone()));")
p("        v.push(Instruction::I64Const(0x20));")
p("        v.push(Instruction::I64Eq);")
p("        v.push(Instruction::I32WrapI64);")
p("        v.push(Instruction::If(BlockType::Empty));")
p("        v.push(Instruction::LocalGet(pos));")
p("        v.push(Instruction::I64Const(1));")
p("        v.push(Instruction::I64Add);")
p("        v.push(Instruction::LocalSet(pos));")
p("        v.push(Instruction::Br(1));")
p("        v.push(Instruction::End);")
p("        v.push(Instruction::End);")
p("        v.push(Instruction::End);")
p("")
p("        // Skip quote if present")
p("        v.push(Instruction::LocalGet(pos));")
p("        v.push(Instruction::LocalGet(ilen));")
p("        v.push(Instruction::I64LtS);")
p("        v.push(Instruction::I32WrapI64);")
p("        v.push(Instruction::If(BlockType::Empty));")
p("        v.push(Instruction::I64Const(ib));")
p("        v.push(Instruction::LocalGet(pos));")
p("        v.push(Instruction::I64Add);")
p("        v.push(Instruction::I32WrapI64);")
p("        v.push(Instruction::I32Load8U(ma8.clone()));")
p("        v.push(Instruction::I64Const(0x22));")
p("        v.push(Instruction::I64Eq);")
p("        v.push(Instruction::I32WrapI64);")
p("        v.push(Instruction::If(BlockType::Empty));")
p("        v.push(Instruction::LocalGet(pos));")
p("        v.push(Instruction::I64Const(1));")
p("        v.push(Instruction::I64Add);")
p("        v.push(Instruction::LocalSet(pos));")
p("        v.push(Instruction::End);")
p("        v.push(Instruction::End);")
p("")
p("        // Check negative")
p("        v.push(Instruction::I64Const(0));")
p("        v.push(Instruction::LocalSet(ng));")
p("        v.push(Instruction::LocalGet(pos));")
p("        v.push(Instruction::LocalGet(ilen));")
p("        v.push(Instruction::I64LtS);")
p("        v.push(Instruction::I32WrapI64);")
p("        v.push(Instruction::If(BlockType::Empty));")
p("        v.push(Instruction::I64Const(ib));")
p("        v.push(Instruction::LocalGet(pos));")
p("        v.push(Instruction::I64Add);")
p("        v.push(Instruction::I32WrapI64);")
p("        v.push(Instruction::I32Load8U(ma8.clone()));")
p("        v.push(Instruction::I64Const(0x2D));")
p("        v.push(Instruction::I64Eq);")
p("        v.push(Instruction::I32WrapI64);")
p("        v.push(Instruction::If(BlockType::Empty));")
p("        v.push(Instruction::I64Const(1));")
p("        v.push(Instruction::LocalSet(ng));")
p("        v.push(Instruction::LocalGet(pos));")
p("        v.push(Instruction::I64Const(1));")
p("        v.push(Instruction::I64Add);")
p("        v.push(Instruction::LocalSet(pos));")
p("        v.push(Instruction::End);")
p("        v.push(Instruction::End);")
p("")
p("        // Parse digits")
p("        v.push(Instruction::I64Const(0));")
p("        v.push(Instruction::LocalSet(res));")
p("")
p("        v.push(Instruction::Block(BlockType::Empty));")
p("        v.push(Instruction::Loop(BlockType::Empty));")
p("        v.push(Instruction::LocalGet(pos));")
p("        v.push(Instruction::LocalGet(ilen));")
p("        v.push(Instruction::I64GeS);")
p("        v.push(Instruction::If(BlockType::Empty));")
p("        v.push(Instruction::Br(2));")
p("        v.push(Instruction::End);")
p("        v.push(Instruction::I64Const(ib));")
p("        v.push(Instruction::LocalGet(pos));")
p("        v.push(Instruction::I64Add);")
p("        v.push(Instruction::I32WrapI64);")
p("        v.push(Instruction::I32Load8U(ma8.clone()));")
p("        v.push(Instruction::LocalSet(dg));")
p("        // if dg < '0', break")
p("        v.push(Instruction::LocalGet(dg));")
p("        v.push(Instruction::I64Const(0x30));")
p("        v.push(Instruction::I64LtS);")
p("        v.push(Instruction::I32WrapI64);")
p("        v.push(Instruction::If(BlockType::Empty));")
p("        v.push(Instruction::Br(2));")
p("        v.push(Instruction::End);")
p("        // if dg > '9', break")
p("        v.push(Instruction::LocalGet(dg));")
p("        v.push(Instruction::I64Const(0x39));")
p("        v.push(Instruction::I64GtS);")
p("        v.push(Instruction::I32WrapI64);")
p("        v.push(Instruction::If(BlockType::Empty));")
p("        v.push(Instruction::Br(2));")
p("        v.push(Instruction::End);")
p("        // res = res * 10 + (dg - 0x30)")
p("        v.push(Instruction::LocalGet(res));")
p("        v.push(Instruction::I64Const(10));")
p("        v.push(Instruction::I64Mul);")
p("        v.push(Instruction::LocalGet(dg));")
p("        v.push(Instruction::I64Const(0x30));")
p("        v.push(Instruction::I64Sub);")
p("        v.push(Instruction::I64Add);")
p("        v.push(Instruction::LocalSet(res));")
p("        v.push(Instruction::LocalGet(pos));")
p("        v.push(Instruction::I64Const(1));")
p("        v.push(Instruction::I64Add);")
p("        v.push(Instruction::LocalSet(pos));")
p("        v.push(Instruction::Br(1));")
p("        v.push(Instruction::End);")
p("        v.push(Instruction::End);")
p("")
p("        // Apply negative")
p("        v.push(Instruction::LocalGet(ng));")
p("        v.push(Instruction::I32WrapI64);")
p("        v.push(Instruction::If(BlockType::Result(ValType::I64)));")
p("        v.push(Instruction::I64Const(0));")
p("        v.push(Instruction::LocalGet(res));")
p("        v.push(Instruction::I64Sub);")
p("        v.push(Instruction::Else);")
p("        v.push(Instruction::LocalGet(res));")
p("        v.push(Instruction::End);")
p("")
p("        Ok(v)")
p("    }")
p("")

# ===== json_get_str =====
p("    /// Emit WASM to read input JSON, scan for \"key\": \"value\", return packed string (ptr|len<<32).")
p("    fn json_get_str(&mut self, key: &str) -> Result<Vec<Instruction<'static>>, String> {")
p("        self.need_host(7); self.need_host(0); self.need_host(1);")
p("")
p("        let mut pattern = vec![b'\"'];")
p("        pattern.extend(key.as_bytes());")
p("        pattern.extend_from_slice(b\"\\\":\");")
p("        let pat_off = self.alloc_data(&pattern);")
p("        let pat_len = pattern.len() as i64;")
p("")
p("        let pos = self.local_idx(\"__jss_pos\");")
p("        let ilen = self.local_idx(\"__jss_ilen\");")
p("        let mi = self.local_idx(\"__jss_mi\");")
p("        let jj = self.local_idx(\"__jss_j\");")
p("        let slen = self.local_idx(\"__jss_slen\");")
p("        let ma8 = wasm_encoder::MemArg { offset: 0, align: 0, memory_index: 0 };")
p("        let ib = INPUT_BUF as i64;")
p("")
p("        let mut v = Vec::new();")
p("")
p("        // Read input to INPUT_BUF")
p("        v.push(Instruction::I64Const(0));")
p("        v.push(Self::host_call(7));")
p("        v.push(Instruction::I64Const(0));")
p("        v.push(Self::host_call(1));")
p("        v.push(Instruction::LocalSet(ilen));")
p("        v.push(Instruction::I64Const(0));")
p("        v.push(Instruction::I64Const(ib));")
p("        v.push(Self::host_call(0));")
p("")
p("        v.push(Instruction::I64Const(0));")
p("        v.push(Instruction::LocalSet(pos));")
p("")
p("        // Scan loop")
p("        v.push(Instruction::Block(BlockType::Empty));")
p("        v.push(Instruction::Loop(BlockType::Empty));")
p("        v.push(Instruction::LocalGet(pos));")
p("        v.push(Instruction::I64Const(pat_len));")
p("        v.push(Instruction::I64Add);")
p("        v.push(Instruction::LocalGet(ilen));")
p("        v.push(Instruction::I64GtS);")
p("        v.push(Instruction::If(BlockType::Empty));")
p("        v.push(Instruction::Br(2));")
p("        v.push(Instruction::End);")
p("")
p("        v.push(Instruction::I64Const(1));")
p("        v.push(Instruction::LocalSet(mi));")
p("        v.push(Instruction::I64Const(0));")
p("        v.push(Instruction::LocalSet(jj));")
p("")
p("        v.push(Instruction::Block(BlockType::Empty));")
p("        v.push(Instruction::Loop(BlockType::Empty));")
p("        v.push(Instruction::LocalGet(jj));")
p("        v.push(Instruction::I64Const(pat_len));")
p("        v.push(Instruction::I64GeS);")
p("        v.push(Instruction::If(BlockType::Empty));")
p("        v.push(Instruction::Br(2));")
p("        v.push(Instruction::End);")
p("")
p("        v.push(Instruction::I64Const(ib));")
p("        v.push(Instruction::LocalGet(pos));")
p("        v.push(Instruction::I64Add);")
p("        v.push(Instruction::LocalGet(jj));")
p("        v.push(Instruction::I64Add);")
p("        v.push(Instruction::I32WrapI64);")
p("        v.push(Instruction::I32Load8U(ma8.clone()));")
p("        v.push(Instruction::I64Const(pat_off));")
p("        v.push(Instruction::LocalGet(jj));")
p("        v.push(Instruction::I64Add);")
p("        v.push(Instruction::I32WrapI64);")
p("        v.push(Instruction::I32Load8U(ma8.clone()));")
p("        v.push(Instruction::I64Eq);")
p("        v.push(Instruction::I32WrapI64);")
p("        v.push(Instruction::If(BlockType::Empty));")
p("        v.push(Instruction::Else);")
p("        v.push(Instruction::I64Const(0));")
p("        v.push(Instruction::LocalSet(mi));")
p("        v.push(Instruction::Br(2));")
p("        v.push(Instruction::End);")
p("")
p("        v.push(Instruction::LocalGet(jj));")
p("        v.push(Instruction::I64Const(1));")
p("        v.push(Instruction::I64Add);")
p("        v.push(Instruction::LocalSet(jj));")
p("        v.push(Instruction::Br(1));")
p("        v.push(Instruction::End);")
p("        v.push(Instruction::End);")
p("")
p("        v.push(Instruction::LocalGet(mi));")
p("        v.push(Instruction::I64Const(1));")
p("        v.push(Instruction::I64Eq);")
p("        v.push(Instruction::I32WrapI64);")
p("        v.push(Instruction::If(BlockType::Empty));")
p("        v.push(Instruction::Br(3));")
p("        v.push(Instruction::End);")
p("")
p("        v.push(Instruction::LocalGet(pos));")
p("        v.push(Instruction::I64Const(1));")
p("        v.push(Instruction::I64Add);")
p("        v.push(Instruction::LocalSet(pos));")
p("        v.push(Instruction::Br(1));")
p("        v.push(Instruction::End);")
p("        v.push(Instruction::End);")
p("")
p("        // pos at match start. Value at pos + pat_len")
p("        v.push(Instruction::LocalGet(pos));")
p("        v.push(Instruction::I64Const(pat_len));")
p("        v.push(Instruction::I64Add);")
p("        v.push(Instruction::LocalSet(pos));")
p("")
p("        // Skip whitespace")
p("        v.push(Instruction::Block(BlockType::Empty));")
p("        v.push(Instruction::Loop(BlockType::Empty));")
p("        v.push(Instruction::LocalGet(pos));")
p("        v.push(Instruction::LocalGet(ilen));")
p("        v.push(Instruction::I64GeS);")
p("        v.push(Instruction::If(BlockType::Empty));")
p("        v.push(Instruction::Br(2));")
p("        v.push(Instruction::End);")
p("        v.push(Instruction::I64Const(ib));")
p("        v.push(Instruction::LocalGet(pos));")
p("        v.push(Instruction::I64Add);")
p("        v.push(Instruction::I32WrapI64);")
p("        v.push(Instruction::I32Load8U(ma8.clone()));")
p("        v.push(Instruction::I64Const(0x20));")
p("        v.push(Instruction::I64Eq);")
p("        v.push(Instruction::I32WrapI64);")
p("        v.push(Instruction::If(BlockType::Empty));")
p("        v.push(Instruction::LocalGet(pos));")
p("        v.push(Instruction::I64Const(1));")
p("        v.push(Instruction::I64Add);")
p("        v.push(Instruction::LocalSet(pos));")
p("        v.push(Instruction::Br(1));")
p("        v.push(Instruction::End);")
p("        v.push(Instruction::End);")
p("        v.push(Instruction::End);")
p("")
p("        // Skip opening quote")
p("        v.push(Instruction::LocalGet(pos));")
p("        v.push(Instruction::I64Const(1));")
p("        v.push(Instruction::I64Add);")
p("        v.push(Instruction::LocalSet(pos));")
p("")
p("        // Measure string length")
p("        v.push(Instruction::I64Const(0));")
p("        v.push(Instruction::LocalSet(slen));")
p("        v.push(Instruction::Block(BlockType::Empty));")
p("        v.push(Instruction::Loop(BlockType::Empty));")
p("        v.push(Instruction::LocalGet(pos));")
p("        v.push(Instruction::LocalGet(slen));")
p("        v.push(Instruction::I64Add);")
p("        v.push(Instruction::LocalGet(ilen));")
p("        v.push(Instruction::I64GeS);")
p("        v.push(Instruction::If(BlockType::Empty));")
p("        v.push(Instruction::Br(2));")
p("        v.push(Instruction::End);")
p("        v.push(Instruction::I64Const(ib));")
p("        v.push(Instruction::LocalGet(pos));")
p("        v.push(Instruction::LocalGet(slen));")
p("        v.push(Instruction::I64Add);")
p("        v.push(Instruction::I32WrapI64);")
p("        v.push(Instruction::I32Load8U(ma8.clone()));")
p("        v.push(Instruction::I64Const(0x22));")
p("        v.push(Instruction::I64Eq);")
p("        v.push(Instruction::I32WrapI64);")
p("        v.push(Instruction::If(BlockType::Empty));")
p("        v.push(Instruction::Br(2));")
p("        v.push(Instruction::End);")
p("        v.push(Instruction::LocalGet(slen));")
p("        v.push(Instruction::I64Const(1));")
p("        v.push(Instruction::I64Add);")
p("        v.push(Instruction::LocalSet(slen));")
p("        v.push(Instruction::Br(1));")
p("        v.push(Instruction::End);")
p("        v.push(Instruction::End);")
p("")
p("        // Return packed: (slen << 32) | (ib + pos)")
p("        v.push(Instruction::LocalGet(slen));")
p("        v.push(Instruction::I64Const(32));")
p("        v.push(Instruction::I64Shl);")
p("        v.push(Instruction::I64Const(ib));")
p("        v.push(Instruction::LocalGet(pos));")
p("        v.push(Instruction::I64Add);")
p("        v.push(Instruction::I64Or);")
p("")
p("        Ok(v)")
p("    }")
p("")

# ===== json_return_int =====
p("    /// Emit WASM to write {\"result\": <digits>} to INPUT_BUF and call value_return.")
p("    fn json_return_int(&mut self, val_expr: Vec<Instruction<'static>>) -> Result<Vec<Instruction<'static>>, String> {")
p("        self.need_host(25);")
p("        let ma8 = wasm_encoder::MemArg { offset: 0, align: 0, memory_index: 0 };")
p("        let abs_val = self.local_idx(\"__jri_abs\");")
p("        let is_neg = self.local_idx(\"__jri_neg\");")
p("        let dc = self.local_idx(\"__jri_dc\");")
p("        let td = self.local_idx(\"__jri_td\");")
p("        let ptr = self.local_idx(\"__jri_ptr\");")
p("        let ib = INPUT_BUF as i64;")
p("        let mut v = Vec::new();")
p("")
p("        // Write prefix: {\"result\": (10 bytes)")
p("        let prefix: &[u8] = b\"{\\\"result\\\":\";")
p("        let prefix_len = prefix.len() as i64;")
p("        let prefix_off = self.alloc_data(prefix);")
p("")
p("        // Copy prefix bytes from data segment to INPUT_BUF")
p("        let copy_i = self.local_idx(\"__jri_ci\");")
p("        v.push(Instruction::I64Const(0));")
p("        v.push(Instruction::LocalSet(copy_i));")
p("        v.push(Instruction::Block(BlockType::Empty));")
p("        v.push(Instruction::Loop(BlockType::Empty));")
p("        v.push(Instruction::LocalGet(copy_i));")
p("        v.push(Instruction::I64Const(prefix_len));")
p("        v.push(Instruction::I64GeS);")
p("        v.push(Instruction::If(BlockType::Empty));")
p("        v.push(Instruction::Br(2));")
p("        v.push(Instruction::End);")
p("        // Load from data segment")
p("        v.push(Instruction::I64Const(prefix_off));")
p("        v.push(Instruction::LocalGet(copy_i));")
p("        v.push(Instruction::I64Add);")
p("        v.push(Instruction::I32WrapI64);")
p("        v.push(Instruction::I32Load8U(ma8.clone()));")
p("        // Store to INPUT_BUF")
p("        v.push(Instruction::I64Const(ib));")
p("        v.push(Instruction::LocalGet(copy_i));")
p("        v.push(Instruction::I64Add);")
p("        v.push(Instruction::I32WrapI64);")
p("        v.push(Instruction::I32Store8(ma8.clone()));")
p("        v.push(Instruction::LocalGet(copy_i));")
p("        v.push(Instruction::I64Const(1));")
p("        v.push(Instruction::I64Add);")
p("        v.push(Instruction::LocalSet(copy_i));")
p("        v.push(Instruction::Br(1));")
p("        v.push(Instruction::End);")
p("        v.push(Instruction::End);")
p("")
p("        // Write integer digits backwards from ib + prefix_len + 20")
p("        let digit_end = prefix_len + 21;")
p("        v.extend(val_expr);")
p("        v.push(Instruction::LocalSet(abs_val));")
p("")
p("        // Check negative")
p("        v.push(Instruction::LocalGet(abs_val));")
p("        v.push(Instruction::I64Const(0));")
p("        v.push(Instruction::I64LtS);")
p("        v.push(Instruction::I64ExtendI32U);")
p("        v.push(Instruction::LocalSet(is_neg));")
p("        v.push(Instruction::LocalGet(is_neg));")
p("        v.push(Instruction::I32WrapI64);")
p("        v.push(Instruction::If(BlockType::Result(ValType::I64)));")
p("        v.push(Instruction::I64Const(0));")
p("        v.push(Instruction::LocalGet(abs_val));")
p("        v.push(Instruction::I64Sub);")
p("        v.push(Instruction::Else);")
p("        v.push(Instruction::LocalGet(abs_val));")
p("        v.push(Instruction::End);")
p("        v.push(Instruction::LocalSet(abs_val));")
p("")
p("        v.push(Instruction::I64Const(digit_end));")
p("        v.push(Instruction::LocalSet(ptr));")
p("        v.push(Instruction::I64Const(0));")
p("        v.push(Instruction::LocalSet(dc));")
p("")
p("        // Handle 0")
p("        v.push(Instruction::LocalGet(abs_val));")
p("        v.push(Instruction::I64Eqz);")
p("        v.push(Instruction::I32WrapI64);")
p("        v.push(Instruction::If(BlockType::Empty));")
p("        v.push(Instruction::LocalGet(ptr));")
p("        v.push(Instruction::I64Const(1));")
p("        v.push(Instruction::I64Sub);")
p("        v.push(Instruction::LocalSet(ptr));")
p("        v.push(Instruction::I64Const(ib));")
p("        v.push(Instruction::LocalGet(ptr));")
p("        v.push(Instruction::I64Add);")
p("        v.push(Instruction::I32WrapI64);")
p("        v.push(Instruction::I64Const(0x30));")
p("        v.push(Instruction::I32Store8(ma8.clone()));")
p("        v.push(Instruction::I64Const(1));")
p("        v.push(Instruction::LocalSet(dc));")
p("        v.push(Instruction::Else);")
p("")
p("        // Digit loop")
p("        v.push(Instruction::Block(BlockType::Empty));")
p("        v.push(Instruction::Loop(BlockType::Empty));")
p("        v.push(Instruction::LocalGet(abs_val));")
p("        v.push(Instruction::I64Eqz);")
p("        v.push(Instruction::If(BlockType::Empty));")
p("        v.push(Instruction::Br(2));")
p("        v.push(Instruction::End);")
p("        v.push(Instruction::LocalGet(abs_val));")
p("        v.push(Instruction::I64Const(10));")
p("        v.push(Instruction::I64RemS);")
p("        v.push(Instruction::LocalSet(td));")
p("        v.push(Instruction::LocalGet(abs_val));")
p("        v.push(Instruction::I64Const(10));")
p("        v.push(Instruction::I64DivS);")
p("        v.push(Instruction::LocalSet(abs_val));")
p("        v.push(Instruction::LocalGet(ptr));")
p("        v.push(Instruction::I64Const(1));")
p("        v.push(Instruction::I64Sub);")
p("        v.push(Instruction::LocalSet(ptr));")
p("        v.push(Instruction::I64Const(ib));")
p("        v.push(Instruction::LocalGet(ptr));")
p("        v.push(Instruction::I64Add);")
p("        v.push(Instruction::I32WrapI64);")
p("        v.push(Instruction::LocalGet(td));")
p("        v.push(Instruction::I64Const(0x30));")
p("        v.push(Instruction::I64Add);")
p("        v.push(Instruction::I32Store8(ma8.clone()));")
p("        v.push(Instruction::LocalGet(dc));")
p("        v.push(Instruction::I64Const(1));")
p("        v.push(Instruction::I64Add);")
p("        v.push(Instruction::LocalSet(dc));")
p("        v.push(Instruction::Br(1));")
p("        v.push(Instruction::End);")
p("        v.push(Instruction::End);")
p("        v.push(Instruction::End); // else")
p("")
p("        // Add minus sign")
p("        v.push(Instruction::LocalGet(is_neg));")
p("        v.push(Instruction::I32WrapI64);")
p("        v.push(Instruction::If(BlockType::Empty));")
p("        v.push(Instruction::LocalGet(ptr));")
p("        v.push(Instruction::I64Const(1));")
p("        v.push(Instruction::I64Sub);")
p("        v.push(Instruction::LocalSet(ptr));")
p("        v.push(Instruction::I64Const(ib));")
p("        v.push(Instruction::LocalGet(ptr));")
p("        v.push(Instruction::I64Add);")
p("        v.push(Instruction::I32WrapI64);")
p("        v.push(Instruction::I64Const(0x2D));")
p("        v.push(Instruction::I32Store8(ma8.clone()));")
p("        v.push(Instruction::LocalGet(dc));")
p("        v.push(Instruction::I64Const(1));")
p("        v.push(Instruction::I64Add);")
p("        v.push(Instruction::LocalSet(dc));")
p("        v.push(Instruction::End);")
p("")
p("        // Now shift digits to position prefix_len. ptr..ptr+dc are the digit bytes.")
p("        // Copy to ib + prefix_len")
p("        let si = self.local_idx(\"__jri_si\");")
p("        v.push(Instruction::I64Const(0));")
p("        v.push(Instruction::LocalSet(si));")
p("        v.push(Instruction::Block(BlockType::Empty));")
p("        v.push(Instruction::Loop(BlockType::Empty));")
p("        v.push(Instruction::LocalGet(si));")
p("        v.push(Instruction::LocalGet(dc));")
p("        v.push(Instruction::I64GeS);")
p("        v.push(Instruction::If(BlockType::Empty));")
p("        v.push(Instruction::Br(2));")
p("        v.push(Instruction::End);")
p("        // Load from ib + ptr + si")
p("        v.push(Instruction::I64Const(ib));")
p("        v.push(Instruction::LocalGet(ptr));")
p("        v.push(Instruction::I64Add);")
p("        v.push(Instruction::LocalGet(si));")
p("        v.push(Instruction::I64Add);")
p("        v.push(Instruction::I32WrapI64);")
p("        v.push(Instruction::I32Load8U(ma8.clone()));")
p("        // Store to ib + prefix_len + si")
p("        v.push(Instruction::I64Const(ib + prefix_len));")
p("        v.push(Instruction::LocalGet(si));")
p("        v.push(Instruction::I64Add);")
p("        v.push(Instruction::I32WrapI64);")
p("        v.push(Instruction::I32Store8(ma8.clone()));")
p("        v.push(Instruction::LocalGet(si));")
p("        v.push(Instruction::I64Const(1));")
p("        v.push(Instruction::I64Add);")
p("        v.push(Instruction::LocalSet(si));")
p("        v.push(Instruction::Br(1));")
p("        v.push(Instruction::End);")
p("        v.push(Instruction::End);")
p("")
p("        // Write '}'")
p("        v.push(Instruction::I64Const(ib + prefix_len));")
p("        v.push(Instruction::LocalGet(dc));")
p("        v.push(Instruction::I64Add);")
p("        v.push(Instruction::I32WrapI64);")
p("        v.push(Instruction::I64Const(b'}' as i64));")
p("        v.push(Instruction::I32Store8(ma8.clone()));")
p("")
p("        // total_len = prefix_len + dc + 1")
p("        let tl = self.local_idx(\"__jri_tl\");")
p("        v.push(Instruction::I64Const(prefix_len));")
p("        v.push(Instruction::LocalGet(dc));")
p("        v.push(Instruction::I64Add);")
p("        v.push(Instruction::I64Const(1));")
p("        v.push(Instruction::I64Add);")
p("        v.push(Instruction::LocalSet(tl));")
p("")
p("        // value_return(total_len, ib)")
p("        v.push(Instruction::LocalGet(tl));")
p("        v.push(Instruction::I64Const(ib));")
p("        v.push(Self::host_call(25));")
p("")
p("        v.push(Instruction::I64Const(1));")
p("        v.push(Instruction::GlobalSet(1));")
p("        v.push(Instruction::I64Const(0));")
p("        Ok(v)")
p("    }")
p("")

# ===== json_return_str =====
p("    /// Emit WASM to write {\"result\": \"str\"} to INPUT_BUF and call value_return.")
p("    fn json_return_str(&mut self, packed_expr: Vec<Instruction<'static>>) -> Result<Vec<Instruction<'static>>, String> {")
p("        self.need_host(25);")
p("        let ma8 = wasm_encoder::MemArg { offset: 0, align: 0, memory_index: 0 };")
p("        let ib = INPUT_BUF as i64;")
p("        let packed = self.local_idx(\"__jrs_packed\");")
p("        let str_ptr = self.local_idx(\"__jrs_ptr\");")
p("        let str_len = self.local_idx(\"__jrs_len\");")
p("        let ci = self.local_idx(\"__jrs_ci\");")
p("        let mut v = Vec::new();")
p("")
p("        // Write prefix: {\"result\": \" (11 bytes)")
p("        let prefix: &[u8] = b\"{\\\"result\\\": \\\"\";")
p("        let prefix_len = prefix.len() as i64;")
p("        let prefix_off = self.alloc_data(prefix);")
p("")
p("        // Copy prefix")
p("        v.push(Instruction::I64Const(0));")
p("        v.push(Instruction::LocalSet(ci));")
p("        v.push(Instruction::Block(BlockType::Empty));")
p("        v.push(Instruction::Loop(BlockType::Empty));")
p("        v.push(Instruction::LocalGet(ci));")
p("        v.push(Instruction::I64Const(prefix_len));")
p("        v.push(Instruction::I64GeS);")
p("        v.push(Instruction::If(BlockType::Empty));")
p("        v.push(Instruction::Br(2));")
p("        v.push(Instruction::End);")
p("        v.push(Instruction::I64Const(prefix_off));")
p("        v.push(Instruction::LocalGet(ci));")
p("        v.push(Instruction::I64Add);")
p("        v.push(Instruction::I32WrapI64);")
p("        v.push(Instruction::I32Load8U(ma8.clone()));")
p("        v.push(Instruction::I64Const(ib));")
p("        v.push(Instruction::LocalGet(ci));")
p("        v.push(Instruction::I64Add);")
p("        v.push(Instruction::I32WrapI64);")
p("        v.push(Instruction::I32Store8(ma8.clone()));")
p("        v.push(Instruction::LocalGet(ci));")
p("        v.push(Instruction::I64Const(1));")
p("        v.push(Instruction::I64Add);")
p("        v.push(Instruction::LocalSet(ci));")
p("        v.push(Instruction::Br(1));")
p("        v.push(Instruction::End);")
p("        v.push(Instruction::End);")
p("")
p("        // Unpack string")
p("        v.extend(packed_expr);")
p("        v.push(Instruction::LocalSet(packed));")
p("        v.push(Instruction::LocalGet(packed));")
p("        v.push(Instruction::I32WrapI64);")
p("        v.push(Instruction::I64ExtendI32U);")
p("        v.push(Instruction::LocalSet(str_ptr));")
p("        v.push(Instruction::LocalGet(packed));")
p("        v.push(Instruction::I64Const(32));")
p("        v.push(Instruction::I64ShrU);")
p("        v.push(Instruction::LocalSet(str_len));")
p("")
p("        // Copy string bytes to ib + prefix_len")
p("        v.push(Instruction::I64Const(0));")
p("        v.push(Instruction::LocalSet(ci));")
p("        v.push(Instruction::Block(BlockType::Empty));")
p("        v.push(Instruction::Loop(BlockType::Empty));")
p("        v.push(Instruction::LocalGet(ci));")
p("        v.push(Instruction::LocalGet(str_len));")
p("        v.push(Instruction::I64GeS);")
p("        v.push(Instruction::If(BlockType::Empty));")
p("        v.push(Instruction::Br(2));")
p("        v.push(Instruction::End);")
p("        v.push(Instruction::LocalGet(str_ptr));")
p("        v.push(Instruction::LocalGet(ci));")
p("        v.push(Instruction::I64Add);")
p("        v.push(Instruction::I32WrapI64);")
p("        v.push(Instruction::I32Load8U(ma8.clone()));")
p("        v.push(Instruction::I64Const(ib + prefix_len));")
p("        v.push(Instruction::LocalGet(ci));")
p("        v.push(Instruction::I64Add);")
p("        v.push(Instruction::I32WrapI64);")
p("        v.push(Instruction::I32Store8(ma8.clone()));")
p("        v.push(Instruction::LocalGet(ci));")
p("        v.push(Instruction::I64Const(1));")
p("        v.push(Instruction::I64Add);")
p("        v.push(Instruction::LocalSet(ci));")
p("        v.push(Instruction::Br(1));")
p("        v.push(Instruction::End);")
p("        v.push(Instruction::End);")
p("")
p("        // Write '\"}'")
p("        v.push(Instruction::I64Const(ib));")
p("        v.push(Instruction::LocalGet(str_len));")
p("        v.push(Instruction::I64Add);")
p("        v.push(Instruction::I64Const(prefix_len));")
p("        v.push(Instruction::I64Add);")
p("        v.push(Instruction::I32WrapI64);")
p("        v.push(Instruction::I64Const(0x22));")
p("        v.push(Instruction::I32Store8(ma8.clone()));")
p("")
p("        v.push(Instruction::I64Const(ib));")
p("        v.push(Instruction::LocalGet(str_len));")
p("        v.push(Instruction::I64Add);")
p("        v.push(Instruction::I64Const(prefix_len + 1));")
p("        v.push(Instruction::I64Add);")
p("        v.push(Instruction::I32WrapI64);")
p("        v.push(Instruction::I64Const(b'}' as i64));")
p("        v.push(Instruction::I32Store8(ma8.clone()));")
p("")
p("        // value_return(prefix_len + str_len + 2, ib)")
p("        v.push(Instruction::I64Const(prefix_len));")
p("        v.push(Instruction::LocalGet(str_len));")
p("        v.push(Instruction::I64Add);")
p("        v.push(Instruction::I64Const(2));")
p("        v.push(Instruction::I64Add);")
p("        v.push(Instruction::I64Const(ib));")
p("        v.push(Self::host_call(25));")
p("")
p("        v.push(Instruction::I64Const(1));")
p("        v.push(Instruction::GlobalSet(1));")
p("        v.push(Instruction::I64Const(0));")
p("        Ok(v)")
p("    }")


