;; RLM Runtime - Algorithm 1 from MIT RLM Paper
;; Implemented as Lisp code that runs inside lisp-rlm
;;
;; Usage:
;;   (load-file "rlm_runtime.lisp")
;;   (run-rlm "your task here")
;;
;; Changes from previous version:
;;   - rlm-set/rlm-get now use bare symbols (no quoting needed)
;;   - sub-rlm has proper state isolation (saves/restores parent state)
;;   - Uses load-file pattern

;; ============================================================
;; 1. INITIALIZATION
;; ============================================================
;; Policy knob defaults — policy.lisp (loaded after the runtime)
;; rebinds these via its own defines; env lookup at call time picks
;; up the override. Defined HERE so init-rlm's body compiles them as
;; variable refs, not symbol passthrough (cross-file forward refs
;; compile to symbol values otherwise).
(define POLICY_MAX_ITER 16)
(define POLICY_STOP_ERRS 0)
;; Q-layer defaults — scripts/rlm-tasks/q-table.lisp (generated by
;; scripts/rlm-qlearn.py from banked worlds) rebinds these. Empty table
;; ⇒ every state falls back to the hand-coded ladder (bootstrap policy).
(define Q-ENABLED false)
(define Q-EPS 10)
(define Q-TABLE (list))
;; Custom actions — proposed by the dream task (agent-written lisp),
;; A/B-gated by rlm-abgate.py. Format: (name lambda(rc)->string).
(define CUSTOM-ACTIONS (list))
(define (rlm-register-action name fn)
  (set! CUSTOM-ACTIONS (append CUSTOM-ACTIONS (list (list name fn)))))
(define (rlm-scope-action name prefixes)
  ;; Attach a task-scope to a registered action (2026-10-01): prefixes
  ;; is a list of task-id prefixes the action may fire on. Dream-proposed
  ;; actions default to global unless scoped here.
  (set! CUSTOM-ACTIONS
    (map (lambda (e)
           (if (and (equal? (to-string (car e)) (to-string name)) (= (len e) 2))
             (append e (list prefixes))
             e))
         CUSTOM-ACTIONS)))
(define (action-allowed? e)
  ;; nil/empty scope = global; else current trace_id must start with one
  ;; of the scope prefixes.
  ;; NB: to-string is the JSON repr (strings gain quotes) — never wrap
  ;; rlm-get values with it for identity/matching. Raw value or "".
  (let ((sc (try (car (cdr (cdr e))) (catch e2 nil)))
        (tid (if (string? (rlm-get __trace_id)) (rlm-get __trace_id) "")))
    (if (or (nil? sc) (= (len sc) 0)) true
      (some (lambda (p)
              (let ((n (str-length p)))
                (if (>= (str-length tid) n)
                  (equal? (str-substring tid 0 n) p)
                  false)))
            sc))))
(define (init-rlm P)
  (begin
    (rlm-set prompt P)
    (rlm-set prompt_length (str-length P))
    (rlm-set prompt_preview (str-substring P 0 300))
    (rlm-set Final nil)
    (rlm-set iteration 0)
    (rlm-set max_iterations 15)
    (rlm-set exec_log (list))
    (rlm-set result nil)
    (rlm-set __trace_nodes (list))
    (rlm-set __last_code "")
    (rlm-set __gate_failed false)
    (rlm-set __last_out "")
    (rlm-set __repeat_count 0)
    (rlm-set __err_streak 0)
    (rlm-set __phantom_bounces 0)
    (rlm-set __must_decompose nil)
    (rlm-set __stop false)
    ;; Exploration policy knobs (policy.lisp MUST define these; the
    ;; generator guarantees them — see scripts/gen-grammar.py)
    (rlm-set max_iterations POLICY_MAX_ITER)
    (rlm-set stop_after_errs POLICY_STOP_ERRS)
    (println "RLM initialized")))

;; ============================================================
;; TRACE EMISSION (Dream-RSI layer: history as replay simulator)
;; One JSON node per iteration; run-rlm writes the world file.
;; ============================================================
(define NL "
")
(define (json-safe s)
  (let ((t (if (string? s) s (to-string s))))
    (str-replace
      (str-replace (str-replace t NL "~~NL~~") "\"" "~~QT~~")
      "\\" "~~BS~~")))
(define (trace-node-json i code ok out s a)
  (str-concat "{\"i\":" (to-string i)
              ",\"ok\":" (if ok "true" "false")
              ",\"s\":\"" (json-safe s) "\""
              ",\"a\":\"" (json-safe a) "\""
              ",\"code\":\"" (json-safe code) "\""
              ",\"out\":\"" (json-safe out) "\"}"))
(define (join-nodes lst)
  (if (= (len lst) 0) ""
    (if (= (len lst) 1) (car lst)
      (str-concat (car lst) "," (join-nodes (cdr lst))))))
(define (write-trace)
  (let ((id (json-safe (rlm-get __trace_id)))
        (pol (json-safe (rlm-get __policy)))
        (ts (to-string (now))))
    (begin
      (write-file (str-concat "data/rlm/traces/" (rlm-get __trace_id) ".json")
        (str-concat "{\"task_id\":\"" id "\""
          ",\"ts\":" ts
          ",\"policy\":\"" pol "\""
          ",\"task\":\"" (json-safe (rlm-get prompt)) "\""
          ",\"completed\":" (if (rlm-get Final) "true" "false")
          ",\"iterations\":" (to-string (rlm-get iteration))
          ",\"result\":\"" (json-safe (rlm-get result)) "\""
          ",\"answer\":\"" (json-safe (to-string (rlm-get answer))) "\""
          ",\"lesson\":\"" (json-safe (rlm-get __lesson)) "\""
          ",\"nodes\":[" (join-nodes (rlm-get __trace_nodes)) "]}")))))

;; Anti-repetition escalation: greedy sampling repeats identical code on
;; identical context — so when code repeats, CHANGE the context:
;; full error (untruncated) + the model's own failed code + the failing
;; builtin's doc signature, then demand a strategy change.
(define (error-fn-name out)
  (if (str-contains out "ERROR: ")
    (let ((rest (str-substring out 7 (str-length out))))
      (let ((colon (str-index-of rest ": ")))
        (if (>= colon 0)
          (str-substring rest 0 colon)
          "")))
    ""))

(define (error-fn-doc out)
  (let ((fname (error-fn-name out)))
    (if (not (= fname ""))
      (let ((d (doc fname)))
        (if (str-contains d " — ")
          (str-concat "\nThe function you called is documented as:\n" d "\n")
          ""))
      "")))

;; Concrete hints for the most common misunderstanding: 'sym is a SYMBOL,
;; not a string and not a list. Errors of the "need list/need string" class
;; almost always come from passing 'sym where data was meant.
(define (error-class-hint out)
  (if (str-contains out "need list")
    (str-concat
      "\nTYPE HINT: in lisp-rlm 'sym is a SYMBOL — it is NOT a string and NOT a list.\n"
      "Strings use double quotes: \"precaution\". If a function needs a LIST, build one: (list a b c)\n"
      "or convert: (str->list \"abc\") if available, else iterate the string by index.\n")
    ""))

;; ============================================================
;; Q-LAYER (Dream v3): learned per-state escalation policy.
;; State: (task-id, error-class, failing-fn, repeat-bin, err-streak-bin, iter-bin)
;; The task-id prefix is REQUIRED: the same error shape on different tasks is
;; a different disease (t2_reverse argtype ≠ td_foldsum argtype). The dream
;; layer cites full states, so targeting inherits task granularity.
;; Actions: none temp08 temp10 doc hint ban budget2 stop ladder
;; Chosen ε-greedy from Q-TABLE; missing state → 'ladder (hand-coded
;; composite, the bootstrap). All decisions recorded in trace nodes.
;; ============================================================
(define (q-classify out)
  (cond
    ((not (str-contains out "ERROR:")) "ok")
    ((str-contains out "type error") "type")
    ((or (str-contains out "need list") (str-contains out "need string") (str-contains out "expects")) "argtype")
    ((str-contains out "Parse") "parse")
    ((str-contains out "arity") "arity")
    (true "runtime")))
(define (q-bin v) (if (>= v 3) 3 v))
(define (q-task-tag)
  (let ((tid (rlm-get __trace_id))) (if tid tid "anon")))
(define (q-state)
  (let ((out (rlm-get __last_out)))
    (str-concat (q-task-tag) "|" (q-classify out) "|" (error-fn-name out)
      "|rc" (to-string (q-bin (rlm-get __repeat_count)))
      "|es" (to-string (q-bin (rlm-get __err_streak)))
      "|i" (to-string (if (>= (rlm-get iteration) 5) 3 (+ 1 (quotient (rlm-get iteration) 2)))))))
(define (q-avail s)
  (let ((parts (str-split s "|"))
        (fnok (not (= (error-fn-name (rlm-get __last_out)) ""))))
    (append
      (list "none" "temp08" "temp10" "stop" "ladder" "decompose")
      (map (lambda (e) (car e)) (filter action-allowed? CUSTOM-ACTIONS))
      (if fnok (list "doc" "ban") (list))
      (if (str-contains s "argtype") (list "hint") (list))
      (if (< (rlm-get iteration) (- (rlm-get max_iterations) 2)) (list "budget2") (list)))))
(define (q-entry s)
  (let ((e (assoc s Q-TABLE)))
    (if e (car (cdr e)) nil)))
(define (q-best-pair acts)
  ;; recursive max — set! inside map-lambdas cannot mutate closure vars
  (if (= (len acts) 1) (car acts)
    (let ((b (q-best-pair (cdr acts))))
      (if (> (car (cdr (car acts))) (car (cdr b))) (car acts) b))))
(define (q-best s)
  (let ((acts (q-entry s)))
    (if (and acts (> (len acts) 0)) (to-string (car (q-best-pair acts))) nil)))
(define (q-pick s)
  ;; deterministic-but-decorrelated pseudo-random: varies with state and history
  (let ((avail (q-avail s))
        (r (mod (+ (* (rlm-get iteration) 7) (str-length (rlm-get __last_code)) (rlm-get __err_streak)) 100)))
    (if (and Q-ENABLED (< r Q-EPS))
      (nth avail (mod (+ r (rlm-get iteration)) (len avail)))
      (let ((b (q-best s)))
        (if b b "ladder")))))
(define (q-choose)
  ;; decide + apply side effects; returns (state . action) strings
  (let* ((s (q-state))
         (a (if (= s "ok||rc0|es0|i1") "none" (q-pick s))))
    (begin
      (if (equal? a "budget2") (rlm-set max_iterations (+ (rlm-get max_iterations) 2)))
      (if (equal? a "stop") (rlm-set __stop true))
      (begin (rlm-set __q_s s) (rlm-set __q_a a) a))))

;; Escalation rendering, action-driven. Base = pure information (no temp
;; marker — temperature is an ACTION now, chosen by Q or ladder).
(define (esc-base rc)
  (let ((out (rlm-get __last_out)))
    (str-concat
      "\n\nYOUR LAST CODE (this FAILED — do not resubmit it):\n"
      (rlm-get __last_code) "\n\n"
      "FULL ERROR MESSAGE (not truncated):\n" out "\n")))
(define (esc-marker rc)
  ;; shim reads this marker → temp 0.8
  (str-concat "\n⚠ YOU REPEATED THE SAME CODE " (to-string rc) "+ TIMES AND IT FAILED.\n"))
(define (esc-marker10 rc)
  ;; marker + STRATEGY CHANGE → shim temp 1.0
  (str-concat (esc-marker rc)
    "STRATEGY CHANGE REQUIRED: abandon the failing function entirely; solve it with a different construct (explicit while/dotimes loop with a set! counter, or plain recursion).\n"))
(define (esc-action a)
  (let ((out (rlm-get __last_out))
        (fname (error-fn-name (rlm-get __last_out)))
        (rc (rlm-get __repeat_count))
        (custom (assoc a CUSTOM-ACTIONS)))
    (if (and custom (action-allowed? custom))
      ((car (cdr custom)) rc)
      (cond
      ((equal? a "doc") (error-fn-doc out))
      ((equal? a "hint") (error-class-hint out))
      ((equal? a "ban")
        (if (not (= fname ""))
          (str-concat "\n⛔ " fname " is now BANNED for this task — your code must NOT contain the symbol " fname ".\n")
          ""))
      ((equal? a "budget2") "\nYou have EXTRA budget — reason carefully and try a fundamentally different approach.\n")
      ((equal? a "temp08") (str-concat (esc-marker rc) "\nWrite DIFFERENT code than your last attempt.\n"))
      ((equal? a "temp10") (esc-marker10 rc))
      ((equal? a "stop") "")
      ((equal? a "none") "")
      ((equal? a "decompose")
        (str-concat
          "\n⚡ DECOMPOSITION REQUIRED. This problem is too big to solve flat.\n"
          "Your next expression MUST delegate one piece to a sub-solver:\n"
          "  (rlm-set <key> (sub-rlm \"<precise description of ONE sub-problem>\"))\n"
          "Examples: (sub-rlm \"reverse the tail (2 3 4) and I'll prepend 1\"),\n"
          "         (sub-rlm \"compute insert of 7 into the left subtree, return new subtree\")\n"
          "Solve ONLY the piece you keep; delegate the rest.\n"))
      ;; 'ladder = hand-coded composite (bootstrap policy)
      (true (str-concat
              (if (>= rc 2) (esc-marker10 rc) (esc-marker rc))
              (error-fn-doc out)
              (error-class-hint out)
              (if (and (>= rc 2) (not (= fname "")))
                (str-concat "\n⛔ " fname " is now BANNED for this task — your code must NOT contain the symbol " fname ".\n")
                "")
              (if (= rc 1) "\nWrite DIFFERENT code than your last attempt.\n" "")))))))
(define (build-escalation a)
  (let ((rc (rlm-get __repeat_count)))
    (if (or (< rc 1) (equal? a "none")) ""
      (str-concat (esc-base rc) (esc-action a)))))

;; ============================================================
;; 2. CONTEXT BUILDER
;; Only sends metadata + state, never the full prompt
;; ============================================================
(define (escalation-and-cheatsheet a)
  ;; fb (one-shot gate feedback) + cheatsheet + CCG memory + escalation,
  ;; hoisted into a simple helper — nested try/if inside str-concat args
  ;; made the CPS compiler emit a pathological loop (1M-eval burn before
  ;; iteration 1). mem = per-task cross-episode decision memory (CCG lane).
  (let ((fb (rlm-get __gate_feedback))
        (cheat (try (read-file "data/rlm/dream/cheatsheet.txt") (catch e "")))
        (mem (try (read-file (str-concat "data/rlm/ccg/" (q-task-tag) ".txt")) (catch e ""))))
    (begin
      (if (and fb (not (= fb ""))) (rlm-set __gate_feedback ""))
      (str-concat
        (if (and fb (not (= fb ""))) fb "")
        "\n" cheat "\n" mem "\n" (build-escalation a)))))

(define (rlm-build-context _sa)
  (let ((task (rlm-get prompt))
        (iter (rlm-get iteration))
        (preview (rlm-get prompt_preview))
        (p_len (rlm-get prompt_length))
        (final_val (rlm-get result))
        (log (rlm-get exec_log)))
    (str-concat
      "You are a Recursive Language Model running in a Lisp REPL.\n"
      "Your task: " task "\n\n"
      "Prompt metadata: " (to-string p_len) " chars total, preview:\n"
      (str-substring preview 0 200) "...\n\n"
      "Current iteration: " (to-string iter) "\n"
      "Current result so far: " (to-string final_val) "\n\n"
      "Recent execution log:\n" (to-string log) "\n"
      (escalation-and-cheatsheet (rlm-get __q_a))
      "\nGenerate ONE Lisp expression to execute. You can:\n"
      "- Use (rlm-set key value) to store results (bare symbol keys, no quoting)\n"
      "- Use (rlm-set Final t) and (rlm-set result <val>) when done\n"
      "- Use (sub-rlm \"sub-task\") to delegate sub-problems\n"
      "- Use (rlm-get prompt) to read the full prompt\n"
      "- Use string functions to slice/inspect the prompt\n"
      "Return ONLY valid Lisp code.")))

;; ============================================================
;; 3. SINGLE STEP
;; Snapshot -> Generate -> Execute -> Log or Rollback
;; ============================================================
(define (llm-retry ctx)
  ;; one retry on transient shim failures ("model busy" during sweeps)
  (let ((r (try (llm-code ctx) (catch e (str-concat "LLMFAIL:" (to-string e))))))
    (if (str-contains r "LLMFAIL")
      (begin (sleep 5) (llm-code ctx))
      r)))
(define (parse-fix ctx code)
  ;; free parse pre-check: one re-ask on syntax errors, no iteration burned.
  ;; read-all: validates the WHOLE response (multi-form included).
  (let ((bad (try (begin (read-all code) "") (catch e (to-string e)))))
    (if (= bad "")
      code
      (llm-retry (str-concat ctx "\n\nYOUR LAST SUBMISSION DID NOT PARSE: " bad "\nResubmit ONE valid lisp expression.")))))

;; ---- few-shot exemplars (own-corpus self-distillation) ----
;; scripts/rlm-tasks/exemplars/<task>.txt holds ONE worked form.
;; Hand-written bootstrap exemplars use DIFFERENT input data than the
;; task (teach the pattern, not the answer). Auto-mined exemplars
;; (scripts/rlm-exemplars.py) refresh only for mastered tasks and never
;; overwrite hand-written files (they start with "# hand").
;; pre-seed: build-prompt references GRAMMAR which is (re)defined by
;; scripts/rlm-tasks/policy.lisp AFTER this file loads. Without the
;; pre-seed the reference compiles to SYMBOL PASSTHROUGH (cross-file
;; define landmine) and the grammar silently vanishes from prompts.
(define GRAMMAR "GRAMMAR-UNSET")

(define (exemplar-file-or f)
  (try (read-file f) (catch e "")))
(define (tactics-for-task path tid)
  ;; Task-scope tactics (2026-10-01): keep ONLY this task's tagged lines
  ;; ("- For <task>: ...") plus untagged general advice. Cross-task
  ;; scaffolds (prime? hints landing on lending tasks) were being
  ;; copy-pasted by the small brain → 80-line paren-explosion spirals.
  (let ((raw (exemplar-file-or path)))
    (if (or (not (string? tid)) (= (str-length raw) 0)) raw
      (str-join "\n"
        (filter (lambda (l)
                  (or (not (str-contains l "For "))
                      (str-contains l (str-concat "For " tid ":"))))
                (str-split raw "\n"))))))
(define (build-prompt ctx)
  (let ((ex (exemplar-file-or
              (str-concat "scripts/rlm-tasks/exemplars/" (rlm-get __trace_id) ".txt")))
        (tac (tactics-for-task "scripts/rlm-tasks/tactics.txt"
                               (rlm-get __trace_id))))
    (str-concat GRAMMAR
      (if (> (str-length tac) 0)
        (str-concat "\n\nTACTICS — your own self-written advice, updated by the dream layer:\n" tac)
        "")
      (if (> (str-length ex) 0)
        (str-concat "\n\nWORKED EXAMPLE — same pattern, DIFFERENT input data. Adapt the pattern, do NOT copy it verbatim:\n" ex)
        "")
      "\n\nTASK CONTEXT:\n" ctx)))


;; ============================================================
;; 3a. PRE-FLIGHT PHANTOM LINT (CCG lane, 2026-09-21)
;; Known-phantom calls (real builtin + "?" suffix, e.g. member?)
;; bounce BEFORE eval — free resubmit, no iteration burn (≤2/episode).
;; NOTE: eager compiler — defines below are strictly order-respecting,
;; no forward refs, no mutual recursion (single walker `lp`).
;; known-fns.txt generated from kernel sources: scripts/gen-known-fns.py
;; ============================================================
(define KNOWN_FNS nil)

(define (known-fns!)
  (if KNOWN_FNS nil
    (set! KNOWN_FNS
      (filter (fn (l) (> (str-length l) 0))
        (map (fn (l) (str-trim l))
          (str-split (try (read-file "data/rlm/ccg/known-fns.txt") (catch e "")) "\n"))))))

(define (known-fn? s defs)
  (or (member s KNOWN_FNS) (member s defs)))

;; phantom check for one form's head; false = clean
(define (lp-head f defs)
  (let ((h (to-string (car f))))
    (if (known-fn? h defs) false
      (if (and (> (str-length h) 1)
               (equal? (str-substring h (- (str-length h) 1) (str-length h)) "?")
               (known-fn? (str-substring h 0 (- (str-length h) 1)) defs))
        (str-concat h " does not exist — did you mean '" (str-substring h 0 (- (str-length h) 1)) "'? (known phantom from past episodes; resubmit with the real name)")
        false))))

;; walk a list of forms; skips quoted data; descends into define bodies
(define (lp forms defs)
  (if (= (len forms) 0) false
    (let ((f (car forms)))
      (if (not (list? f)) (lp (cdr forms) defs)
        (if (= (len f) 0) (lp (cdr forms) defs)
          (if (equal? (car f) (quote quote)) (lp (cdr forms) defs)
            (if (equal? (car f) (quote define))
              (let ((r (lp (cdr (cdr f)) defs)))
                (if r r (lp (cdr forms) defs)))
              (let ((r (lp-head f defs)))
                (if r r (lp (cdr f) defs))))))))))

(define (collect-defines forms acc)
  (if (= (len forms) 0) acc
    (let ((f (car forms)))
      (if (and (list? f) (>= (len f) 2) (equal? (car f) (quote define)) (list? (car (cdr f))))
        (collect-defines (cdr forms) (cons (to-string (car (car (cdr f)))) acc))
        (collect-defines (cdr forms) acc)))))

(define (lint-phantom code)
  (known-fns!)
  (let ((forms (try (read-all code) (catch e nil))))
    (if (= (len forms) 0) false
      (let ((defs (collect-defines forms (list))))
        (lp forms defs)))))

(define (rlm-step)
  (begin
    (reset-eval-budget)
    (snapshot)
    (let ((qa (q-choose)))
      (let ((ctx (rlm-build-context qa)))
        (let ((code (parse-fix ctx (llm-retry ctx))))
          ;; PRE-FLIGHT PHANTOM LINT (CCG lane): a known phantom call
          ;; (real builtin + "?" suffix, e.g. member?) bounces for FREE —
          ;; no iteration burn, ≤2 bounces/episode, traced for memory.
          (let ((lint (lint-phantom code)))
            (if (and lint (< (rlm-get __phantom_bounces) 2))
              (begin
                (rlm-set __phantom_bounces (+ (rlm-get __phantom_bounces) 1))
                (rlm-set __last_code code)
                (rlm-set __last_out (str-concat "ERROR: " lint))
                (rlm-set __trace_nodes
                  (append (rlm-get __trace_nodes)
                    (list (trace-node-json (rlm-get iteration) code false (rlm-get __last_out) (rlm-get __q_s) qa))))
                (println (str-concat "[RLM " (to-string (rlm-get iteration)) "] PHANTOM-BOUNCE (free resubmit)"))
                (rlm-get __last_out))
          ;; FORCE GATE: decompose action OR task-level must-decompose flag —
          ;; the next expression MUST contain a sub-rlm delegation or it bounces.
          (if (and (or (equal? qa "decompose") (rlm-get __must_decompose))
                   (not (str-contains code "sub-rlm")))
            (begin
              (rlm-set iteration (+ (rlm-get iteration) 1))
              (rlm-set __last_code code)
              (rlm-set __last_out "ERROR: decompose-rejected — this step MUST delegate via (sub-rlm \"...\"); resubmit with a delegation")
              (rlm-set __err_streak (+ (rlm-get __err_streak) 1))
              (rlm-set __trace_nodes
                (append (rlm-get __trace_nodes)
                  (list (trace-node-json (rlm-get iteration) code false (rlm-get __last_out) (rlm-get __q_s) qa))))
              (println (str-concat "[RLM " (to-string (rlm-get iteration)) "] DECOMPOSE-REJECTED"))
              (rlm-get __last_out))
            (let ((exec-result
                  (try
                    ;; MULTI-FORM TOLERANCE: models naturally emit sequences
                    ;; (define helper) (define answer) (final true). (read s)
                    ;; returns ONLY the first form — the rest silently vanished,
                    ;; which is what starved t2_reverse/t3_fib of completions.
                    ;; read-all + begin-wrap executes the whole response as one
                    ;; snapshot/rollback unit.
                    (eval
                      (let ((forms (read-all code)))
                        (if (= (len forms) 1)
                          (car forms)
                          (cons (quote begin) forms))))
                    (catch e
                      (begin
                        (rollback)
                        (str-concat "ERROR: " (to-string e)))))))
            (let ((is-error (str-contains (to-string exec-result) "ERROR:")))
              ;; anti-repetition tracking: consecutive identical generations
              (if (equal? code (rlm-get __last_code))
                (rlm-set __repeat_count (+ (rlm-get __repeat_count) 1))
                (rlm-set __repeat_count 0))
              (rlm-set __last_code code)
              (rlm-set __last_out (to-string exec-result))
              (if is-error
                (rlm-set __err_streak (+ (rlm-get __err_streak) 1))
                (rlm-set __err_streak 0))
              (rlm-set __trace_nodes
                (append (rlm-get __trace_nodes)
                  (list (trace-node-json (+ (rlm-get iteration) 1) code (not is-error) exec-result (rlm-get __q_s) qa))))
            (rlm-set exec_log
              (append (rlm-get exec_log)
                (list (str-concat "iter " (to-string (rlm-get iteration))
                       ": " (str-substring (to-string exec-result) 0 200)))))
            (rlm-set iteration (+ (rlm-get iteration) 1))
            (if is-error
              (println (str-concat "[RLM " (to-string (rlm-get iteration)) "] ERR - retrying"))
              (println (str-concat "[RLM " (to-string (rlm-get iteration)) "] OK")))
            exec-result))))))))))

;; ============================================================
;; 4. MAIN LOOP
;; Runs until Final is set or max iterations reached
;; ============================================================
(define (rlm-loop)
  (if (rlm-get Final)
    (begin
      (println (str-concat "RLM completed in " (to-string (rlm-get iteration)) " iterations"))
      (rlm-get result))
    (if (> (rlm-get iteration) (rlm-get max_iterations))
      (begin
        (println "RLM: max iterations reached")
        (rlm-get result))
      (if (and (> (rlm-get stop_after_errs) 0)
               (>= (rlm-get __err_streak) (rlm-get stop_after_errs)))
        (begin
          (println (str-concat "RLM: stopped after " (to-string (rlm-get __err_streak)) " consecutive errors (policy)"))
          (rlm-get result))
        (if (rlm-get __stop)
          (begin
            (println "RLM: stopped (Q-action stop)")
            (rlm-get result))
          (begin
            (rlm-step)
            ;; bank partials: a wall episode killed by the harness alarm
            ;; mid-retry still leaves an honest world (completed=false)
            (write-trace)
            (rlm-loop)))))))

;; ============================================================
;; 5. SUB-RLM (recursive sub-problem solving)
;; Isolated state: saves all parent rlm_state keys, runs sub-task,
;; then restores parent state completely.
;; ============================================================
(define (sub-rlm sub-prompt)
  ;; Save parent state
  (let ((saved-prompt (rlm-get prompt))
        (saved-iter (rlm-get iteration))
        (saved-result (rlm-get result))
        (saved-log (rlm-get exec_log))
        (saved-final (rlm-get Final))
        (saved-max (rlm-get max_iterations))
        (saved-preview (rlm-get prompt_preview))
        (saved-plen (rlm-get prompt_length))
        (saved-trace (rlm-get __trace_nodes))
        (saved-tid (rlm-get __trace_id))
        (saved-pol (rlm-get __policy)))
    ;; Run sub-task with clean state
    (begin
      (init-rlm sub-prompt)
      (rlm-set max_iterations 5)
      (rlm-set __trace_id (str-concat (rlm-get __trace_id) "-sub"))
      (let ((sub-result (rlm-loop)))
        ;; the sub's ANSWER is the payload — capture AFTER the loop ran,
        ;; BEFORE the restore (nested let: parallel let reads stale state)
        (let ((sub-answer (rlm-get answer)))
        ;; capture the sub-episode BEFORE restore so it banks into the
        ;; parent world — sub iterations feed Q and the journal too
        (let ((sub-nodes (rlm-get __trace_nodes)))
          (begin
            (rlm-set prompt saved-prompt)
          (rlm-set iteration saved-iter)
          (rlm-set result saved-result)
          (rlm-set exec_log saved-log)
          (rlm-set Final saved-final)
          (rlm-set max_iterations saved-max)
          (rlm-set prompt_preview saved-preview)
          (rlm-set prompt_length saved-plen)
          (rlm-set __trace_id saved-tid)
          (rlm-set __policy saved-pol)
          (rlm-set __trace_nodes (append saved-trace sub-nodes))
          (if sub-answer sub-answer sub-result))))))))

;; ============================================================
;; LESSON (the failure journal): one reflective sentence per run,
;; generated by the model itself. For science. And comedy.
;; ============================================================
(define (gen-lesson-once)
  (str-substring
    (llm (str-concat
      "You are a small Lisp program that just finished (or failed) a task. Reflect honestly.\n"
      "Task: " (str-substring (rlm-get prompt) 0 120) "\n"
      "Iterations used: " (to-string (rlm-get iteration)) "\n"
      "Solved: " (if (rlm-get __gate_failed)
                  "NO — the verify gate REJECTED your answer. You claimed (final true) but the answer you stored was WRONG."
                  (if (rlm-get Final) "yes" "no")) "\n"
      "Final answer stored: " (str-substring (to-string (rlm-get answer)) 0 60) "\n"
      "Last code you ran:\n" (str-substring (rlm-get __last_code) 0 200) "\n"
      "Last output/error: " (str-substring (rlm-get __last_out) 0 300) "\n\n"
      "Write ONE sentence starting 'Today I learned' naming the SPECIFIC technical "
      "insight or mistake — exact function name, argument order, or data shape. "
      "Max 20 words.\n"
      "GOOD: Today I learned str-join takes the separator FIRST: (str-join sep lst).\n"
      "GOOD: Today I learned returning the input unchanged fails the verify gate.\n"
      "BAD (forbidden): Today I learned Lisp state management is complex.\n"
      "BAD (forbidden): Today I learned tiny programs can do complex math."))
    0 220))
(define (gen-lesson)
  (try
    (let ((L (gen-lesson-once)))
      (if (= (str-length (str-trim L)) 0) (gen-lesson-once) L))
    (catch e "")))
(define (re-lesson)
  ;; Called by the task's verify gate on rejection: nil Final, regenerate
  ;; the lesson with the honest "gate rejected you" context, rewrite trace.
  (begin
    (rlm-set Final nil)
    (rlm-set __gate_failed true)
    (rlm-set __lesson (gen-lesson))
    (write-trace)))

;; ============================================================
;; RETRY-WITH-FEEDBACK: the gate speaks DURING the episode.
;; On verify-fail, resume the same episode (Final=nil) with the
;; expected-vs-actual verdict injected into the next context.
;; ============================================================
(define (retry-with-feedback verify-fn expected-str rounds)
  (if (try (verify-fn (rlm-get answer)) (catch e false))
    true
    (if (<= rounds 0)
      false
      (begin
        (rlm-set Final nil)
        (rlm-set __gate_feedback
          (str-concat
            "\n*** VERIFY GATE VERDICT: WRONG ***\n"
            "You finished, but the answer you stored is incorrect.\n"
            "Your answer:    " (str-substring (to-string (rlm-get answer)) 0 120) "\n"
            "Correct answer: " expected-str "\n"
            "Compare them character by character, find the difference, then write\n"
            "lisp that produces the correct value, (rlm-set answer <correct-value>),\n"
            "and finish with (rlm-set Final t).\n"))
        (let ((res (rlm-loop)))
          (begin
            (write-trace)
            (if (try (verify-fn (rlm-get answer)) (catch e false))
              true
              (retry-with-feedback verify-fn expected-str (- rounds 1)))))))))

;; ============================================================
;; 6. ENTRY POINT
;; ============================================================
(define (run-rlm P)
  (begin
    (init-rlm P)
    (let ((res (rlm-loop)))
      (begin
        (rlm-set __lesson (gen-lesson))
        (write-trace)
        res))))
