(define *pass* 0)
(define *fail* 0)

(define (test expected expr)
  (if (equal? expected expr)
    (set! *pass* (+ *pass* 1))
    (begin (set! *fail* (+ *fail* 1)) (print "FAIL: expected ") (print expected) (print " got ") (println expr))))

(let ()
  (define x 28)
  (test 28 x))
(test 'a (quote a))
(test '(+ 1 2) (quote (+ 1 2)))
(test 'a 'a)
(test '() '())
(test '(+ 1 2) '(+ 1 2))
(test '(quote a) '(quote a))
(test '(quote a) ''a)
(test "abc" '"abc")
(test "abc" "abc")
(test 145932 '145932)
(test 145932 145932)
(test true 'true)
(test true true)
(test 7 (+ 3 4))
(test 12 ((if false + *) 3 4))
(test 8 ((lambda (x) (+ x x)) 4))
(define reverse-subtract
  (lambda (x y) (- y x)))
(test 3 (reverse-subtract 7 10))
(define add4
  (let ((x 4))
    (lambda (y) (+ x y))))
(test 10 (add4 6))
(test '(3 4 5 6) ((lambda x x) 3 4 5 6))
(test '(5 6) ((lambda (x y . z) z)
 3 4 5 6))
(test 'yes (if (> 3 2) 'yes 'no))
(test 'no (if (> 2 3) 'yes 'no))
(test 1 (if (> 3 2)
    (- 3 2)
    (+ 3 2)))
(let ()
  (define x 2)
  (test 3 (+ x 1)))
(test 'greater
    (cond ((> 3 2) 'greater)
          ((< 3 2) 'less)))
(test 'equal
    (cond ((> 3 3) 'greater)
          ((< 3 3) 'less)
          (else 'equal)))
(test 2
    (cond ((assv 'b '((a 1) (b 2))) => cadr)
          (else false)))
(test 'composite
    (case (* 2 3)
      ((2 3 5 7) 'prime)
      ((1 4 6 8 9) 'composite)))
(test 'c
    (case (car '(c d))
      ((a e i o u) 'vowel)
      ((w y) 'semivowel)
      (else => (lambda (x) x))))
(test '((other . z) (semivowel . y) (other . x)
        (semivowel . w) (vowel . u))
    (map (lambda (x)
           (case x
             ((a e i o u) => (lambda (w) (cons 'vowel w)))
             ((w y) (cons 'semivowel x))
             (else => (lambda (w) (cons 'other w)))))
         '(z y x w u)))
(test true (and (= 2 2) (> 2 1)))
(test false (and (= 2 2) (< 2 1)))
(test '(f g) (and 1 2 'c '(f g)))
(test true (and))
(test true (or (= 2 2) (> 2 1)))
(test true (or (= 2 2) (< 2 1)))
(test false (or false false false))
(test '(b c) (or (memq 'b '(a b c))
    (/ 3 0)))
(test 6 (let ((x 2) (y 3))
  (* x y)))
(test 35 (let ((x 2) (y 3))
  (let ((x 7)
        (z (+ x y)))
    (* z x))))
(test 70 (let ((x 2) (y 3))
  (let* ((x 7)
         (z (+ x y)))
    (* z x))))
(test true
    (letrec ((even?
              (lambda (n)
                (if (zero? n)
                    true
                    (odd? (- n 1)))))
             (odd?
              (lambda (n)
                (if (zero? n)
                    false
                    (even? (- n 1))))))
      (even? 88)))
(test 5
    (letrec* ((p
               (lambda (x)
                 (+ 1 (q (- x 1)))))
              (q
               (lambda (y)
                 (if (zero? y)
                     0
                     (+ 1 (p (- y 1))))))
              (x (p 5))
              (y x))
             y))
(define (means ton)
  (letrec*
     ((mean
        (lambda (f g)
          (f (/ (sum g ton) n))))
      (sum
        (lambda (g ton)
          (if (null? ton)
            (+)
            (if (number? ton)
                (g ton)
                (+ (sum g (car ton))
                   (sum g (cdr ton)))))))
      (n (sum (lambda (x) 1) ton)))
    (values (mean values values)
            (mean exp log)
            (mean / /))))
(test 'ok (let-values () 'ok))
(let ()
  (define x 0)
  (set! x 5)
  (test 6 (+ x 1)))
(test 25 (let ((x '(1 3 5 7 9)))
  (do ((x x (cdr x))
       (sum 0 (+ sum (car x))))
      ((null? x) sum))))
(test '((6 1 3) (-5 -2))
    (let loop ((numbers '(3 -2 1 6 -5))
               (nonneg '())
               (neg '()))
      (cond ((null? numbers) (list nonneg neg))
            ((>= (car numbers) 0)
             (loop (cdr numbers)
                   (cons (car numbers) nonneg)
                   neg))
            ((< (car numbers) 0)
             (loop (cdr numbers)
                   nonneg
                   (cons (car numbers) neg))))))
(test 3 (force (delay (+ 1 2))))
(test '(3 3)  
    (let ((p (delay (+ 1 2))))
      (list (force p) (force p))))
(define head
  (lambda (stream) (car (force stream))))
(define tail
  (lambda (stream) (cdr (force stream))))
(test 2 (head (tail (tail integers))))
(define (stream-filter p? s)
  (delay-force
   (if (null? (force s)) 
       (delay '())
       (let ((h (car (force s)))
             (t (cdr (force s))))
         (if (p? h)
             (delay (cons h (stream-filter p? t)))
             (stream-filter p? t))))))
(test 5 (head (tail (tail (stream-filter odd? integers)))))
(let ()
  (define x 5)
  (define count 0)
  (define p
    (delay (begin (set! count (+ count 1))
                  (if (> count x)
                      count
                      (force p)))))
  (test 6 (force p))
  (test 6 (begin (set! x 10) (force p))))
(test true (promise? (delay (+ 2 2))))
(test true (promise? (make-promise (+ 2 2))))
(test true
    (let ((x (delay (+ 2 2))))
      (force x)
      (promise? x)))
(test true
    (let ((x (make-promise (+ 2 2))))
      (force x)
      (promise? x)))
(test 4 (force (make-promise (+ 2 2))))
(test 4 (force (make-promise (make-promise (+ 2 2)))))
(define radix
  (make-parameter
   10
   (lambda (x)
     (if (and (integer? x) (<= 2 x 16))
         x
         (error "invalid radix")))))
(define (f n) (number->string n (radix)))
(test "12" (f 12))
(test "1100" (parameterize ((radix 2))
  (f 12)))
(test "12" (f 12))
(test '(list 3 4) `(list ,(+ 1 2) 4))
(let ((name 'a)) (test '(list a (quote a)) `(list ,name ',name)))
(test '(a 3 4 5 6 b) `(a ,(+ 1 2) ,@(map abs '(4 -5 6)) b))
(test '(a `(b ,(+ 1 2) ,(foo 4 d) e) f)
    `(a `(b ,(+ 1 2) ,(foo ,(+ 1 3) d) e) f) )
(let ((name1 'x)
      (name2 'y))
   (test '(a `(b ,x ,'y d) e) `(a `(b ,,name1 ,',name2 d) e)))
(test '(list 3 4) (quasiquote (list (unquote (+ 1 2)) 4)) )
(test `(list ,(+ 1 2) 4) (quasiquote (list (unquote (+ 1 2)) 4)))
(define any-arity
  (case-lambda 
    (() 'zero)
    ((x) x)
    ((x y) (cons x y))
    ((x y z) (list x y z))
    (args (cons 'many args))))
(test 'zero (any-arity))
(test 1 (any-arity 1))
(test '(1 . 2) (any-arity 1 2))
(test '(1 2 3) (any-arity 1 2 3))
(test '(many 1 2 3 4) (any-arity 1 2 3 4))
(define rest-arity
  (case-lambda 
    (() '(zero))
    ((x) (list 'one x))
    ((x y) (list 'two x y))
    ((x y . z) (list 'more x y z))))
(test '(zero) (rest-arity))
(test '(one 1) (rest-arity 1))
(test '(two 1 2) (rest-arity 1 2))
(test '(more 1 2 (3)) (rest-arity 1 2 3))
(define dead-clause
  (case-lambda
    ((x . y) 'many)
    (() 'none)
    (foo 'unreachable)))
(test 'none (dead-clause))
(test 'many (dead-clause 1))
(test 'many (dead-clause 1 2))
(test 'many (dead-clause 1 2 3))
(be-like-begin1 sequence1)
(test 3 (sequence1 0 1 2 3))
(be-like-begin2 sequence2)
(test 4 (sequence2 1 2 3 4))
(be-like-begin3 sequence3)
(test 5 (sequence3 2 3 4 5))
(test '... (elli-esc-1))
(test '(100 ...) (elli-esc-1 100))
(test '(... 100 200) (elli-esc-1 100 200))
(test '_ (underscore foo))
(test '(2 0 many)
    (list (count-to-2 a b) (count-to-2) (count-to-2 a b c d)))
(test '(2 0 fail fail)
    (list (count-to-2_ _ _) (count-to-2_)
          (count-to-2_ a b) (count-to-2_ a b c d)))
(jabberwocky mad-hatter)
(test 42 (mad-hatter))
(test 'ok (let ((=> false)) (cond (true => 'ok))))
(define add3
  (lambda (x) (+ x 3)))
(test 6 (add3 3))
(define first car)
(test 1 (first '(1 2)))
(test 45 (let ((x 5))
  (define foo (lambda (y) (bar x y)))
  (define bar (lambda (a b) (+ (* a b) a)))
  (foo (+ x 3))))
(test 'ok
    (let ()
      (define-values () (values))
      'ok))
(test 1
    (let ()
      (define-values (x) (values 1))
      x))
(test 3
    (let ()
      (define-values x (values 1 2))
      (apply + x)))
(test 3
    (let ()
      (define-values (x y) (values 1 2))
      (+ x y)))
(test 6
    (let ()
      (define-values (x y z) (values 1 2 3))
      (+ x y z)))
(test 10
    (let ()
      (define-values (x y . z) (values 1 2 3 4))
      (+ x y (car z) (cadr z))))
(define-record-type <pare>
  (kons x y)
  pare?
  (x kar set-kar!)
  (y kdr))
(test true (pare? (kons 1 2)))
(test false (pare? (cons 1 2)))
(test 1 (kar (kons 1 2)))
(test 2 (kdr (kons 1 2)))
(test 3 (let ((k (kons 1 2)))
          (set-kar! k 3)
          (kar k)))
(test true (eqv? 'a 'a))
(test false (eqv? 'a 'b))
(test true (eqv? 2 2))
(test true (eqv? '() '()))
(test true (eqv? 100000000 100000000))
(test false (eqv? (cons 1 2) (cons 1 2)))
(test false (eqv? (lambda () 1)
               (lambda () 2)))
(test false (eqv? false 'nil))
(define gen-counter
  (lambda ()
    (let ((n 0))
      (lambda () (set! n (+ n 1)) n))))
(test true
    (let ((g (gen-counter)))
      (eqv? g g)))
(test false (eqv? (gen-counter) (gen-counter)))
(define gen-loser
  (lambda ()
    (let ((n 0))
      (lambda () (set! n (+ n 1)) 27))))
(test true (let ((g (gen-loser)))
  (eqv? g g)))
(test false
(letrec ((f (lambda () (if (eqv? f g) 'f 'both)))
         (g (lambda () (if (eqv? f g) 'g 'both))))
   (eqv? f g)))
(test true
    (let ((x '(a)))
      (eqv? x x)))
(test true (eq? 'a 'a))
(test false (eq? (list 'a) (list 'a)))
(test true (eq? '() '()))
(test true
    (let ((x '(a)))
      (eq? x x)))
(test true
    (let ((p (lambda (x) x)))
      (eq? p p)))
(test true (equal? 'a 'a))
(test true (equal? '(a) '(a)))
(test true (equal? '(a (b) c)
                 '(a (b) c)))
(test true (equal? "abc" "abc"))
(test true (equal? 2 2))
(test true (equal? (make-vector 5 'a)
                 (make-vector 5 'a)))
(test true (complex? 3+4i))
(test true (complex? 3))
(test true (real? 3))
(test true (real? -2.5+0i))
(test false (real? -2.5+0.0i))
(test true (real? #e1e10))
(test true (real? +inf.0))
(test false (rational? -inf.0))
(test false (rational? +nan.0))
(test true (rational? 9007199254740991.0))
(test true (rational? 9007199254740992.0))
(test true (rational? 1.7976931348623157e308))
(test true (rational? 6/10))
(test true (rational? 6/3))
(test true (integer? 3+0i))
(test true (integer? 3.0))
(test true (integer? 8/4))
(test false (exact? 3.0))
(test true (exact? #e3.0))
(test true (inexact? 3.))
(test true (exact-integer? 32))
(test false (exact-integer? 32.0))
(test false (exact-integer? 32/5))
(test true (finite? 3))
(test false (finite? +inf.0))
(test false (finite? 3.0+inf.0i))
(test false (infinite? 3))
(test true (infinite? +inf.0))
(test false (infinite? +nan.0))
(test true (infinite? 3.0+inf.0i))
(test true (nan? +nan.0))
(test false (nan? 32))
(test false (nan? 1+2i))
(test true (= 1 1.0 1.0+0.0i))
(test false (= 1.0 1.0+1.0i))
(test true (< 1 2 3))
(test false (< 1 1 2))
(test true (> 3.0 2.0 1.0))
(test false (> -3.0 2.0 1.0))
(test true (<= 1 1 2))
(test false (<= 1 2 1))
(test true (>= 2 1 1))
(test false (>= 1 2 1))
(test false (< +nan.0 0))
(test false (> +nan.0 0))
(test false (< +nan.0 0.0))
(test false (> +nan.0 0.0))
(test '(true false) (list (<= 1 1 2) (<= 2 1 3)))
(test false (= 9007199254740992.0 9007199254740993))
(define single-float-epsilon
  (do ((eps 1.0 (* eps 2.0)))
      ((= eps (+ eps 1.0)) eps)))
(let* ((a (/ 10.0 single-float-epsilon))
       (j (exact a)))
  (test true (if (and (<= a j) (< j (+ j 1)))
               (not (<= (+ j 1) a))
               true)))
(test true (zero? 0))
(test true (zero? 0.0))
(test true (zero? 0.0+0.0i))
(test false (zero? 1))
(test false (zero? -1))
(test false (positive? 0))
(test false (positive? 0.0))
(test true (positive? 1))
(test true (positive? 1.0))
(test false (positive? -1))
(test false (positive? -1.0))
(test true (positive? +inf.0))
(test false (positive? -inf.0))
(test false (positive? +nan.0))
(test false (negative? 0))
(test false (negative? 0.0))
(test false (negative? 1))
(test false (negative? 1.0))
(test true (negative? -1))
(test true (negative? -1.0))
(test false (negative? +inf.0))
(test true (negative? -inf.0))
(test false (negative? +nan.0))
(test false (odd? 0))
(test true (odd? 1))
(test true (odd? -1))
(test false (odd? 102))
(test true (even? 0))
(test false (even? 1))
(test true (even? -2))
(test true (even? 102))
(test 3 (max 3))
(test 4 (max 3 4))
(test 4.0 (max 3.9 4))
(test 5.0 (max 5 3.9 4))
(test +inf.0 (max 100 +inf.0))
(test 3 (min 3))
(test 3 (min 3 4))
(test 3.0 (min 3 3.1))
(test -inf.0 (min -inf.0 -100))
(test 7 (+ 3 4))
(test 3 (+ 3))
(test 0 (+))
(test 4 (* 4))
(test 1 (*))
(test -1 (- 3 4))
(test -6 (- 3 4 5))
(test -3 (- 3))
(test -3/2 (- 3/2))
(test -3/2-i (- 3/2+i))
(test 3/20 (/ 3 4 5))
(test 1/3 (/ 3))
(test 1073741824 (/ -1073741824 -1))
(test 1073741824 (quotient -1073741824 -1))
(test 0 (remainder -1073741824 -1))
(test 4611686018427387904 (/ -4611686018427387904 -1))
(test 4611686018427387904 (quotient -4611686018427387904 -1))
(test 0 (remainder -4611686018427387904 -1))
(test 7 (abs -7))
(test 7 (abs 7))
(test-values (values 2 1) (floor/ 5 2))
(test-values (values -3 1) (floor/ -5 2))
(test-values (values -3 -1) (floor/ 5 -2))
(test-values (values 2 -1) (floor/ -5 -2))
(test-values (values 2 1) (truncate/ 5 2))
(test-values (values -2 -1) (truncate/ -5 2))
(test-values (values -2 1) (truncate/ 5 -2))
(test-values (values 2 -1) (truncate/ -5 -2))
(test-values (values 2.0 -1.0) (truncate/ -5.0 -2))
(test 1 (modulo 13 4))
(test 1 (remainder 13 4))
(test 3 (modulo -13 4))
(test -1 (remainder -13 4))
(test -3 (modulo 13 -4))
(test 1 (remainder 13 -4))
(test -1 (modulo -13 -4))
(test -1 (remainder -13 -4))
(test -1.0 (remainder -13 -4.0))
(test 4 (gcd 32 -36))
(test 0 (gcd))
(test 288 (lcm 32 -36))
(test 288.0 (lcm 32.0 -36))
(test 1 (lcm))
(test 3 (numerator (/ 6 4)))
(test 2 (denominator (/ 6 4)))
(test 11.0 (numerator 5.5))
(test 2.0 (denominator 5.5))
(test 5.0 (numerator 5.0))
(test 1.0 (denominator 5.0))
(test -5.0 (floor -4.3))
(test -4.0 (ceiling -4.3))
(test -4.0 (truncate -4.3))
(test -4.0 (round -4.3))
(test 3.0 (floor 3.5))
(test 4.0 (ceiling 3.5))
(test 3.0 (truncate 3.5))
(test 4.0 (round 3.5))
(test 4 (round 7/2))
(test 7 (round 7))
(test 1 (round 7/10))
(test -4 (round -7/2))
(test -7 (round -7))
(test -1 (round -7/10))
(test 1/3 (rationalize (exact .3) 1/10))
(test #i1/3 (rationalize .3 1/10))
(test 20.0855369231877 (exp 3))
(test 1.0 (log (exp 1)))
(test 42.0 (log (exp 42)))
(test 2.0 (log 100 10))
(test 12.0 (log 4096 2))
(test 1.0 (sin 1.5707963267949))
(test -1.0 (cos 3.14159265358979))
(test 1.5574077246549 (tan 1))
(test 1.5707963267949 (asin 1))
(test 3.14159265358979 (acos -1))
(test 0.0 (atan 0.0 1.0))
(test -0.0 (atan -0.0 1.0))
(test 0.785398163397448 (atan 1.0 1.0))
(test 1.5707963267949 (atan 1.0 0.0))
(test 2.35619449019234 (atan 1.0 -1.0))
(test 3.14159265358979 (atan 0.0 -1.0))
(test -3.14159265358979 (atan -0.0 -1.0))
(test -2.35619449019234 (atan -1.0 -1.0))
(test -1.5707963267949 (atan -1.0 0.0))
(test -0.785398163397448 (atan -1.0 1.0))
(test 1764 (square 42))
(test 4 (square 2))
(test 1.4142135623731 (sqrt 2))
(test 0.0+1.0i (sqrt -1.0-0.0i))
(test '(2 0) (call-with-values (lambda () (exact-integer-sqrt 4)) list))
(test '(2 1) (call-with-values (lambda () (exact-integer-sqrt 5)) list))
(test 27 (expt 3 3))
(test 1 (expt 0 0))
(test 0 (expt 0 1))
(test 1.0 (expt 0.0 0))
(test 0.0 (expt 0 1.0))
(test 1+2i (make-rectangular 1 2))
(test 0.54030230586814+0.841470984807897i (make-polar 1 1))
(test 1 (real-part 1+2i))
(test 2 (imag-part 1+2i))
(test 2.23606797749979 (magnitude 1+2i))
(test 1.10714871779409 (angle 1+2i))
(test 1 (exact 1.0))
(test true (exact? (exact 1.0)))
(test 100 (string->number "100"))
(test 256 (string->number "100" 16))
(test 100.0 (string->number "1e2"))
(test false (string->number "1 2"))
(test true true)
(test false false)
(test false 'false)
(test false (not true))
(test false (not 3))
(test false (not (list 3)))
(test true (not false))
(test false (not '()))
(test false (not (list)))
(test false (not 'nil))
(test true (boolean? false))
(test false (boolean? 0))
(test false (boolean? '()))
(test true (boolean=? true true))
(test true (boolean=? false false))
(test false (boolean=? true false))
(test true (boolean=? false false false))
(test false (boolean=? true true false))
(let* ((x (list 'a 'b 'c))
       (y x))
  (test '(a b c) (values y))
  (test true (list? y))
  (set-cdr! x 4)
  (test '(a . 4) (values x))
  (test true (eqv? x y))
  (test false (list? y))
  (set-cdr! x x)
  (test false (list? x)))
(test true (pair? '(a . b)))
(test true (pair? '(a b c)))
(test false (pair? '()))
(test '(a) (cons 'a '()))
(test '((a) b c d) (cons '(a) '(b c d)))
(test '("a" b c) (cons "a" '(b c)))
(test '(a . 3) (cons 'a 3))
(test '((a b) . c) (cons '(a b) 'c))
(test 'a (car '(a b c)))
(test '(a) (car '((a) b c d)))
(test 1 (car '(1 . 2)))
(test '(b c d) (cdr '((a) b c d)))
(test 2 (cdr '(1 . 2)))
(define (g) '(constant-list))
(test true (list? '(a b c)))
(test true (list? '()))
(test false (list? '(a . b)))
(test false (let ((x (list 'a))) (set-cdr! x x) (list? x)))
(test '(3 3) (make-list 2 3))
(test '(a 7 c) (list 'a (+ 3 4) 'c))
(test '() (list))
(test 3 (length '(a b c)))
(test 3 (length '(a (b) (c d e))))
(test 0 (length '()))
(test '(x y) (append '(x) '(y)))
(test '(a b c d) (append '(a) '(b c d)))
(test '(a (b) (c)) (append '(a (b)) '((c))))
(test '(a b c . d) (append '(a b) '(c . d)))
(test 'a (append '() 'a))
(test '(c b a) (reverse '(a b c)))
(test '((e (f)) d (b c) a) (reverse '(a (b c) d (e (f)))))
(test '(d e) (list-tail '(a b c d e) 3))
(test 'c (list-ref '(a b c d) 2))
(test 'c (list-ref '(a b c d)
          (exact (round 1.8))))
(test '(0 ("Sue" "Sue") "Anna")
    (let ((lst (list 0 '(2 2 2 2) "Anna")))
      (list-set! lst 1 '("Sue" "Sue"))
      lst))
(test '(a b c) (memq 'a '(a b c)))
(test '(b c) (memq 'b '(a b c)))
(test false (memq 'a '(b c d)))
(test false (memq (list 'a) '(b (a) c)))
(test '((a) c) (member (list 'a) '(b (a) c)))
(test '("b" "c") (member "B" '("a" "b" "c") string-ci=?))
(test '(101 102) (memv 101 '(100 101 102)))
(let ()
  (define e '((a 1) (b 2) (c 3)))
  (test '(a 1) (assq 'a e))
  (test '(b 2) (assq 'b e))
  (test false (assq 'd e)))
(test false (assq (list 'a) '(((a)) ((b)) ((c)))))
(test '((a)) (assoc (list 'a) '(((a)) ((b)) ((c)))))
(test '(2 4) (assoc 2.0 '((1 1) (2 4) (3 9)) =))
(test '(5 7) (assv 5 '((2 3) (5 7) (11 13))))
(test '(1 2 3) (list-copy '(1 2 3)))
(test "foo" (list-copy "foo"))
(test '() (list-copy '()))
(test '(3 . 4) (list-copy '(3 . 4)))
(test '(6 7 8 . 9) (list-copy '(6 7 8 . 9)))
(let* ((l1 '((a b) (c d) e))
       (l2 (list-copy l1)))
  (test l2 '((a b) (c d) e))
  (test true (eq? (car l1) (car l2)))
  (test true (eq? (cadr l1) (cadr l2)))
  (test false (eq? (cdr l1) (cdr l2)))
  (test false (eq? (cddr l1) (cddr l2))))
(test true (symbol? 'foo))
(test true (symbol? (car '(a b))))
(test false (symbol? "bar"))
(test true (symbol? 'nil))
(test false (symbol? '()))
(test false (symbol? false))
(test true (symbol=? 'a 'a))
(test false (symbol=? 'a 'A))
(test true (symbol=? 'a 'a 'a))
(test false (symbol=? 'a 'a 'A))
(test "flying-fish"     
(symbol->string 'flying-fish))
(test "Martin" (symbol->string 'Martin))
(test "Malvina" (symbol->string (string->symbol "Malvina")))
(test 'mISSISSIppi (string->symbol "mISSISSIppi"))
(test true (eq? 'bitBlt (string->symbol "bitBlt")))
(test true (eq? 'LollyPop (string->symbol (symbol->string 'LollyPop))))
(test true (string=? "K. Harper, M.D."
                   (symbol->string (string->symbol "K. Harper, M.D."))))
(test true (char? #\a))
(test false (char? "a"))
(test false (char? 'a))
(test false (char? 0))
(test true (char=? #\a #\a #\a))
(test false (char=? #\a #\A))
(test true (char<? #\a #\b #\c))
(test false (char<? #\a #\a))
(test false (char<? #\b #\a))
(test false (char>? #\a #\b))
(test false (char>? #\a #\a))
(test true (char>? #\c #\b #\a))
(test true (char<=? #\a #\b #\b))
(test true (char<=? #\a #\a))
(test false (char<=? #\b #\a))
(test false (char>=? #\a #\b))
(test true (char>=? #\a #\a))
(test true (char>=? #\b #\b #\a))
(test true (char-ci=? #\a #\a))
(test true (char-ci=? #\a #\A #\a))
(test false (char-ci=? #\a #\b))
(test true (char-ci<? #\a #\B #\c))
(test false (char-ci<? #\A #\a))
(test false (char-ci<? #\b #\A))
(test false (char-ci>? #\A #\b))
(test false (char-ci>? #\a #\A))
(test true (char-ci>? #\c #\B #\a))
(test true (char-ci<=? #\a #\B #\b))
(test true (char-ci<=? #\A #\a))
(test false (char-ci<=? #\b #\A))
(test false (char-ci>=? #\A #\b))
(test true (char-ci>=? #\a #\A))
(test true (char-ci>=? #\b #\B #\a))
(test true (char-alphabetic? #\a))
(test false (char-alphabetic? #\space))
(test true (char-numeric? #\0))
(test false (char-numeric? #\.))
(test false (char-numeric? #\a))
(test true (char-whitespace? #\space))
(test true (char-whitespace? #\tab))
(test true (char-whitespace? #\newline))
(test false (char-whitespace? #\_))
(test false (char-whitespace? #\a))
(test true (char-upper-case? #\A))
(test false (char-upper-case? #\a))
(test false (char-upper-case? #\3))
(test true (char-lower-case? #\a))
(test false (char-lower-case? #\A))
(test false (char-lower-case? #\3))
(test true (char-alphabetic? #\Λ))
(test false (char-alphabetic? #\x0E50))
(test true (char-upper-case? #\Λ))
(test false (char-upper-case? #\λ))
(test false (char-lower-case? #\Λ))
(test true (char-lower-case? #\λ))
(test false (char-numeric? #\Λ))
(test true (char-numeric? #\x0E50))
(test true (char-whitespace? #\x1680))
(test 0 (digit-value #\0))
(test 3 (digit-value #\3))
(test 9 (digit-value #\9))
(test 4 (digit-value #\x0664))
(test 0 (digit-value #\x0AE6))
(test false (digit-value #\.))
(test false (digit-value #\-))
(test 97 (char->integer #\a))
(test #\a (integer->char 97))
(test #\A (char-upcase #\a))
(test #\A (char-upcase #\A))
(test #\a (char-downcase #\a))
(test #\a (char-downcase #\A))
(test #\a (char-foldcase #\a))
(test #\a (char-foldcase #\A))
(test #\Λ (char-upcase #\λ))
(test #\Λ (char-upcase #\Λ))
(test #\λ (char-downcase #\λ))
(test #\λ (char-downcase #\Λ))
(test #\λ (char-foldcase #\λ))
(test #\λ (char-foldcase #\Λ))
(test true (string? ""))
(test true (string? " "))
(test false (string? 'a))
(test false (string? #\a))
(test 3 (string-length (make-string 3)))
(test "---" (make-string 3 #\-))
(test "" (string))
(test "---" (string #\- #\- #\-))
(test "kitten" (string #\k #\i #\t #\t #\e #\n))
(test 0 (string-length ""))
(test 1 (string-length "a"))
(test 3 (string-length "abc"))
(test #\a (string-ref "abc" 0))
(test #\b (string-ref "abc" 1))
(test #\c (string-ref "abc" 2))
(test "a-c" (let ((str (string #\a #\b #\c))) (string-set! str 1 #\-) str))
(test (string #\a #\x1F700 #\c)
    (let ((s (string #\a #\b #\c)))
      (string-set! s 1 #\x1F700)
      s))
(test true (string=? "" ""))
(test true (string=? "abc" "abc" "abc"))
(test false (string=? "" "abc"))
(test false (string=? "abc" "aBc"))
(test false (string<? "" ""))
(test false (string<? "abc" "abc"))
(test true (string<? "abc" "abcd" "acd"))
(test false (string<? "abcd" "abc"))
(test true (string<? "abc" "bbc"))
(test false (string>? "" ""))
(test false (string>? "abc" "abc"))
(test false (string>? "abc" "abcd"))
(test true (string>? "acd" "abcd" "abc"))
(test false (string>? "abc" "bbc"))
(test true (string<=? "" ""))
(test true (string<=? "abc" "abc"))
(test true (string<=? "abc" "abcd" "abcd"))
(test false (string<=? "abcd" "abc"))
(test true (string<=? "abc" "bbc"))
(test true (string>=? "" ""))
(test true (string>=? "abc" "abc"))
(test false (string>=? "abc" "abcd"))
(test true (string>=? "abcd" "abcd" "abc"))
(test false (string>=? "abc" "bbc"))
(test true (string-ci=? "" ""))
(test true (string-ci=? "abc" "abc"))
(test false (string-ci=? "" "abc"))
(test true (string-ci=? "abc" "aBc"))
(test false (string-ci=? "abc" "aBcD"))
(test false (string-ci<? "abc" "aBc"))
(test true (string-ci<? "abc" "aBcD"))
(test false (string-ci<? "ABCd" "aBc"))
(test false (string-ci>? "abc" "aBc"))
(test false (string-ci>? "abc" "aBcD"))
(test true (string-ci>? "ABCd" "aBc"))
(test true (string-ci<=? "abc" "aBc"))
(test true (string-ci<=? "abc" "aBcD"))
(test false (string-ci<=? "ABCd" "aBc"))
(test true (string-ci>=? "abc" "aBc"))
(test false (string-ci>=? "abc" "aBcD"))
(test true (string-ci>=? "ABCd" "aBc"))
(test true (string-ci=? "ΑΒΓ" "αβγ" "αβγ"))
(test false (string-ci<? "ΑΒΓ" "αβγ"))
(test false (string-ci>? "ΑΒΓ" "αβγ"))
(test true (string-ci<=? "ΑΒΓ" "αβγ"))
(test true (string-ci>=? "ΑΒΓ" "αβγ"))
(test "ABC" (string-upcase "abc"))
(test "ABC" (string-upcase "ABC"))
(test "abc" (string-downcase "abc"))
(test "abc" (string-downcase "ABC"))
(test "abc" (string-foldcase "abc"))
(test "abc" (string-foldcase "ABC"))
(test "ΑΒΓ" (string-upcase "αβγ"))
(test "ΑΒΓ" (string-upcase "ΑΒΓ"))
(test "αβγ" (string-downcase "αβγ"))
(test "αβγ" (string-downcase "ΑΒΓ"))
(test "αβγ" (string-foldcase "αβγ"))
(test "αβγ" (string-foldcase "ΑΒΓ"))
(test "SSA" (string-upcase "ßa"))
(test "ßa" (string-downcase "ßa"))
(test "ssa" (string-downcase "SSA"))
(test "maß" (string-downcase "Maß"))
(test "mass" (string-foldcase "Maß"))
(test "İ" (string-upcase "İ"))


(print "
=== R7RS Conformance ===")
(print "Pass: ") (println *pass*)
(print "Fail: ") (println *fail*)
(print "Total tested: ") (println (+ *pass* *fail*))
