;; GENERATED by scripts/rlm-qlearn.py — do not hand-edit.
;; Learned escalation policy (tabular Q). Unseen states fall
;; back to 'ladder (the hand-coded bootstrap composite).
(define Q-ENABLED true)
(define Q-EPS 10)
(define Q-TABLE (list
  (list "ok||rc0|es0|i1" (list (list 'none 0.0) (list 'temp08 0.0) (list 'temp10 0.0) (list 'doc 0.0) (list 'hint 0.0) (list 'ban 0.0) (list 'budget2 0.0) (list 'stop 0.0) (list 'ladder 0.0)))
  (list "argtype| ~~QT~~fold-right|rc0|es1|i1" (list (list 'none 0.0) (list 'temp08 0.0) (list 'temp10 0.0) (list 'doc 0.0) (list 'hint 0.0) (list 'ban 0.0) (list 'budget2 0.0) (list 'stop 0.0) (list 'ladder -0.0125)))
  (list "argtype| ~~QT~~fold-right|rc1|es2|i2" (list (list 'none 0.0) (list 'temp08 0.0) (list 'temp10 0.0) (list 'doc 0.0) (list 'hint 0.0) (list 'ban 0.0) (list 'budget2 0.0) (list 'stop 0.0) (list 'ladder -0.0125)))
  (list "argtype| ~~QT~~fold-right|rc2|es3|i2" (list (list 'none 0.0) (list 'temp08 0.0) (list 'temp10 0.0) (list 'doc 0.0) (list 'hint 0.0) (list 'ban 0.0) (list 'budget2 0.0) (list 'stop 0.0) (list 'ladder 0.0)))
  (list "ok||rc0|es0|i3" (list (list 'none 0.0) (list 'temp08 0.0) (list 'temp10 0.0) (list 'doc 0.0) (list 'hint 0.0) (list 'ban 0.0) (list 'budget2 0.0) (list 'stop 0.0) (list 'ladder -0.0125)))
  (list "ok||rc1|es0|i3" (list (list 'none 0.0) (list 'temp08 0.0) (list 'temp10 0.0) (list 'doc 0.0) (list 'hint 0.0) (list 'ban 0.0) (list 'budget2 0.0) (list 'stop 0.0) (list 'ladder -0.0125)))
  (list "ok||rc2|es0|i3" (list (list 'none 0.0) (list 'temp08 0.0) (list 'temp10 0.0) (list 'doc 0.0) (list 'hint 0.0) (list 'ban 0.0) (list 'budget2 0.0) (list 'stop 0.0) (list 'ladder -0.0625)))
))
