;; RLM lending curriculum — stage 4: portfolio LTV in bps
;; Open-goal ladder step (2026-09-30): pure-function DeFi math, no storage.
(load-file "rlm_runtime.lisp")
(load-file "scripts/rlm-tasks/policy.lisp")
(load-file "scripts/rlm-tasks/q-table.lisp")
(load-file "scripts/rlm-tasks/custom-actions.lisp")
(rlm-set __policy POLICY_ID)
(rlm-set __trace_id "t_lend_ltv")
(define (llm-code ctx)
  (llm (build-prompt ctx)))
(define (task-verify a) (equal? a 4000))
(run-rlm "A portfolio has two assets: 30 units at price 50, and 10 units at price 200 (total value 3500). Total borrowed = 1400. Compute loan-to-value in basis points = borrowed*10000/total_value with truncating integer division (equals 4000). Store the integer as answer. When achieved, evaluate (final true).")
(retry-with-feedback task-verify "4000" 2)
(if (task-verify (rlm-get answer)) nil (re-lesson))
(write-trace)
(println (str-concat "RLMDUMP task=t_lend_ltv"))
(println (str-concat "RLMDUMP iterations=" (to-string (rlm-get iteration))))
(println (str-concat "RLMDUMP answer=" (to-string (rlm-get answer))))
(println (str-concat "RLMDUMP Final=" (to-string (rlm-get Final))))
