;; RLM lending curriculum — stage 5: risk tier classification
;; Open-goal ladder step (2026-09-30): pure-function DeFi math, no storage.
(load-file "rlm_runtime.lisp")
(load-file "scripts/rlm-tasks/policy.lisp")
(load-file "scripts/rlm-tasks/q-table.lisp")
(load-file "scripts/rlm-tasks/custom-actions.lisp")
(rlm-set __policy POLICY_ID)
(rlm-set __trace_id "t_lend_tier")
(define (llm-code ctx)
  (llm (build-prompt ctx)))
(define (task-verify a) (equal? a "liquidate"))
(run-rlm "Classify a risk tier from a health factor given in tenths: hf=8 tenths (i.e. 0.8). Tiers: hf>=20 -> high, hf>=12 -> medium, hf>=10 -> low, below 10 -> liquidate. hf=8 classifies as liquidate. Store the string liquidate as answer. When achieved, evaluate (final true).")
(retry-with-feedback task-verify ""liquidate"" 2)
(if (task-verify (rlm-get answer)) nil (re-lesson))
(write-trace)
(println (str-concat "RLMDUMP task=t_lend_tier"))
(println (str-concat "RLMDUMP iterations=" (to-string (rlm-get iteration))))
(println (str-concat "RLMDUMP answer=" (to-string (rlm-get answer))))
(println (str-concat "RLMDUMP Final=" (to-string (rlm-get Final))))
