;; RLM lending curriculum — stage 3: simple interest accrual
;; Open-goal ladder step (2026-09-30): pure-function DeFi math, no storage.
(load-file "rlm_runtime.lisp")
(load-file "scripts/rlm-tasks/policy.lisp")
(load-file "scripts/rlm-tasks/q-table.lisp")
(load-file "scripts/rlm-tasks/custom-actions.lisp")
(rlm-set __policy POLICY_ID)
(rlm-set __trace_id "t_lend_accrue")
(define (llm-code ctx)
  (llm (build-prompt ctx)))
(define (task-verify a) (equal? a 1060))
(run-rlm "Accrue simple interest: principal=1000, rate=3 per-10000 per block, blocks=200; new principal = principal + principal*rate*blocks/10000 with truncating integer division (equals 1060). Store the integer as answer. When achieved, evaluate (final true).")
(retry-with-feedback task-verify "1060" 2)
(if (task-verify (rlm-get answer)) nil (re-lesson))
(write-trace)
(println (str-concat "RLMDUMP task=t_lend_accrue"))
(println (str-concat "RLMDUMP iterations=" (to-string (rlm-get iteration))))
(println (str-concat "RLMDUMP answer=" (to-string (rlm-get answer))))
(println (str-concat "RLMDUMP Final=" (to-string (rlm-get Final))))
