;; AUTO-GENERATED @ts twin of td_power.lisp — edit the BASE task and
;; regenerate: python3 scripts/gen-ts-twins.py  (do not hand-edit)
;; DREAMED TASK — agent-authored, probe-verified (ref solves, poison fails)
;; targets state: t4_pow@ts|runtime|run_program|rc0|es1|i1
;; dreamed 1791215161.2155239582
(load-file "rlm_runtime.lisp")
(load-file "scripts/rlm-tasks/policy.lisp")
(load-file "scripts/rlm-tasks/q-table.lisp")
(load-file "scripts/rlm-tasks/custom-actions.lisp")
(load-file "scripts/rlm-tasks/rlm_ts.lisp")
(rlm-set __policy POLICY_ID)
(rlm-set __surface "ts")
(define (llm-code ctx)
  (ts->lisp (strip-code-fences (llm (build-prompt-ts ctx)))))
(begin
  (rlm-set __trace_id "td_power@ts")
  (define (task-verify a) (= a 256))
  (run-rlm "Calculate 2 to the power of 8 using the pow function; store the result via rlm_set(\"answer\", v) then rlm_set(\"Final\", true).")
  (if (task-verify (rlm-get answer)) nil (re-lesson))
  (write-trace)
  (println (str-concat "RLMDUMP task=td_power@ts"))
  (println (str-concat "RLMDUMP iterations=" (to-string (rlm-get iteration))))
  (println (str-concat "RLMDUMP answer=" (to-string (rlm-get answer))))
  (println (str-concat "RLMDUMP Final=" (to-string (rlm-get Final))))
)
