;; DREAMED TASK — agent-authored, probe-verified (ref solves, poison fails)
;; targets state: ta_primeprod|ok||rc0|es0|i3
;; dreamed 1790528025.2910439968
(load-file "rlm_runtime.lisp")
(load-file "scripts/rlm-tasks/policy.lisp")
(load-file "scripts/rlm-tasks/q-table.lisp")
(load-file "scripts/rlm-tasks/custom-actions.lisp")
(rlm-set __policy POLICY_ID)
(define (llm-code ctx)
  (llm (build-prompt ctx)))
(begin
  (rlm-set __trace_id "td_primeproduct")
  (define (task-verify a) (= a 30))
  (run-rlm "Compute the product of the first 3 prime numbers (2, 3, 5) and store it via (rlm-set answer ...) then (rlm-set Final true).")
  (if (task-verify (rlm-get answer)) nil (re-lesson))
  (write-trace)
  (println (str-concat "RLMDUMP task=td_primeproduct"))
  (println (str-concat "RLMDUMP iterations=" (to-string (rlm-get iteration))))
  (println (str-concat "RLMDUMP answer=" (to-string (rlm-get answer))))
  (println (str-concat "RLMDUMP Final=" (to-string (rlm-get Final))))
)
