(define (default0 v) (if (= v 0) 0 v))
(define (pool-s) (near/load "p0s"))
(define (pool-a) (near/load "p0a"))
(define (pool-bs) (near/load "p0bs"))
(define (pool-ba) (near/load "p0ba"))
(define (pool-bi) (near/load "p0bi"))
(define (pool-si) (near/load "p0si"))
(define (pool-lb) (near/load "p0lb"))
(define (pool-res) (near/load "p0res"))
(define (cfg-vol) (default0 (near/load "c0vol")))
(define (cfg-cf) (default0 (near/load "c0cf")))
(define (cfg-tu) (default0 (near/load "c0tu")))
(define (cfg-r0) (default0 (near/load "c0r0")))
(define (cfg-r1) (default0 (near/load "c0r1")))
(define (cfg-r2) (default0 (near/load "c0r2")))
(define (cfg-rc) (default0 (near/load "c0rc")))

(define (health-of aid)
  (let ((c (near/kv-get "u/" aid "/c")))
    (let ((bs (near/kv-get "u/" aid "/b")))
      (let ((dc (default0 c)))
        (let ((dbs (default0 bs)))
          (if (= dbs 0) 10000
            (let ((bi (default0 (pool-bi))))
              (let ((cf (cfg-cf)))
                (let ((vol (cfg-vol)))
                  (let ((debt (/ (* dbs bi) 1000000)))
                    (if (= debt 0) 10000
                      (/ (* (* dc cf) vol) (* debt 100)))))))))))))

(define (health) (health-of (near/signer_account_id)))

(define (do-accrue)
  (let ((ba (default0 (pool-ba))))
    (let ((sa (default0 (pool-a))))
      (if (or (= sa 0) (= ba 0)) 0
        (let ((util (/ (* ba 100) sa)))
          (let ((tu (cfg-tu)))
            (let ((r0 (cfg-r0)))
              (let ((r1 (cfg-r1)))
                (let ((r2 (cfg-r2)))
                  (let ((rate (if (< util tu)
                                (+ r0 (/ (* (- r1 r0) util) tu))
                                (+ r1 (/ (* (- r2 r1) (- util tu)) (- 100 tu))))))
                    (let ((rc (cfg-rc)))
                      (let ((bh (near/block_index)))
                        (let ((lb (default0 (pool-lb))))
                          (let ((delta (- bh lb)))
                            (let ((sr (/ (* rate (- 100 rc)) 100)))
                              (let ((rd (/ (* rate delta) 10000)))
                                (let ((srd (/ (* sr delta) 10000)))
                                  (let ((intr (* ba rd)))
                                    (let ((sintr (* sa srd)))
                                      (let ((bi (default0 (pool-bi))))
                                        (let ((si (default0 (pool-si))))
                                          (begin
                                            (near/store "p0ba" (+ ba intr))
                                            (near/store "p0a" (+ sa sintr))
                                            (near/store "p0res" (+ (default0 (pool-res)) (- intr sintr)))
                                            (near/store "p0bi" (+ bi (* bi rd)))
                                            (near/store "p0si" (+ si (* si srd)))
                                            (near/store "p0lb" bh)))))))))))))))))))))))

(define (accrue)
  (let ((bh (near/block_index)))
    (let ((lb (default0 (pool-lb))))
      (if (= lb 0)
        (begin
          (near/store "p0bi" 1000000)
          (near/store "p0si" 1000000)
          (near/store "p0lb" bh))
        (if (= (- bh lb) 0) 0
          (do-accrue))))))

(define (register-asset)
  (let ((inp (near/input)))
    (let ((vol (bytes-to-u32 (str-slice inp 0 4))))
      (let ((cf (bytes-to-u32 (str-slice inp 4 8))))
        (let ((tu (bytes-to-u32 (str-slice inp 8 12))))
          (let ((r0 (bytes-to-u32 (str-slice inp 12 16))))
            (let ((r1 (bytes-to-u32 (str-slice inp 16 20))))
              (let ((r2 (bytes-to-u32 (str-slice inp 20 24))))
                (let ((rc (bytes-to-u32 (str-slice inp 24 28))))
                  (begin
                    (near/store "c0vol" vol)
                    (near/store "c0cf" cf)
                    (near/store "c0tu" tu)
                    (near/store "c0r0" r0)
                    (near/store "c0r1" r1)
                    (near/store "c0r2" r2)
                    (near/store "c0rc" rc)
                    (near/return_str "ok"))))))))))))

(define (init)
  (begin
    (near/store "p0s" 0)
    (near/store "p0a" 0)
    (near/store "p0bs" 0)
    (near/store "p0ba" 0)
    (near/store "p0bi" 1000000)
    (near/store "p0si" 1000000)
    (near/store "p0lb" (near/block_index))
    (near/store "p0res" 0)
    (near/kv "u/" (near/signer_account_id) "/s" 0)
    (near/kv "u/" (near/signer_account_id) "/c" 0)
    (near/kv "u/" (near/signer_account_id) "/b" 0)
    (near/return_str "ok")))

(define (deposit)
  (do-accrue)
  (let ((inp (near/input)))
    (let ((amt (bytes-to-u32 (str-slice inp 0 4))))
      (let ((ps (default0 (pool-s))))
        (let ((pa (default0 (pool-a))))
          (let ((si (default0 (pool-si))))
            (let ((sh (/ (* amt 1000000) (if (= si 0) 1 si))))
              (let ((cs (near/kv-get "u/" (near/signer_account_id) "/s")))
                (begin
                  (near/store "p0s" (+ ps sh))
                  (near/store "p0a" (+ pa amt))
                  (near/kv "u/" (near/signer_account_id) "/s" (+ (default0 cs) sh))
                  (near/return_str (to-string sh)))))))))))

(define (withdraw)
  (do-accrue)
  (let ((inp (near/input)))
    (let ((ws (bytes-to-u32 (str-slice inp 0 4))))
      (let ((cs (near/kv-get "u/" (near/signer_account_id) "/s")))
        (let ((cur (default0 cs)))
          (if (> ws cur)
            (near/return_str "too_much")
            (let ((si (default0 (pool-si))))
              (let ((wa (/ (* ws si) 1000000)))
                (let ((pa (default0 (pool-a))))
                  (let ((maxw (/ (* pa (- 100 (cfg-tu))) 100)))
                    (if (> wa maxw)
                      (near/return_str "min_liquidity")
                      (let ((ps (default0 (pool-s))))
                        (begin
                          (near/kv "u/" (near/signer_account_id) "/s" (- cur ws))
                          (near/store "p0s" (- ps ws))
                          (near/store "p0a" (- pa wa))
                          (near/return_str (to-string wa)))))))))))))))

(define (inc-collat)
  (do-accrue)
  (let ((inp (near/input)))
    (let ((amt (bytes-to-u32 (str-slice inp 0 4))))
      (let ((cc (near/kv-get "u/" (near/signer_account_id) "/c")))
        (begin
          (near/kv "u/" (near/signer_account_id) "/c" (+ (default0 cc) amt))
          (near/return_str "ok"))))))

(define (dec-collat)
  (do-accrue)
  (let ((inp (near/input)))
    (let ((amt (bytes-to-u32 (str-slice inp 0 4))))
      (let ((cc (near/kv-get "u/" (near/signer_account_id) "/c")))
        (let ((cur (default0 cc)))
          (if (> amt cur)
            (near/return_str "too_much")
            (begin
              (near/kv "u/" (near/signer_account_id) "/c" (- cur amt))
              (let ((h (health)))
                (if (< h 100)
                  (begin
                    (near/kv "u/" (near/signer_account_id) "/c" cur)
                    (near/return_str "unsafe"))
                  (near/return_str "ok"))))))))))

(define (borrow)
  (do-accrue)
  (let ((inp (near/input)))
    (let ((amt (bytes-to-u32 (str-slice inp 0 4))))
      (let ((bs (default0 (pool-bs))))
        (let ((ba (default0 (pool-ba))))
          (let ((ub (near/kv-get "u/" (near/signer_account_id) "/b")))
            (let ((bi (default0 (pool-bi))))
              (let ((cub (default0 ub)))
                (let ((sh (/ (* amt 1000000) (if (= bi 0) 1 bi))))
                  (begin
                    (near/kv "u/" (near/signer_account_id) "/b" (+ cub sh))
                    (near/store "p0ba" (+ ba amt))
                    (let ((h (health)))
                      (if (< h 100)
                        (begin
                          (near/kv "u/" (near/signer_account_id) "/b" cub)
                          (near/store "p0ba" ba)
                          (near/return_str "unsafe"))
                        (begin
                          (near/store "p0bs" (+ bs sh))
                          (near/return_str (to-string sh)))))))))))))))

(define (repay)
  (do-accrue)
  (let ((inp (near/input)))
    (let ((amt (bytes-to-u32 (str-slice inp 0 4))))
      (let ((bs (default0 (pool-bs))))
        (let ((ba (default0 (pool-ba))))
          (let ((bi (default0 (pool-bi))))
            (if (= ba 0)
              (near/return_str "no_debt")
              (if (> amt ba)
                (near/return_str "too_much")
                (let ((sh (/ (* amt 1000000) (if (= bi 0) 1 bi))))
                  (let ((cb (near/kv-get "u/" (near/signer_account_id) "/b")))
                    (let ((cub (default0 cb)))
                      (if (> sh cub)
                        (near/return_str "too_much")
                        (begin
                          (near/kv "u/" (near/signer_account_id) "/b" (- cub sh))
                          (near/store "p0bs" (- bs sh))
                          (near/store "p0ba" (- ba amt))
                          (near/return_str (to-string sh)))))))))))))))

(define (liquidate)
  (do-accrue)
  (let ((inp (near/input)))
    (let ((ra (bytes-to-u32 (str-slice inp 0 4))))
      (let ((ms (bytes-to-u32 (str-slice inp 4 8))))
        (let ((h (health)))
          (if (>= h 100)
            (near/return_str "healthy")
            (let ((vc (near/kv-get "u/" (near/signer_account_id) "/c")))
              (let ((vb (near/kv-get "u/" (near/signer_account_id) "/b")))
                (let ((cvc (default0 vc)))
                  (let ((cvb (default0 vb)))
                    (let ((bi (default0 (pool-bi))))
                      (let ((vd (/ (* cvb bi) 1000000)))
                        (if (= vd 0)
                          (near/return_str "no_debt")
                          (let ((ar (if (> ra vd) vd ra)))
                            (let ((dc (+ 5 (/ (* (- 100 h) 15) 100))))
                              (let ((sa (/ (* ar dc) 100)))
                                (let ((a1 (if (> sa ms) ms sa)))
                                  (let ((a2 (if (> a1 cvc) cvc a1)))
                                    (let ((bs (default0 (pool-bs))))
                                      (let ((ba (default0 (pool-ba))))
                                        (let ((sh (/ (* ar 1000000) (if (= bi 0) 1 bi))))
                                          (begin
                                            (near/kv "u/" (near/signer_account_id) "/b" (- cvb sh))
                                            (near/store "p0bs" (- bs sh))
                                            (near/store "p0ba" (- ba ar))
                                            (near/kv "u/" (near/signer_account_id) "/c" (- cvc a2))
                                            (near/return_str (to-string a2))))))))))))))))))))))))

;; View functions - accept account_id as input string
(define (get-supplied)
  (let ((aid (near/input)))
    (let ((us (near/kv-get "u/" aid "/s")))
      (let ((si (default0 (pool-si))))
        (near/return_str (to-string (/ (* (default0 us) (if (= si 0) 1 si)) 1000000)))))))

(define (get-collat)
  (let ((aid (near/input)))
    (let ((uc (near/kv-get "u/" aid "/c")))
      (near/return_str (to-string (default0 uc))))))

(define (get-borr)
  (let ((aid (near/input)))
    (let ((ub (near/kv-get "u/" aid "/b")))
      (let ((bi (default0 (pool-bi))))
        (near/return_str (to-string (/ (* (default0 ub) (if (= bi 0) 1 bi)) 1000000)))))))

(define (get-health)
  (let ((aid (near/input)))
    (near/return_str (to-string (health-of aid)))))

(define (get-pool-s) (near/return_str (to-string (default0 (pool-s)))))
(define (get-pool-a) (near/return_str (to-string (default0 (pool-a)))))
(define (get-reserve) (near/return_str (to-string (default0 (pool-res)))))
(define (get-borrow-index) (near/return_str (to-string (default0 (pool-bi)))))
(define (get-supply-index) (near/return_str (to-string (default0 (pool-si)))))

(define (get-borrow-rate)
  (let ((ba (default0 (pool-ba))))
    (let ((sa (default0 (pool-a))))
      (if (= sa 0) 0
        (let ((util (/ (* ba 100) sa)))
          (let ((tu (cfg-tu)))
            (let ((r0 (cfg-r0)))
              (let ((r1 (cfg-r1)))
                (let ((r2 (cfg-r2)))
                  (near/return_str (to-string (if (< util tu)
                    (+ r0 (/ (* (- r1 r0) util) tu))
                    (+ r1 (/ (* (- r2 r1) (- util tu)) (- 100 tu))))))))))))))

(define (get-supply-rate)
  (let ((ba (default0 (pool-ba))))
    (let ((sa (default0 (pool-a))))
      (if (= sa 0) 0
        (let ((util (/ (* ba 100) sa)))
          (let ((tu (cfg-tu)))
            (let ((r0 (cfg-r0)))
              (let ((r1 (cfg-r1)))
                (let ((r2 (cfg-r2)))
                  (let ((br (if (< util tu)
                              (+ r0 (/ (* (- r1 r0) util) tu))
                              (+ r1 (/ (* (- r2 r1) (- util tu)) (- 100 tu))))))
                    (let ((rc (cfg-rc)))
                      (near/return_str (to-string (/ (* br (- 100 rc)) 100))))))))))))))

(export "register_asset" register-asset)
(export "init" init)
(export "deposit" deposit)
(export "withdraw" withdraw)
(export "inc_collat" inc-collat)
(export "dec_collat" dec-collat)
(export "borrow" borrow)
(export "repay" repay)
(export "liquidate" liquidate)
(export "get_supplied" get-supplied)
(export "get_collat" get-collat)
(export "get_borr" get-borr)
(export "get_health" get-health)
(export "get_pool" get-pool-s)
(export "get_pool_a" get-pool-a)
(export "get_borrow_rate" get-borrow-rate)
(export "get_supply_rate" get-supply-rate)
(export "get_reserve" get-reserve)
(export "get_borrow_index" get-borrow-index)
(export "get_supply_index" get-supply-index)
