;; Live test: Show lengths only (avoid large string concat)
(define (run)
  (let* ((args-b64 "eyJhY2NvdW50X2lkIjoiOTQzYWRkYWJkZTc5MTNjNmY1ODA0M2QzNDhlYzc2MzY0MzY4OWI2OGRhMmU3YWIxODZiN2Q3NWUxZDU0NGZmMiJ9")
         (rpc-body (str-cat "{\"jsonrpc\":\"2.0\",\"id\":\"1\",\"method\":\"query\",\"params\":{\"request_type\":\"call_function\",\"finality\":\"final\",\"account_id\":\"contract.main.burrow.near\",\"method_name\":\"get_account\",\"args_base64\":\"" args-b64 "\"}}"))
         (rpc-result (http-post "https://rpc.mainnet.near.org" rpc-body))
         (raw-bytes (json-get-str "result" rpc-result))
         (decoded (json-decode-bytes raw-bytes))
         (len-rpc (str-len rpc-result))
         (len-bytes (str-len raw-bytes))
         (len-dec (str-len decoded)))
    (begin
      (print (str-cat "RPC len: " (to-string len-rpc)))
      (print (str-cat "Bytes len: " (to-string len-bytes)))
      (print (str-cat "Decoded len: " (to-string len-dec)))
      "OK")))