(define (run)
  (let* ((prices (http-get "https://api.rhea.finance/list-token-price"))
         (o1 (json-get-str "nbtc.bridge.near" prices))
         (p1 (json-get-str "price" o1))
         (o2 (json-get-str "nbtc.bridge.near" prices))
         (p2 (json-get-str "price" o2))
         (o3 (json-get-str "nbtc.bridge.near" prices))
         (p3 (json-get-str "price" o3))
         (o4 (json-get-str "nbtc.bridge.near" prices))
         (p4 (json-get-str "price" o4))
         (o5 (json-get-str "nbtc.bridge.near" prices))
         (prices2 (http-get "https://api.rhea.finance/list-token-price"))
         (p5 (json-get-str "price" o5)))
    (str-cat p1 "|" p5 "|prices:" (to-string (str-len prices)) "|prices2:" (to-string (str-len prices2)) "|o5:" (to-string (str-len o5)))))
