(define (run)
  (let* ((prices (http-get "https://api.rhea.finance/list-token-price"))
         (nbtc-p (json-get-str "price" (json-get-str "nbtc.bridge.near" prices)))
         (zec-p (json-get-str "price" (json-get-str "zec.omft.near" prices)))
         (usdt-p (json-get-str "price" (json-get-str "usdt.tether-token.near" prices)))
         (stnear-p (json-get-str "price" (json-get-str "meta-pool.near" prices)))
         (brrr-p (json-get-str "price" (json-get-str "token.burrow.near" prices)))
         (out (str-cat "A:" nbtc-p " B:" zec-p " C:" usdt-p " D:" stnear-p " E:" brrr-p)))
    out))
