(define (run)
  (let* ((prices (http-get "https://api.rhea.finance/list-token-price"))
         (objs (json-extract prices "nbtc.bridge.near" "zec.omft.near" "usdt.tether-token.near" "meta-pool.near" "token.burrow.near"))
         (p1 (json-get-str "price" (json-array-get objs 0)))
         (p2 (json-get-str "price" (json-array-get objs 1)))
         (p3 (json-get-str "price" (json-array-get objs 2)))
         (p4 (json-get-str "price" (json-array-get objs 3)))
         (p5 (json-get-str "price" (json-array-get objs 4)))
         (out (str-cat p1 "|" p2 "|" p3 "|" p4 "|" p5)))
    out))
