(define (run)
  (let* (
    (args-b64 "eyJhY2NvdW50X2lkIjoiOTQzYWRkYWJkZTc5MTNjNmY1ODA0M2QzNDhlYzc2MzY0MzY4OWI2OGRhMmU3YWIxODZiN2Q3NWUxZDU0NGZmMiJ9")
    (prices (http-get "https://api.rhea.finance/list-token-price"))
    (nbtc-p (json-get-str "price" (json-get-str "nbtc.bridge.near" prices)))
    (zec-p (json-get-str "price" (json-get-str "zec.omft.near" prices)))
    (usdt-p (json-get-str "price" (json-get-str "usdt.tether-token.near" prices)))
    (stnear-p (json-get-str "price" (json-get-str "meta-pool.near" prices)))
    (xrhea-p (json-get-str "price" (json-get-str "xtoken.rhealab.near" prices)))
    (burrow-p (json-get-str "price" (json-get-str "token.burrow.near" prices)))
    (lst-p (json-get-str "price" (json-get-str "lst.rhealab.near" prices)))
    (usdce-p (json-get-str "price" (json-get-str "a0b86991c6218b36c1d19d4a2e9eb0ce3606eb48.factory.bridge.near" prices)))
    (weth-p (json-get-str "price" (json-get-str "2260fac5e5542a773aa44fbcfedf7c193bc2c599.factory.bridge.near" prices)))
    (rpc-part (str-cat "{\"jsonrpc\":\"2.0\",\"id\":\"1\",\"method\":\"query\",\"params\":{\"request_type\":\"call_function\",\"finality\":\"final\",\"account_id\":\"contract.main.burrow.near\",\"method_name\":\"get_account\",\"args_base64\":\""
                args-b64 "\"}}"))
    (rpc-result (http-post "https://rpc.fastnear.com" rpc-part))
    (outer (json-get-str "result" rpc-result))
    (inner (json-get-str "result" outer))
    (account (json-decode-bytes inner))
    (supplied (json-get-str "supplied" account))
    (test-out (str-cat ",\"supplied\":" supplied "}"))
  )
  test-out))
