(define (get_credits)
  (let ((inp (near/input)))
    (let ((acct-len (bytes-to-u32 (str-slice inp 0 4))))
      (let ((acct (str-slice inp 4 (+ 4 acct-len))))
        (let ((credits (near/kload "c/" acct)))
          (near/return_str (to-string credits)))))))
