(define (run)
  (let* ((prices (http-get "https://api.rhea.finance/list-token-price"))
         (nbtc-p (json-get-str "price" (json-get-str "nbtc.bridge.near" prices)))
         (zec-p (json-get-str "price" (json-get-str "zec.omft.near" prices)))
         (usdt-p (json-get-str "price" (json-get-str "usdt.tether-token.near" prices)))
         (stnear-p (json-get-str "price" (json-get-str "meta-pool.near" prices)))
         (brrr-p (json-get-str "price" (json-get-str "token.burrow.near" prices)))
         (xrhea-p (json-get-str "price" (json-get-str "xtoken.rhealab.near" prices)))
         (rnear-p (json-get-str "price" (json-get-str "lst.rhealab.near" prices)))
         (wbtc-p (json-get-str "price" (json-get-str "2260fac5e5542a773aa44fbcfedf7c193bc2c599.factory.bridge.near" prices)))
         (usdce-p (json-get-str "price" (json-get-str "a0b86991c6218b36c1d19d4a2e9eb0ce3606eb48.factory.bridge.near" prices)))
         (usdc-p (json-get-str "price" (json-get-str "17208628f84f5d6ad33f0da3bbbeb27ffcb398eac501a31bd6ad2011e36133a1" prices)))
         (rpc-body "{\"jsonrpc\":\"2.0\",\"id\":\"1\",\"method\":\"query\",\"params\":{\"request_type\":\"call_function\",\"finality\":\"final\",\"account_id\":\"contract.main.burrow.near\",\"method_name\":\"get_account\",\"args_base64\":\"eyJhY2NvdW50X2lkIjoiOTQzYWRkYWJkZTc5MTNjNmY1ODA0M2QzNDhlYzc2MzY0MzY4OWI2OGRhMmU3YWIxODZiN2Q3NWUxZDU0NGZmMiJ9\"}}")
         (rpc (http-post "https://rpc.mainnet.near.org" rpc-body))
         (outer (json-get-str "result" rpc))
         (inner (json-get-str "result" outer))
         (account (json-decode-bytes inner))
         (supplied (json-get-str "supplied" account))
         (collateral (json-get-str "collateral" account))
         (borrowed (json-get-str "borrowed" account))
         (header (str-cat "nBTC:" nbtc-p " ZEC:" zec-p " USDT:" usdt-p " stN:" stnear-p " BRRR:" brrr-p " XR:" xrhea-p " rN:" rnear-p " WBTC:" wbtc-p " USDe:" usdce-p " USDC:" usdc-p))
         (summary (str-cat "\nS:" (to-string (str-len supplied)) " C:" (to-string (str-len collateral)) " B:" (to-string (str-len borrowed)))))
    (str-cat header summary)))
