(define (run)
  (let* ((prices (http-get "https://api.rhea.finance/list-token-price"))
         (p1 (json-get-str "price" (json-get-str "nbtc.bridge.near" prices)))
         (p2 (json-get-str "price" (json-get-str "zec.omft.near" prices)))
         (p3 (json-get-str "price" (json-get-str "usdt.tether-token.near" prices)))
         (p4 (json-get-str "price" (json-get-str "meta-pool.near" prices)))
         (p5 (json-get-str "price" (json-get-str "token.burrow.near" prices)))
         (p6 (json-get-str "price" (json-get-str "xtoken.rhealab.near" prices)))
         (p7 (json-get-str "price" (json-get-str "wrap.near" prices)))
         (p8 (json-get-str "price" (json-get-str "rnek.v2.near" prices)))
         (p9 (json-get-str "price" (json-get-str "a0b86991c6218b36c1d19d4a2e9eb0ce3606eb48.factory.bridge.near" prices)))
         (p10 (json-get-str "price" (json-get-str "usdc.contract.near" prices)))
         (out (str-cat p1 "|" p2 "|" p3 "|" p4 "|" p5 "|" p6 "|" p7 "|" p8 "|" p9 "|" p10)))
    out))
