(define (run)
  (let* ((args-b64 "eyJhY2NvdW50X2lkIjoiOTQzYWRkYWJkZTc5MTNjNmY1ODA0M2QzNDhlYzc2MzY0MzY4OWI2OGRhMmU3YWIxODZiN2Q3NWUxZDU0NGZmMiJ9")
         (rpc-body (str-cat "{\"jsonrpc\":\"2.0\",\"id\":\"1\",\"method\":\"query\",\"params\":{\"request_type\":\"call_function\",\"finality\":\"final\",\"account_id\":\"contract.main.burrow.near\",\"method_name\":\"get_account\",\"args_base64\":\"" args-b64 "\"}}"))
         (rpc-result (http-post "https://rpc.mainnet.near.org" rpc-body))
         (outer-result (json-get-str "result" rpc-result))
         (inner-result (json-get-str "result" outer-result))
         (decoded (json-decode-bytes inner-result))
         (supplied (json-get-str "supplied" decoded))
         (collateral (json-get-str "collateral" decoded))
         (borrowed (json-get-str "borrowed" decoded)))
    (str-cat "SUPPLIED(" (to-string (str-len supplied)) "): " supplied "\nCOLLATERAL(" (to-string (str-len collateral)) "): " collateral "\nBORROWED(" (to-string (str-len borrowed)) "): " borrowed)))