(define (run)
  (let* (
    (rpc-body (str-cat "{{\"jsonrpc\":\"2.0\",\"id\":\"1\",\"method\":\"query\",\"params\":{{\"request_type\":\"call_function\",\"finality\":\"final\",\"account_id\":\"contract.main.burrow.near\",\"method_name\":\"get_account\",\"args_base64\":\"eyJhY2NvdW50X2lkIjogIjk0M2FkZGFiZGU3OTEzYzZmNTgwNDNkMzQ4ZWM3NjM2NDM2ODliNjhkYTJlN2FiMTg2YjdkNzVlMWQ1NDRmZjIifQ==\"}}}}"))
    (rpc-result (http-post "https://rpc.mainnet.near.org" rpc-body))
    (r-len (str-len rpc-result))
    (outer-result (json-get-str "result" rpc-result))
    (or-len (str-len outer-result))
    (inner-result (json-get-str "result" outer-result))
    (ir-len (str-len inner-result))
    (account-bytes (json-decode-bytes inner-result))
    (ab-len (str-len account-bytes))
    (supplied-str (json-get-str "supplied" account-bytes))
    (s-len (str-len supplied-str))
    (out (str-cat "rpc:" (to-string r-len) " outer:" (to-string or-len) " inner:" (to-string ir-len) " decoded:" (to-string ab-len) " sup:" (to-string s-len))))
    out))
