(define (run)
  (let* ((prices (http-get "https://api.rhea.finance/list-token-price"))
         (o1 (json-get-str "token.burrow.near" prices))
         (p1 (json-get-str "price" o1))
         (o2 (json-get-str "nbtc.bridge.near" prices))
         (p2 (json-get-str "price" o2))
         (o3 (json-get-str "zec.omft.near" prices))
         (p3 (json-get-str "price" o3))
         (o4 (json-get-str "usdt.tether-token.near" prices))
         (p4 (json-get-str "price" o4)))
    (str-cat p1 "|" p2 "|" p3 "|" p4)))
