(define (run)
  (let* (
    (prices (http-get "https://api.rhea.finance/list-token-price"))
    (nbtc-p (json-get-str "price" (json-get-str "nbtc.bridge.near" prices)))
    (zec-p (json-get-str "price" (json-get-str "zec.omft.near" prices)))
    (usdt-p (json-get-str "price" (json-get-str "usdt.tether-token.near" prices)))
    (stnear-p (json-get-str "price" (json-get-str "meta-pool.near" prices)))
    (prices-0 (str-cat "{\"nbtc.bridge.near\":\"" nbtc-p "\""))
    (prices-1 (str-cat prices-0 ",\"zec.omft.near\":\"" zec-p "\""))
    (prices-2 (str-cat prices-1 ",\"usdt.tether-token.near\":\"" usdt-p "\""))
    (prices-3 (str-cat prices-2 ",\"meta-pool.near\":\"" stnear-p "\""))
    (prices-obj (str-cat prices-3 "}"))
    )
    prices-obj))
