(define (main)
  (println (and true false))
  (println (and true true))
  (println (or false false))
  (println (or false true))
  (println (not true))
  (println (not (and true false)))
  (println (and (or false true) (not false)))
  (println (< 1 2))
  (println (<= 2 2))
  (println (> 1 2))
  (println (>= 2 2)))
