(define X 10)
(define (main)
  (let ((a 1) (b 2))
    (println (+ a b))
    (let ((a 100))
      (println (+ a b))
      (let ((b 500) (a 7))
        (println (+ a b))
        (println (+ a b X))))
    (println a))
  (println X))
