(define (main)
  (let ((total 0))
    (dotimes (i 3)
      (dotimes (j 3)
        (set! total (+ total 1))))
    (println total))
  (let ((acc ""))
    (dotimes (k 4)
      (set! acc (str-cat acc "x")))
    (println acc))
  (dotimes (n 0) (println "never"))
  (println "done"))
