(define (main)
  (let ((i 0) (sum 0) (halts false))
    (while (not halts)
      (set! i (+ i 1))
      (set! sum (+ sum i))
      (if (> sum 10) (set! halts true) nil))
    (println i)
    (println sum))
  (let ((s ""))
    (while (< (str-length s) 3)
      (set! s (str-cat s "q")))
    (println s)))
