(define (even? n) (if (= n 0) true (odd? (- n 1))))
(define (odd? n) (if (= n 0) false (even? (- n 1))))
(define (main)
  (println (even? 10))
  (println (odd? 10))
  (println (even? 7))
  (println (odd? 7))
  (println (even? 0))
  (println (odd? 0)))
