(define (dollars s)
  (str->num (nth (str-split s ".") 0)))
(define (run)
  (let ((hl (dollars (json-get (http-post "https://api.hyperliquid.xyz/info" "{\"type\":\"allMids\"}") "BTC")))
        (cb (dollars (json-get (http-get "https://api.coinbase.com/v2/prices/BTC-USD/spot") "data.amount")))
        (bs (dollars (json-get (http-get "https://www.bitstamp.net/api/v2/ticker/btcusd/") "last"))))
    (str-cat "{\"hyperliquid\":" (to-string hl)
             ",\"coinbase\":" (to-string cb)
             ",\"bitstamp\":" (to-string bs)
             ",\"average\":" (to-string (/ (+ (+ hl cb) bs) 3))
             "}")))
