(define (dollars s)
  (str->num (nth (str-split s ".") 0)))
(define (run)
  (let ((hl (dollars (json-get "BTC" (http-post "https://api.hyperliquid.xyz/info" "{\"type\":\"allMids\"}"))))
        (cb (dollars (json-get "data.amount" (http-get "https://api.coinbase.com/v2/prices/BTC-USD/spot"))))
        (bs (dollars (json-get "last" (http-get "https://www.bitstamp.net/api/v2/ticker/btcusd/")))))
    (str-cat "{\"hyperliquid\":" (to-string hl)
             ",\"coinbase\":" (to-string cb)
             ",\"bitstamp\":" (to-string bs)
             ",\"average\":" (to-string (/ (+ (+ hl cb) bs) 3))
             "}")))
