(define (run)
  (let ((r1 (http-get "https://api.rhea.finance/get-token-price?token_id=token.rhealab.near")))
    (let ((p1 (json-get-str "price" r1)))
      (let ((s1 (str-cat "RHEA:" p1)))
        (let ((r2 (http-get "https://api.rhea.finance/get-token-price?token_id=nbtc.bridge.near")))
          (let ((p2 (json-get-str "price" r2)))
            (let ((s2 (str-cat s1 " BTC:" p2)))
              (let ((r3 (http-get "https://api.rhea.finance/get-token-price?token_id=usdt.tether-token.near")))
                (let ((p3 (json-get-str "price" r3)))
                  (let ((s3 (str-cat s2 " USDT:" p3)))
                    (let ((r4 (http-get "https://api.rhea.finance/get-token-price?token_id=meta-pool.near")))
                      (let ((p4 (json-get-str "price" r4)))
                        (let ((s4 (str-cat s3 " NEAR:" p4)))
                          (let ((r5 (http-get "https://api.rhea.finance/get-token-price?token_id=zec.omft.near")))
                            (let ((p5 (json-get-str "price" r5)))
                              (str-cat s4 " ZEC:" p5))))))))))))))))
