(define (cell-type p) (load_i64 p 0))
(define (cell-val p) (load_i64 p 8))
(define (cell-cdr p) (load_i64 p 16))
(define (num-box v) (let* ((c (malloc 24))) (begin (store_i64 c 0 1) (store_i64 c 8 v) c)))
(define (sym-box v) (let* ((c (malloc 24))) (begin (store_i64 c 0 3) (store_i64 c 8 v) c)))
(define (my-cons a b) (let* ((c (malloc 24))) (begin (store_i64 c 0 2) (store_i64 c 8 a) (store_i64 c 16 b) c)))
(define (null? p) (= p 0))
(define (num? p) (if (null? p) 0 (if (= (cell-type p) 1) 1 0)))
(define (pair? p) (if (null? p) 0 (if (= (cell-type p) 2) 1 0)))
(define (sym? p) (if (null? p) 0 (if (= (cell-type p) 3) 1 0)))
(define (truthy x) (if (null? x) 0 (if (num? x) (if (= (cell-val x) 0) 0 1) 1)))
(define (lookup e k) (if (null? e) 0 (if (= (cell-val (cell-val (cell-val e))) k) (cell-cdr (cell-val e)) (lookup (cell-cdr e) k))))
(define (ext e k v) (my-cons (my-cons (sym-box k) v) e))
(define (my-eval x env) (if (null? x) x (if (sym? x) (lookup env (cell-val x)) (if (pair? x) (eval-form x env) x))))
(define (eval-form x env) (let* ((head (cell-val x))) (if (pair? head) (let* ((eargs (evargs (cell-cdr x) env))) (apply-proc head eargs env)) (if (if (>= (cell-val head) 1001) (if (<= (cell-val head) 1004) 1 0) 0) (eval-special (cell-val head) (cell-cdr x) env) (let* ((eargs (evargs (cell-cdr x) env))) (let* ((fnv (lookup env (cell-val head)))) (apply-proc fnv eargs env)))))))
(define (eval-special sym args env) (if (= sym 1001) (cell-val args) (if (= sym 1002) (do-if args env) (if (= sym 1003) (do-begin (cell-cdr args) env) (if (= sym 1004) (do-begin (cell-cdr args) env) (do-begin args env))))))
(define (do-if args env) (if (truthy (my-eval (cell-val args) env)) (my-eval (cell-val (cell-cdr args)) env) (if (pair? (cell-cdr (cell-cdr args))) (my-eval (cell-val (cell-cdr (cell-cdr args))) env) 0)))
(define (do-begin args env) (if (null? args) 0 (if (null? (cell-cdr args)) (my-eval (cell-val args) env) (begin (my-eval (cell-val args) env) (do-begin (cell-cdr args) env)))))
(define (evargs args env) (if (null? args) 0 (my-cons (my-eval (cell-val args) env) (evargs (cell-cdr args) env))))
(define (apply-proc fn eargs env) (if (pair? fn) (let* ((params (cell-val fn))) (let* ((body (cell-cdr fn))) (let* ((ne (bind-params params eargs env))) (my-eval body ne)))) (dispatch (cell-val fn) eargs)))
(define (bind-params ps as env) (if (null? ps) env (if (null? as) env (bind-params (cell-cdr ps) (cell-cdr as) (ext env (cell-val (cell-val ps)) (cell-val as))))))
(define (apply-builtin code args) (dispatch code args))
(define (dispatch code args) (if (= code 1006) (do-eq args) (if (= code 1007) (do-add args) (if (= code 1008) (do-sub args) (if (= code 1009) (do-mul args) (if (= code 1010) (do-div args) (if (= code 1011) (do-lt args) (if (= code 1012) (do-gt args) (if (= code 1013) (do-my-cons args) (if (= code 1014) (my-car (cell-val args)) (if (= code 1015) (my-cdr (cell-val args)) (if (= code 1016) (do-null? args) (if (= code 1017) (do-pair? args) 0)))))))))))))
(define (do-add a) (num-box (+ (cell-val (cell-val a)) (cell-val (cell-val (cell-cdr a))))))
(define (do-sub a) (num-box (- (cell-val (cell-val a)) (cell-val (cell-val (cell-cdr a))))))
(define (do-mul a) (num-box (* (cell-val (cell-val a)) (cell-val (cell-val (cell-cdr a))))))
(define (do-div a) (num-box (/ (cell-val (cell-val a)) (cell-val (cell-val (cell-cdr a))))))
(define (do-lt a) (num-box (if (< (cell-val (cell-val a)) (cell-val (cell-val (cell-cdr a)))) 1 0)))
(define (do-gt a) (num-box (if (> (cell-val (cell-val a)) (cell-val (cell-val (cell-cdr a)))) 1 0)))
(define (do-eq a) (num-box (if (= (cell-val (cell-val a)) (cell-val (cell-val (cell-cdr a)))) 1 0)))
(define (do-my-cons a) (my-cons (cell-val a) (cell-val (cell-cdr a))))
(define (do-pair? a) (num-box (if (pair? (cell-val a)) 1 0)))
(define (do-null? a) (num-box (if (null? (cell-val a)) 1 0)))
(define (my-car p) (if (null? p) 0 (cell-val p)))
(define (my-cdr p) (if (null? p) 0 (cell-cdr p)))
(define (setup-env ) (let* ((burned (malloc 8))) (my-cons (my-cons (sym-box 1001) (num-box 1001)) (my-cons (my-cons (sym-box 1002) (num-box 1002)) (my-cons (my-cons (sym-box 1003) (num-box 1003)) (my-cons (my-cons (sym-box 1004) (num-box 1004)) (my-cons (my-cons (sym-box 1005) (num-box 1005)) (my-cons (my-cons (sym-box 1006) (num-box 1006)) (my-cons (my-cons (sym-box 1007) (num-box 1007)) (my-cons (my-cons (sym-box 1008) (num-box 1008)) (my-cons (my-cons (sym-box 1009) (num-box 1009)) (my-cons (my-cons (sym-box 1010) (num-box 1010)) (my-cons (my-cons (sym-box 1011) (num-box 1011)) (my-cons (my-cons (sym-box 1012) (num-box 1012)) (my-cons (my-cons (sym-box 1013) (num-box 1013)) (my-cons (my-cons (sym-box 1014) (num-box 1014)) (my-cons (my-cons (sym-box 1015) (num-box 1015)) (my-cons (my-cons (sym-box 1016) (num-box 1016)) (my-cons (my-cons (sym-box 1017) (num-box 1017)) 0)))))))))))))))))))
(define (run ) (let* ((env (setup-env)) (p0 (my-cons (sym-box 2001) 0)) (x0 (sym-box 2001)) (n2c (num-box 2)) (n3c (num-box 3)) (n111 (num-box 111)) (n333 (num-box 333)) (n4c (num-box 4)) (n222 (num-box 222))) (let* ((r (+ (+ (cell-val (my-eval (my-cons (sym-box 1007) (my-cons (my-cons (sym-box 1009) (my-cons (num-box 3) (my-cons (num-box 4) 0))) (my-cons (my-cons (sym-box 1008) (my-cons (num-box 10) (my-cons (num-box 5) 0))) 0))) env)) (cell-val (my-eval (my-cons (my-cons p0 (my-cons (sym-box 1009) (my-cons x0 (my-cons x0 0)))) (my-cons (num-box 7) 0)) env))) (cell-val (my-eval (my-cons (sym-box 1002) (my-cons (my-cons (sym-box 1012) (my-cons n3c (my-cons n2c 0))) (my-cons (my-cons (sym-box 1002) (my-cons (my-cons (sym-box 1011) (my-cons n3c (my-cons n4c 0))) (my-cons n111 (my-cons n222 0)))) (my-cons n333 0)))) env))))) (near/return_str (itoa r)))))
(export "run" run true)
