(memory 4096)
(define (cell-type p) (mem-get p))
(define (cell-val p) (mem-get (ptr-add p 8)))
(define (cell-cdr p) (mem-get (ptr-add p 16)))
(define (cell-alloc ) (let* ((head (mem-get 2097160))) (if (null? head) (begin (mem-set! 2097160 0) (let* ((q (ptr-add (mem-get 2097152) 2097152))) (begin (mem-set! 2097152 (ptr-add (mem-get 2097152) 24)) q))) (begin (mem-set! 2097160 (mem-get (ptr-add head 8))) head))))
(define (cell-free q) (begin (mem-set! (ptr-add q 8) (mem-get 2097160)) (mem-set! 2097160 q) 0))
(define (num-box v) (let* ((q (cell-alloc))) (begin (mem-set! q 1) (mem-set! (ptr-add q 8) v) (ptr-add q 0))))
(define (sym-box v) (let* ((q (cell-alloc))) (begin (mem-set! q 3) (mem-set! (ptr-add q 8) v) (ptr-add q 0))))
(define (my-cons a b) (let* ((q (cell-alloc))) (begin (mem-set! q 2) (mem-set! (ptr-add q 8) a) (mem-set! (ptr-add q 16) b) (ptr-add q 0))))
(define (make-env-cell e) (let* ((q (cell-alloc))) (begin (mem-set! q 4) (mem-set! (ptr-add q 8) e) (ptr-add q 0))))
(define (heap-init ) (begin (mem-set! 2097152 24) (mem-set! 2097160 0) 0))
(define (null? p) (= p 0))
(define (num? p) (if (null? p) 0 (if (= (cell-type p) 1) 1 0)))
(define (pair? p) (if (null? p) 0 (if (= (cell-type p) 2) 1 0)))
(define (sym? p) (if (null? p) 0 (if (= (cell-type p) 3) 1 0)))
(define (truthy x) (if (null? x) 0 (if (num? x) (if (= (cell-val x) 0) 0 1) 1)))
(define (lookup e k) (if (null? e) (near/panic (str_cat "unbound symbol: " (itoa k))) (if (= (cell-val (cell-val (cell-val e))) k) (cell-cdr (cell-val e)) (lookup (cell-cdr e) k))))
(define (ext e k v) (my-cons (my-cons (sym-box k) v) e))
(define (my-eval x env) (if (null? x) x (if (sym? x) (lookup env (cell-val x)) (if (pair? x) (eval-form x env) x))))
(define (is-op2 code) (if (>= code 1006) (if (<= code 1012) 1 0) 0))
(define (eval-form x env) (let* ((head (cell-val x))) (if (pair? head) (let* ((fn (my-eval head env))) (let* ((eargs (evargs (cell-cdr x) env))) (apply-proc fn eargs env))) (if (is-op2 (cell-val head)) (let* ((rest (cell-cdr x))) (apply-op2 (cell-val head) (my-eval (cell-val rest) env) (my-eval (cell-val (cell-cdr rest)) env))) (if (if (>= (cell-val head) 1001) (if (<= (cell-val head) 1005) 1 0) 0) (eval-special (cell-val head) (cell-cdr x) env) (let* ((eargs (evargs (cell-cdr x) env))) (let* ((fnv (lookup env (cell-val head)))) (apply-proc fnv eargs env))))))))
(define (eval-special sym args env) (if (= sym 1001) (cell-val args) (if (= sym 1002) (do-if args env) (if (= sym 1003) (do-begin args env) (if (= sym 1004) (if (pair? (cell-val args)) (let* ((target (cell-val args))) (make-env-cell (ext env (cell-val (cell-val target)) (my-cons (cell-cdr target) (cell-cdr args))))) (let* ((target (cell-val args))) (make-env-cell (ext env (cell-val target) (my-eval (cell-val (cell-cdr args)) env))))) (if (= sym 1005) (my-cons (cell-val args) (cell-cdr args)) (my-eval (my-cons (cell-val args) (evargs (cell-cdr args) env)) env)))))))
(define (do-if args env) (if (truthy (my-eval (cell-val args) env)) (my-eval (cell-val (cell-cdr args)) env) (if (pair? (cell-cdr (cell-cdr args))) (my-eval (cell-val (cell-cdr (cell-cdr args))) env) 0)))
(define (do-begin args env) (if (null? args) 0 (if (null? (cell-cdr args)) (let* ((r (my-eval (cell-val args) env))) (if (if (null? r) 0 (if (= (cell-type r) 4) 1 0)) (cell-val r) r)) (let* ((r (my-eval (cell-val args) env))) (if (if (null? r) 0 (if (= (cell-type r) 4) 1 0)) (do-begin (cell-cdr args) (cell-val r)) (do-begin (cell-cdr args) env))))))
(define (read-form s pos) (let* ((p (skip-ws s pos))) (if (>= p (str-len s)) 0 (if (str_eq (char-at s p) "(")  (read-list s (+ p 1)) (read-atom s p)))))
(define (evargs args env) (if (null? args) 0 (my-cons (my-eval (cell-val args) env) (evargs (cell-cdr args) env))))
(define (apply-proc fn eargs env) (if (pair? fn) (let* ((params (cell-val fn))) (let* ((body (cell-cdr fn))) (let* ((ne (bind-params params eargs env))) (do-begin body ne)))) (dispatch (cell-val fn) eargs)))
(define (bind-params ps as env) (if (null? ps) env (if (null? as) env (bind-params (cell-cdr ps) (cell-cdr as) (ext env (cell-val (cell-val ps)) (cell-val as))))))
(define (apply-builtin code args) (dispatch code args))
(define (dispatch code args) (if (= code 1006) (do-eq args) (if (= code 1007) (do-add args) (if (= code 1008) (do-sub args) (if (= code 1009) (do-mul args) (if (= code 1010) (do-div args) (if (= code 1011) (do-lt args) (if (= code 1012) (do-gt args) (if (= code 1013) (do-my-cons args) (if (= code 1014) (my-car (cell-val args)) (if (= code 1015) (my-cdr (cell-val args)) (if (= code 1016) (do-null? args) (if (= code 1017) (do-pair? args) 0)))))))))))))
(define (do-add a) (num-box (+ (cell-val (cell-val a)) (cell-val (cell-val (cell-cdr a))))))
(define (do-sub a) (num-box (- (cell-val (cell-val a)) (cell-val (cell-val (cell-cdr a))))))
(define (do-mul a) (num-box (* (cell-val (cell-val a)) (cell-val (cell-val (cell-cdr a))))))
(define (do-div a) (num-box (/ (cell-val (cell-val a)) (cell-val (cell-val (cell-cdr a))))))
(define (do-lt a) (num-box (if (< (cell-val (cell-val a)) (cell-val (cell-val (cell-cdr a)))) 1 0)))
(define (do-gt a) (num-box (if (> (cell-val (cell-val a)) (cell-val (cell-val (cell-cdr a)))) 1 0)))
(define (do-eq a) (num-box (if (= (cell-val (cell-val a)) (cell-val (cell-val (cell-cdr a)))) 1 0)))
(define (do-my-cons a) (my-cons (cell-val a) (cell-val (cell-cdr a))))
(define (do-pair? a) (num-box (if (pair? (cell-val a)) 1 0)))
(define (do-null? a) (num-box (if (null? (cell-val a)) 1 0)))
(define (my-car p) (if (null? p) 0 (cell-val p)))
(define (my-cdr p) (if (null? p) 0 (cell-cdr p)))
(define (setup-env ) (begin (my-cons (my-cons (sym-box 1001) (num-box 1001)) (my-cons (my-cons (sym-box 1002) (num-box 1002)) (my-cons (my-cons (sym-box 1003) (num-box 1003)) (my-cons (my-cons (sym-box 1004) (num-box 1004)) (my-cons (my-cons (sym-box 1005) (num-box 1005)) (my-cons (my-cons (sym-box 1006) (num-box 1006)) (my-cons (my-cons (sym-box 1007) (num-box 1007)) (my-cons (my-cons (sym-box 1008) (num-box 1008)) (my-cons (my-cons (sym-box 1009) (num-box 1009)) (my-cons (my-cons (sym-box 1010) (num-box 1010)) (my-cons (my-cons (sym-box 1011) (num-box 1011)) (my-cons (my-cons (sym-box 1012) (num-box 1012)) (my-cons (my-cons (sym-box 1013) (num-box 1013)) (my-cons (my-cons (sym-box 1014) (num-box 1014)) (my-cons (my-cons (sym-box 1015) (num-box 1015)) (my-cons (my-cons (sym-box 1016) (num-box 1016)) (my-cons (my-cons (sym-box 1017) (num-box 1017)) 0)))))))))))))))))))
(define (run ) (let* ((env (setup-env))) (let* ((r (+ (+ (cell-val (my-eval (my-cons (sym-box 1007) (my-cons (my-cons (sym-box 1009) (my-cons (num-box 3) (my-cons (num-box 4) 0))) (my-cons (my-cons (sym-box 1008) (my-cons (num-box 10) (my-cons (num-box 5) 0))) 0))) env)) (cell-val (my-eval (my-cons (my-cons (my-cons (sym-box 2001) 0) (my-cons (sym-box 1009) (my-cons (sym-box 2001) (my-cons (sym-box 2001) 0)))) (my-cons (num-box 7) 0)) env))) (cell-val (my-eval (my-cons (sym-box 1002) (my-cons (my-cons (sym-box 1012) (my-cons (num-box 3) (my-cons (num-box 2) 0))) (my-cons (my-cons (sym-box 1002) (my-cons (my-cons (sym-box 1011) (my-cons (num-box 3) (my-cons (num-box 4) 0))) (my-cons (num-box 111) (my-cons (num-box 222) 0)))) (my-cons (num-box 333) 0)))) env))))) (near/return_str (itoa r)))))
(export "run" run true)

(define (char-at s pos) (str-slice s pos (+ pos 1)))
(define (ws? c) (if (str_eq c " ") 1 0))
(define (delim? c) (if (ws? c) 1 (if (str_eq c "(") 1 (if (str_eq c ")") 1 0))))
(define (skip-ws s pos) (if (>= pos (str-len s)) pos (if (= (ws? (char-at s pos)) 1) (skip-ws s (+ pos 1)) pos)))
(define (atom-end s pos) (if (>= pos (str-len s)) pos (if (= (delim? (char-at s pos)) 1) pos (atom-end s (+ pos 1)))))
(define (sym-hash tok i acc) (if (>= i (str-len tok)) acc (sym-hash tok (+ i 1) (mod (+ (* acc 31) (byte-at tok i)) 4096))))
(define (sym-code tok) (let* ((c (if (str_eq tok "quote") 1001 (if (str_eq tok "if") 1002 (if (str_eq tok "begin") 1003 (if (str_eq tok "define") 1004 (if (str_eq tok "lambda") 1005 (if (str_eq tok "=") 1006 (if (str_eq tok "+") 1007 (if (str_eq tok "-") 1008 (if (str_eq tok "*") 1009 (if (str_eq tok "/") 1010 (if (str_eq tok "<") 1011 (if (str_eq tok ">") 1012 (if (str_eq tok "cons") 1013 (if (str_eq tok "car") 1014 (if (str_eq tok "cdr") 1015 (if (str_eq tok "null?") 1016 (if (str_eq tok "pair?") 1017 (if (str_eq tok "a") 2001 (if (str_eq tok "b") 2002 (if (str_eq tok "c") 2003 (if (str_eq tok "d") 2004 (if (str_eq tok "e") 2005 (if (str_eq tok "f") 2006 (if (str_eq tok "g") 2007 (if (str_eq tok "h") 2008 (if (str_eq tok "i") 2009 (if (str_eq tok "j") 2010 (if (str_eq tok "k") 2011 (if (str_eq tok "l") 2012 (if (str_eq tok "m") 2013 (if (str_eq tok "n") 2014 (if (str_eq tok "o") 2015 (if (str_eq tok "p") 2016 (if (str_eq tok "q") 2017 (if (str_eq tok "r") 2018 (if (str_eq tok "s") 2019 (if (str_eq tok "t") 2020 (if (str_eq tok "u") 2021 (if (str_eq tok "v") 2022 (if (str_eq tok "w") 2023 (if (str_eq tok "x") 2024 (if (str_eq tok "y") 2025 (if (str_eq tok "z") 2026 (if (str_eq tok "fn") 2027 (if (str_eq tok "acc") 2028 (if (str_eq tok "lst") 2029 (if (str_eq tok "val") 2030 (if (str_eq tok "fact") 2051 (if (str_eq tok "fib") 2052 (if (str_eq tok "countd") 2070 (if (str_eq tok "cd") 2003 0))))))))))))))))))))))))))))))))))))))))))))))))))))) (if (= c 0) (+ 30000 (sym-hash tok 0 0)) c)))
(define (read-atom s pos) (let* ((e (atom-end s pos))) (let* ((tok (str-slice s pos e))) (if (= (str-to-num tok) 0) (if (str_eq tok "0") (my-cons (num-box 0) (my-cons e 0)) (my-cons (sym-box (sym-code tok)) (my-cons e 0))) (my-cons (num-box (str-to-num tok)) (my-cons e 0))))))
(define (read-list s pos) (let* ((p (skip-ws s pos))) (if (>= p (str-len s)) 0 (if (str_eq (char-at s p) ")") (my-cons 0 (my-cons (+ p 1) 0)) (let* ((r (read-form s p))) (if (null? r) 0 (let* ((fst (cell-val r))) (let* ((rst (cell-cdr r))) (let* ((np (cell-val rst))) (let* ((rr (read-list s np))) (if (null? rr) 0 (my-cons (my-cons fst (cell-val rr)) (cell-cdr rr)))))))))))))
(define (evargs args env) (if (null? args) 0 (my-cons (my-eval (cell-val args) env) (evargs (cell-cdr args) env))))
;; 2-arg arithmetic fast path (gas diet, 2026-08-29): eval both operands directly —
;; skips evargs cons pairs + the dispatch re-unboxing. Semantics identical to
;; (do-add (evargs ...)) for exactly-2-arg calls, which is what fib/arith generate.
(define (do-add2 a b) (num-box (+ (cell-val a) (cell-val b))))
(define (do-sub2 a b) (num-box (- (cell-val a) (cell-val b))))
(define (do-mul2 a b) (num-box (* (cell-val a) (cell-val b))))
(define (do-lt2 a b) (num-box (if (< (cell-val a) (cell-val b)) 1 0)))
(define (do-gt2 a b) (num-box (if (> (cell-val a) (cell-val b)) 1 0)))
(define (do-eq2 a b) (num-box (if (= (cell-val a) (cell-val b)) 1 0)))
(define (do-div2 a b) (num-box (/ (cell-val a) (cell-val b))))
(define (apply-op2 code a b) (if (= code 1006) (do-eq2 a b) (if (= code 1007) (do-add2 a b) (if (= code 1008) (do-sub2 a b) (if (= code 1009) (do-mul2 a b) (if (= code 1010) (do-div2 a b) (if (= code 1011) (do-lt2 a b) (if (= code 1012) (do-gt2 a b) 0))))))))
;; JSON args unwrap: near-cli sends {"program":"..."} — extract the raw program
;; if the input is wrapped, else treat input as the program itself.
(define (json-prog s) (let* ((l (str-len s))) (if (str_eq (str-slice s 0 1) "{") (str-slice s 12 (- l 2)) s)))
(define (do-eval) (let* ((e (heap-init))) (let* ((srcrev (near/input))) (let* ((src (json-prog srcrev))) (let* ((r (read-form src 0))) (let* ((ast (cell-val r))) (let* ((env (setup-env))) (near/return_str (itoa (+ (cell-val (my-eval ast env)) 0))))))))))
(export "eval" do-eval true)
