// AFP CLMM port — TS twin (generated by gen_ts.py).
// Edit gen_ts.py, not this file — every name regenerates.
// u128 values are decimal STRINGS; all arithmetic via u128* fns (money-sealed).
// grug naming: GRID_LO = grid floor, CELL_TOP_i = grid top of cell i,
// CELL_L_i = liquidity in cell i, CELL_Q_i = gross units cell i eats per
// unit price, sqp = current sqrt-price. Keys ("s:...") are wire format —
// do NOT rename keys.

function sget(k: string): string {
  return near.storageGet(k) ?? "0";
}
function sput(k: string, v: string): void {
  near.storageSet(k, v);
}
function fail(m: string): void {
  near.log(m);
  near.abort(m);
}
// splt3: N-pool composition (N=3, shared grid, fee 3000000000000000/1000000000000000000).
// Net is concave in y => optimum EQUALIZES ENDING PRICE p*:
//   sum_k qgross_k(p*) = y,  y_k = min(cap_k, qgross_k(p*)).
// 48-stage unrolled binary search (see NOTE); sums muldiv-free (mdiv by "1").
const GRID_LO = "1000000000";
const GRID_MID = "2000000000";
const GRID_HI = "4000000000";
const CELL_W_1 = "1000000000";   // price width of zone 1 (below mid)
const CELL_W_2 = "2000000000";   // price width of zone 2 (above mid)
const POOL_CAP_0 = "220661985957873620862589000000000";
const POOL_CAP_1 = "190571715145436308926782000000000";
const POOL_CAP_2 = "110330992978936810431296000000000";
const Q0_LO = "100300902708124373119359";   // pool 0 gross-per-price, zone 1
const Q0_HI = "60180541624874623871615";   // pool 0 gross-per-price, zone 2
const Q1_LO = "30090270812437311935808";
const Q1_HI = "80240722166499498495487";
const Q2_LO = "50150451354062186559680";
const Q2_HI = "30090270812437311935808";
const POOL0 = "pa.clmm.test.near";
const POOL1 = "n1.clmm.test.near";
const POOL2 = "n2.clmm.test.near";
const SELF = "splt3.clmm.test.near";
const TGAS = 50000000000;
const SWAP_ARGS = '{"min_out":"0"}';

// gross units pool k consumes walking GRID_LO -> price (exact: muldiv by "1")
function gross0(price: string): string {
  if (u128.lt(GRID_MID, price)) {
    return u128.add(u128MulDiv(Q0_LO, CELL_W_1, "1"), u128MulDiv(Q0_HI, u128.sub(price, GRID_MID), "1"));
  }
  return u128MulDiv(Q0_LO, u128.sub(price, GRID_LO), "1");
}
function gross1(price: string): string {
  if (u128.lt(GRID_MID, price)) {
    return u128.add(u128MulDiv(Q1_LO, CELL_W_1, "1"), u128MulDiv(Q1_HI, u128.sub(price, GRID_MID), "1"));
  }
  return u128MulDiv(Q1_LO, u128.sub(price, GRID_LO), "1");
}
function gross2(price: string): string {
  if (u128.lt(GRID_MID, price)) {
    return u128.add(u128MulDiv(Q2_LO, CELL_W_1, "1"), u128MulDiv(Q2_HI, u128.sub(price, GRID_MID), "1"));
  }
  return u128MulDiv(Q2_LO, u128.sub(price, GRID_LO), "1");
}
function sum_gross(price: string): string {
  return u128.add(gross0(price), u128.add(gross1(price), gross2(price)));
}
function min_cap(a: string, b: string): string {
  return u128.lt(a, b) ? a : b;
}

export function split(): string {
  const deposit: Yocto = near.attachedDepositU128();
  const who = near.predecessorAccountId();
  if (u128.eq(deposit, "0")) { fail("ERR_ZERO"); }
  // NOTE: no loop-carried u128-string mutation — when 2+ string lets
  // interlock through a loop (lo,hi <- mid <- (lo+hi)), writes silently
  // stop sticking after iteration 1 (frontend bug; probe /tmp/bsprobe).
  // Straight-line unique-named const stages, mirroring the lisp let* chain.
  // unrolled binary search stages (no loop-carried string mutation)
  const lo0 = GRID_LO;
  const hi0 = GRID_HI;
  const mid1 = u128MulDiv(u128.add(lo0, hi0), "1", "2");
  const go_up1 = u128.lt(sum_gross(mid1), deposit);
  const lo1 = go_up1 ? u128.add(mid1, "1") : lo0;
  const hi1 = go_up1 ? hi0 : mid1;
  const mid2 = u128MulDiv(u128.add(lo1, hi1), "1", "2");
  const go_up2 = u128.lt(sum_gross(mid2), deposit);
  const lo2 = go_up2 ? u128.add(mid2, "1") : lo1;
  const hi2 = go_up2 ? hi1 : mid2;
  const mid3 = u128MulDiv(u128.add(lo2, hi2), "1", "2");
  const go_up3 = u128.lt(sum_gross(mid3), deposit);
  const lo3 = go_up3 ? u128.add(mid3, "1") : lo2;
  const hi3 = go_up3 ? hi2 : mid3;
  const mid4 = u128MulDiv(u128.add(lo3, hi3), "1", "2");
  const go_up4 = u128.lt(sum_gross(mid4), deposit);
  const lo4 = go_up4 ? u128.add(mid4, "1") : lo3;
  const hi4 = go_up4 ? hi3 : mid4;
  const mid5 = u128MulDiv(u128.add(lo4, hi4), "1", "2");
  const go_up5 = u128.lt(sum_gross(mid5), deposit);
  const lo5 = go_up5 ? u128.add(mid5, "1") : lo4;
  const hi5 = go_up5 ? hi4 : mid5;
  const mid6 = u128MulDiv(u128.add(lo5, hi5), "1", "2");
  const go_up6 = u128.lt(sum_gross(mid6), deposit);
  const lo6 = go_up6 ? u128.add(mid6, "1") : lo5;
  const hi6 = go_up6 ? hi5 : mid6;
  const mid7 = u128MulDiv(u128.add(lo6, hi6), "1", "2");
  const go_up7 = u128.lt(sum_gross(mid7), deposit);
  const lo7 = go_up7 ? u128.add(mid7, "1") : lo6;
  const hi7 = go_up7 ? hi6 : mid7;
  const mid8 = u128MulDiv(u128.add(lo7, hi7), "1", "2");
  const go_up8 = u128.lt(sum_gross(mid8), deposit);
  const lo8 = go_up8 ? u128.add(mid8, "1") : lo7;
  const hi8 = go_up8 ? hi7 : mid8;
  const mid9 = u128MulDiv(u128.add(lo8, hi8), "1", "2");
  const go_up9 = u128.lt(sum_gross(mid9), deposit);
  const lo9 = go_up9 ? u128.add(mid9, "1") : lo8;
  const hi9 = go_up9 ? hi8 : mid9;
  const mid10 = u128MulDiv(u128.add(lo9, hi9), "1", "2");
  const go_up10 = u128.lt(sum_gross(mid10), deposit);
  const lo10 = go_up10 ? u128.add(mid10, "1") : lo9;
  const hi10 = go_up10 ? hi9 : mid10;
  const mid11 = u128MulDiv(u128.add(lo10, hi10), "1", "2");
  const go_up11 = u128.lt(sum_gross(mid11), deposit);
  const lo11 = go_up11 ? u128.add(mid11, "1") : lo10;
  const hi11 = go_up11 ? hi10 : mid11;
  const mid12 = u128MulDiv(u128.add(lo11, hi11), "1", "2");
  const go_up12 = u128.lt(sum_gross(mid12), deposit);
  const lo12 = go_up12 ? u128.add(mid12, "1") : lo11;
  const hi12 = go_up12 ? hi11 : mid12;
  const mid13 = u128MulDiv(u128.add(lo12, hi12), "1", "2");
  const go_up13 = u128.lt(sum_gross(mid13), deposit);
  const lo13 = go_up13 ? u128.add(mid13, "1") : lo12;
  const hi13 = go_up13 ? hi12 : mid13;
  const mid14 = u128MulDiv(u128.add(lo13, hi13), "1", "2");
  const go_up14 = u128.lt(sum_gross(mid14), deposit);
  const lo14 = go_up14 ? u128.add(mid14, "1") : lo13;
  const hi14 = go_up14 ? hi13 : mid14;
  const mid15 = u128MulDiv(u128.add(lo14, hi14), "1", "2");
  const go_up15 = u128.lt(sum_gross(mid15), deposit);
  const lo15 = go_up15 ? u128.add(mid15, "1") : lo14;
  const hi15 = go_up15 ? hi14 : mid15;
  const mid16 = u128MulDiv(u128.add(lo15, hi15), "1", "2");
  const go_up16 = u128.lt(sum_gross(mid16), deposit);
  const lo16 = go_up16 ? u128.add(mid16, "1") : lo15;
  const hi16 = go_up16 ? hi15 : mid16;
  const mid17 = u128MulDiv(u128.add(lo16, hi16), "1", "2");
  const go_up17 = u128.lt(sum_gross(mid17), deposit);
  const lo17 = go_up17 ? u128.add(mid17, "1") : lo16;
  const hi17 = go_up17 ? hi16 : mid17;
  const mid18 = u128MulDiv(u128.add(lo17, hi17), "1", "2");
  const go_up18 = u128.lt(sum_gross(mid18), deposit);
  const lo18 = go_up18 ? u128.add(mid18, "1") : lo17;
  const hi18 = go_up18 ? hi17 : mid18;
  const mid19 = u128MulDiv(u128.add(lo18, hi18), "1", "2");
  const go_up19 = u128.lt(sum_gross(mid19), deposit);
  const lo19 = go_up19 ? u128.add(mid19, "1") : lo18;
  const hi19 = go_up19 ? hi18 : mid19;
  const mid20 = u128MulDiv(u128.add(lo19, hi19), "1", "2");
  const go_up20 = u128.lt(sum_gross(mid20), deposit);
  const lo20 = go_up20 ? u128.add(mid20, "1") : lo19;
  const hi20 = go_up20 ? hi19 : mid20;
  const mid21 = u128MulDiv(u128.add(lo20, hi20), "1", "2");
  const go_up21 = u128.lt(sum_gross(mid21), deposit);
  const lo21 = go_up21 ? u128.add(mid21, "1") : lo20;
  const hi21 = go_up21 ? hi20 : mid21;
  const mid22 = u128MulDiv(u128.add(lo21, hi21), "1", "2");
  const go_up22 = u128.lt(sum_gross(mid22), deposit);
  const lo22 = go_up22 ? u128.add(mid22, "1") : lo21;
  const hi22 = go_up22 ? hi21 : mid22;
  const mid23 = u128MulDiv(u128.add(lo22, hi22), "1", "2");
  const go_up23 = u128.lt(sum_gross(mid23), deposit);
  const lo23 = go_up23 ? u128.add(mid23, "1") : lo22;
  const hi23 = go_up23 ? hi22 : mid23;
  const mid24 = u128MulDiv(u128.add(lo23, hi23), "1", "2");
  const go_up24 = u128.lt(sum_gross(mid24), deposit);
  const lo24 = go_up24 ? u128.add(mid24, "1") : lo23;
  const hi24 = go_up24 ? hi23 : mid24;
  const mid25 = u128MulDiv(u128.add(lo24, hi24), "1", "2");
  const go_up25 = u128.lt(sum_gross(mid25), deposit);
  const lo25 = go_up25 ? u128.add(mid25, "1") : lo24;
  const hi25 = go_up25 ? hi24 : mid25;
  const mid26 = u128MulDiv(u128.add(lo25, hi25), "1", "2");
  const go_up26 = u128.lt(sum_gross(mid26), deposit);
  const lo26 = go_up26 ? u128.add(mid26, "1") : lo25;
  const hi26 = go_up26 ? hi25 : mid26;
  const mid27 = u128MulDiv(u128.add(lo26, hi26), "1", "2");
  const go_up27 = u128.lt(sum_gross(mid27), deposit);
  const lo27 = go_up27 ? u128.add(mid27, "1") : lo26;
  const hi27 = go_up27 ? hi26 : mid27;
  const mid28 = u128MulDiv(u128.add(lo27, hi27), "1", "2");
  const go_up28 = u128.lt(sum_gross(mid28), deposit);
  const lo28 = go_up28 ? u128.add(mid28, "1") : lo27;
  const hi28 = go_up28 ? hi27 : mid28;
  const mid29 = u128MulDiv(u128.add(lo28, hi28), "1", "2");
  const go_up29 = u128.lt(sum_gross(mid29), deposit);
  const lo29 = go_up29 ? u128.add(mid29, "1") : lo28;
  const hi29 = go_up29 ? hi28 : mid29;
  const mid30 = u128MulDiv(u128.add(lo29, hi29), "1", "2");
  const go_up30 = u128.lt(sum_gross(mid30), deposit);
  const lo30 = go_up30 ? u128.add(mid30, "1") : lo29;
  const hi30 = go_up30 ? hi29 : mid30;
  const mid31 = u128MulDiv(u128.add(lo30, hi30), "1", "2");
  const go_up31 = u128.lt(sum_gross(mid31), deposit);
  const lo31 = go_up31 ? u128.add(mid31, "1") : lo30;
  const hi31 = go_up31 ? hi30 : mid31;
  const mid32 = u128MulDiv(u128.add(lo31, hi31), "1", "2");
  const go_up32 = u128.lt(sum_gross(mid32), deposit);
  const lo32 = go_up32 ? u128.add(mid32, "1") : lo31;
  const hi32 = go_up32 ? hi31 : mid32;
  const mid33 = u128MulDiv(u128.add(lo32, hi32), "1", "2");
  const go_up33 = u128.lt(sum_gross(mid33), deposit);
  const lo33 = go_up33 ? u128.add(mid33, "1") : lo32;
  const hi33 = go_up33 ? hi32 : mid33;
  const mid34 = u128MulDiv(u128.add(lo33, hi33), "1", "2");
  const go_up34 = u128.lt(sum_gross(mid34), deposit);
  const lo34 = go_up34 ? u128.add(mid34, "1") : lo33;
  const hi34 = go_up34 ? hi33 : mid34;
  const mid35 = u128MulDiv(u128.add(lo34, hi34), "1", "2");
  const go_up35 = u128.lt(sum_gross(mid35), deposit);
  const lo35 = go_up35 ? u128.add(mid35, "1") : lo34;
  const hi35 = go_up35 ? hi34 : mid35;
  const mid36 = u128MulDiv(u128.add(lo35, hi35), "1", "2");
  const go_up36 = u128.lt(sum_gross(mid36), deposit);
  const lo36 = go_up36 ? u128.add(mid36, "1") : lo35;
  const hi36 = go_up36 ? hi35 : mid36;
  const mid37 = u128MulDiv(u128.add(lo36, hi36), "1", "2");
  const go_up37 = u128.lt(sum_gross(mid37), deposit);
  const lo37 = go_up37 ? u128.add(mid37, "1") : lo36;
  const hi37 = go_up37 ? hi36 : mid37;
  const mid38 = u128MulDiv(u128.add(lo37, hi37), "1", "2");
  const go_up38 = u128.lt(sum_gross(mid38), deposit);
  const lo38 = go_up38 ? u128.add(mid38, "1") : lo37;
  const hi38 = go_up38 ? hi37 : mid38;
  const mid39 = u128MulDiv(u128.add(lo38, hi38), "1", "2");
  const go_up39 = u128.lt(sum_gross(mid39), deposit);
  const lo39 = go_up39 ? u128.add(mid39, "1") : lo38;
  const hi39 = go_up39 ? hi38 : mid39;
  const mid40 = u128MulDiv(u128.add(lo39, hi39), "1", "2");
  const go_up40 = u128.lt(sum_gross(mid40), deposit);
  const lo40 = go_up40 ? u128.add(mid40, "1") : lo39;
  const hi40 = go_up40 ? hi39 : mid40;
  const mid41 = u128MulDiv(u128.add(lo40, hi40), "1", "2");
  const go_up41 = u128.lt(sum_gross(mid41), deposit);
  const lo41 = go_up41 ? u128.add(mid41, "1") : lo40;
  const hi41 = go_up41 ? hi40 : mid41;
  const mid42 = u128MulDiv(u128.add(lo41, hi41), "1", "2");
  const go_up42 = u128.lt(sum_gross(mid42), deposit);
  const lo42 = go_up42 ? u128.add(mid42, "1") : lo41;
  const hi42 = go_up42 ? hi41 : mid42;
  const mid43 = u128MulDiv(u128.add(lo42, hi42), "1", "2");
  const go_up43 = u128.lt(sum_gross(mid43), deposit);
  const lo43 = go_up43 ? u128.add(mid43, "1") : lo42;
  const hi43 = go_up43 ? hi42 : mid43;
  const mid44 = u128MulDiv(u128.add(lo43, hi43), "1", "2");
  const go_up44 = u128.lt(sum_gross(mid44), deposit);
  const lo44 = go_up44 ? u128.add(mid44, "1") : lo43;
  const hi44 = go_up44 ? hi43 : mid44;
  const mid45 = u128MulDiv(u128.add(lo44, hi44), "1", "2");
  const go_up45 = u128.lt(sum_gross(mid45), deposit);
  const lo45 = go_up45 ? u128.add(mid45, "1") : lo44;
  const hi45 = go_up45 ? hi44 : mid45;
  const mid46 = u128MulDiv(u128.add(lo45, hi45), "1", "2");
  const go_up46 = u128.lt(sum_gross(mid46), deposit);
  const lo46 = go_up46 ? u128.add(mid46, "1") : lo45;
  const hi46 = go_up46 ? hi45 : mid46;
  const mid47 = u128MulDiv(u128.add(lo46, hi46), "1", "2");
  const go_up47 = u128.lt(sum_gross(mid47), deposit);
  const lo47 = go_up47 ? u128.add(mid47, "1") : lo46;
  const hi47 = go_up47 ? hi46 : mid47;
  const mid48 = u128MulDiv(u128.add(lo47, hi47), "1", "2");
  const go_up48 = u128.lt(sum_gross(mid48), deposit);
  const lo48 = go_up48 ? u128.add(mid48, "1") : lo47;
  const hi48 = go_up48 ? hi47 : mid48;
  const price = hi48;
  const share0 = min_cap(gross0(price), deposit);
  const left1 = u128.sub(deposit, share0);
  const share1 = min_cap(gross1(price), left1);
  const left2 = u128.sub(left1, share1);
  const share2 = min_cap(gross2(price), left2);
  const cb = '{"who":' + near.jsonQuote(who) + '}';
  sput("s:lo", lo48);
  sput("s:hi", hi48);
  sput("s:p", price);
  sput("sp:who", who);
  sput("s:s0", share0);
  sput("s:s1", share1);
  sput("s:s2", share2);
  near.log("splt3 price=" + price);
  const prom0 = near.promiseCreate(POOL0, "swap", SWAP_ARGS, share0, TGAS);
  near.promiseThen(prom0, SELF, "on0", cb, "0", TGAS);
  const prom1 = near.promiseCreate(POOL1, "swap", SWAP_ARGS, share1, TGAS);
  near.promiseThen(prom1, SELF, "on1", cb, "0", TGAS);
  const prom2 = near.promiseCreate(POOL2, "swap", SWAP_ARGS, share2, TGAS);
  near.promiseThen(prom2, SELF, "on2", cb, "0", TGAS);
  return "queued";
}

function credit(failTag: string): string {
  const who = sget("sp:who");
  const out = near.promiseResult(0);
  if (out === "") { fail(failTag); }
  const pk = "paid:" + who;
  const total = u128.add(sget(pk), out);
  sput(pk, total);
  return total;
}

export function on0(): string {
  return credit("ERR_P0");
}
export function on1(): string {
  return credit("ERR_P1");
}
export function on2(): string {
  const total = credit("ERR_P2");
  near.log("splt3 total=" + total);
  return total;
}

export function get_paid(): string {
  return sget("paid:" + near.predecessorAccountId());
}

export function get_split(): string {
  return sget("s:s0") + "," + sget("s:s1") + "," + sget("s:s2");
}
