;; Test: exact handle-command pattern from ralph-agent
(define (starts-with? s prefix)
  (let ((slen (str-length s)))
    (let ((plen (str-length prefix)))
      (if (< slen plen) 0
        (= (str-slice s 0 plen) prefix)))))

(define (status) "ok-status")
(define (list-tasks) "tasks-list")
(define (reset-agent) (storage-set "ralph:phase" "idle"))
(define (get-progress) "progress-info")
(define (add-task id desc priority)
  (str-concat "added:" id ":" desc))

(define (handle-command msg)
  (if (= msg "status")
    (status)
    (if (= msg "tasks")
      (list-tasks)
      (if (= msg "reset")
        (begin (reset-agent) "Agent reset.")
        (if (= msg "run")
          (begin (storage-set "ralph:phase" "idle") "Running.")
          (if (= msg "progress")
            (get-progress)
            (if (starts-with? msg "add task ")
              (add-task (str-concat "task-" (to-string 0)) (str-slice msg 9 (str-length msg)) 50)
              (if (starts-with? msg "read ")
                (let ((path (str-slice msg 5 (str-length msg))))
                  (str-concat "reading:" path))
                (if (starts-with? msg "list ")
                  (str-concat "listing:" (str-slice msg 5 (str-length msg)))
                  (if (starts-with? msg "write ")
                    (let ((rest (str-slice msg 6 (str-length msg))))
                      (begin
                        (storage-set "write-test" rest)
                        (str-concat "Wrote " (to-string (str-length rest)) " bytes")))
                    (str-concat "Unknown: " msg)))))))))))

(define (run input)
  (handle-command input))
