#!/usr/bin/env python3
"""gen-grammar — build the FULL lisp-rlm syntax sheet from source of truth.

Builtin signatures are extracted from helpers.rs doc entries (91+, exact
shapes). Special forms are hand-curated (parser sugar + compiler forms).
Writes scripts/rlm-tasks/policy.lisp (POLICY_ID + GRAMMAR) — regenerable,
never hand-edited again.
"""
import re, os

HERE = os.path.dirname(os.path.abspath(__file__))
DOC_RE = re.compile(r'"([a-z0-9!?*=<>+/_-]+)"(?:\s*\|\s*"[a-z0-9!?*=<>+/_-]+")*\s*=>\s*"([^"\n]+)"')

# Grammar content version. Bump whenever the SHEET TEXT changes semantically
# (not just entry count) so digest policy stats don't lump old/new worlds.
GRAMMAR_V = 3

# ---- grammar variants (dream-searchable dimension) ----
# scripts/rlm-tasks/grammar-variant.json: {"variant": "full"|"lean"|"strings-first"}
#   full          — every builtin with meaning (baseline)
#   lean          — builtins never seen in any trace get bare signatures
#   strings-first — string/collection builtins listed first (attention
#                   primacy for string/list tasks like t2_reverse/t3_fib)
# POLICY_ID suffix: full="", lean="l", strings-first="s" (g3 / g3l / g3s)
import json as _json

VARIANT_FILE = os.path.join(HERE, "rlm-tasks", "grammar-variant.json")
VARIANT_SUFFIX = {"full": "", "lean": "l", "strings-first": "s"}

STRINGY = {"str-concat", "str-join", "str-split", "str-replace", "str-substring",
           "str-length", "str-index-of", "str-trim", "str-upcase", "str-downcase",
           "reverse", "list", "append", "cons", "car", "cdr", "map", "filter",
           "fold-left", "fold-right", "reduce", "nth", "len", "sort", "range"}


def active_variant():
    try:
        return _json.load(open(VARIANT_FILE)).get("variant", "full")
    except Exception:
        return "full"


def used_builtins(docs):
    """Builtin names that appear in any banked trace node (code or error)."""
    import glob as _glob
    names = set()
    pool = _glob.glob(os.path.join(HERE, "..", "data", "rlm", "traces", "*", "*.json")) + \
           _glob.glob(os.path.join(HERE, "..", "data", "rlm", "traces", "*.json"))
    docnames = [n for n, _ in docs]
    for p in pool:
        try:
            w = _json.loads(open(p, "rb").read().decode().replace("\\", "\\\\"))
        except Exception:
            continue
        for n in w.get("nodes", []):
            text = f"{n.get('code', '')} {n.get('out', '')}"
            for nm in docnames:
                if nm in text:
                    names.add(nm)
    return names


def apply_variant(entries, variant, used):
    out = list(entries)
    if variant == "lean":
        out = [(n, d.split(" — ")[0] if n not in used else d) for n, d in out]
    elif variant == "strings-first":
        out.sort(key=lambda e: (0 if e[0] in STRINGY else 1, e[0]))
    return out

SPECIAL_FORMS = [
    ("define fn", "(define (f x y) body...)"),
    ("define var", "(define name value)"),
    ("lambda", "(lambda (x) body)"),
    ("let / let*", "(let ((x 1) (y 2)) body)"),
    ("if", "(if cond then else)"),
    ("begin", "(begin a b c)"),
    ("while", "(while cond body...)"),
    ("dotimes", "(dotimes (i n) body...)  ;; binding is (i n) — ONE paren pair"),
    ("set!", "(set! var expr)"),
    ("try/catch", "(try EXPR (catch e handler))"),
    ("cond", "(cond (test body...) (else body...))"),
    ("quote", "'x  or  (quote x)"),
]

def build():
    src = open(os.path.join(HERE, "..", "src", "helpers.rs")).read()
    docs = DOC_RE.findall(src)
    docs = [(n, d) for n, d in docs if len(d) < 110]
    # dedupe by primary name, keep sorted
    seen, entries = set(), []
    for n, d in docs:
        if n in seen: continue
        seen.add(n); entries.append((n, d))
    entries.sort()
    variant = active_variant()
    used = used_builtins(entries) if variant == "lean" else set()
    entries = apply_variant(entries, variant, used)
    lines = [f"{d}" for _, d in entries]
    special = [f"{name}: {ex}" for name, ex in SPECIAL_FORMS]
    grammar = (
        "Write lisp-rlm code ONLY. FULL SYNTAX SHEET follows. "
        "NO Common Lisp (no loop-for, no incf). Numbers are integers only. "
        "CRITICAL: store your result with (rlm-set answer <value>) — plain (set! x v) "
        "env vars are INVISIBLE outside; then finish with (final true). "
        "Output ONE lisp form.\n\n"
        "SPECIAL FORMS (exact shapes):\n- " + "\n- ".join(special) +
        "\n\nBUILTINS (signature — meaning):\n- " + "\n- ".join(lines)
    )
    import json as _json
    params = _json.load(open(os.path.join(HERE, "rlm-tasks", "policy-params.json")))
    pid = (f"p5-{params['max_iter']}x{params['stop_errs']}-{len(entries)}b"
           f"-g{GRAMMAR_V}{VARIANT_SUFFIX.get(variant, '')}")
    policy = (
        ";; GENERATED by scripts/gen-grammar.py — do not hand-edit GRAMMAR.\n"
        ";; Edit SPECIAL_FORMS in gen-grammar.py or the doc strings in src/helpers.rs.\n"
        ";; Policy knobs (max_iter, stop_errs) come from policy-params.json —\n"
        ";; deployed by the dream layer (rlm-dream.py) via the replay gate.\n"
        f"(define POLICY_ID \"{pid}\")\n"
        f"(define POLICY_MAX_ITER {int(params['max_iter'])})\n"
        f"(define POLICY_STOP_ERRS {int(params['stop_errs'])})\n"
        "(define GRAMMAR\n"
        "  \"" + grammar.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n') + "\")\n"
    )
    out = os.path.join(HERE, "rlm-tasks", "policy.lisp")
    open(out, "w").write(policy)
    print(f"policy.lisp: {len(entries)} builtins + {len(special)} forms → {len(grammar)} chars")

if __name__ == "__main__":
    build()
