#!/usr/bin/env python3
"""gen_bip340_sign.py — emits BIP-340 Schnorr SIGN in raw lisp-rlm.

Reuses the proven core (gen_bip340.py structure, SHA-256 stripped — runtime
`sha256-hash` builtin covers all hashing) and adds:
  - fe-muln: second Montgomery domain mod n (scalar arithmetic)
  - sc-mul-small / sc-add-partial: double-and-add mod n
  - Jacobian point double + mixed add (a=0), lift_x via fe-sqrt
  - bytes32->limbs, words->hex, nonce gen via builtin sha
Output: /tmp/nostr_probe/sign_lib.lisp (library only; driver appended by tests)
"""
import hashlib

LIMB, NL, M = 30, 9, (1 << 30) - 1

p = 2**256 - 2**32 - 977
n = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141
Gx = 0x79BE667EF9DCBBAC55A06295CE870B07029BFCDB2DCE28D959F2815B16F81798
Gy = 0x483ADA7726A3C4655DA4FBFC0E1108A8FD17B448A68554199C47D08FFB10D4B8
R = 1 << 270

def limbs(x, nl=NL):
    return [(x >> (LIMB * i)) & M for i in range(nl)]

def lisp_list(vals):
    return "(list " + " ".join(str(v) for v in vals) + ")"

L = []
def w(s=""):
    L.append(s)

def fe2(fn, a, b):
    return "(%s %s %s)" % (fn, " ".join("(vec-nth %s %d)" % (a, i) for i in range(NL)), b)

def fe2limbs(fn, a_lims, b):
    return "(%s %s %s)" % (fn, " ".join(a_lims),
        " ".join("(vec-nth %s %d)" % (b, i) for i in range(NL)))

def geq_chain(aget, bget, top):
    expr = "0"
    for k in range(top, -1, -1):
        expr = "(if (> %s %s) 1 (if (< %s %s) 0 %s))" % (aget(k), bget(k), aget(k), bget(k), expr)
    return expr

def geq_chain_msb(aget, bget, top):
    expr = "1"
    for k in range(0, top + 1):
        expr = "(if (> %s %s) 1 (if (< %s %s) 0 %s))" % (aget(k), bget(k), aget(k), bget(k), expr)
    return expr

def cond_sub_p_stmts(aget, dst, const_fn):
    stmts = ["(set! g %s)" % geq_chain_msb(aget, lambda k: "(vec-nth (%s 0) %d)" % (const_fn, k), 8)]
    stmts.append("(if (= g 1)")
    stmts.append("  (begin")
    for k in range(9):
        stmts.append("    (set! %sv (+ (- (- %s (vec-nth (%s 0) %d)) %sbr) 1073741824))" % (dst, aget(k), const_fn, k, dst))
        stmts.append("    (set! %shi (shr %sv 30))" % (dst, dst))
        stmts.append("    (set! %sbr (if (= %shi 0) 1 0))" % (dst, dst))
        stmts.append("    (set! %s%d (if (= %sbr 1) %sv (- %sv 1073741824)))" % (dst, k, dst, dst, dst))
    stmts.append("    0)")
    stmts.append("  0)")
    for k in range(10):
        stmts.append("(set! %s%d (if (= g 1) %s%d %s))" % (dst, k, dst, k, aget(k)))
    return stmts

# ═══ constants ═══
w(";; bip340-sign.lisp — generated by gen_bip340_sign.py")
w("(define (c-p _d) %s)" % lisp_list(limbs(p)))
w("(define (c-n _d) %s)" % lisp_list(limbs(n)))
w("(define (c-r2 _d) %s)" % lisp_list(limbs((R * R) % p)))
w("(define (c-onem _d) %s)" % lisp_list(limbs(R % p)))
w("(define (c-pp _d) %s)" % lisp_list(limbs((-pow(p, -1, 1 << 270)) % (1 << 270))))
w("(define (c-npp _d) %s)" % lisp_list(limbs((-pow(n, -1, 1 << 270)) % (1 << 270))))
w("(define (c-nr2 _d) %s)" % lisp_list(limbs((R * R) % n)))
w("(define (c-none _d) %s)" % lisp_list(limbs(R % n)))
w("(define (c-sevenm _d) %s)" % lisp_list(limbs((7 * R) % p)))
w("(define (c-gxm _d) %s)" % lisp_list(limbs((Gx * R) % p)))
w("(define (c-gym _d) %s)" % lisp_list(limbs((Gy * R) % p)))
w("(define (c-d1 _d) %s)" % lisp_list(limbs((p + 1) // 4)))
w("(define (c-pm1 _d) %s)" % lisp_list(limbs(((p - 1) * R) % p)))
w("(define (c-n2 _d) %s)" % lisp_list(limbs(n - 2)))
w("(define (c-zero _d) %s)" % lisp_list([0] * NL))
w()


def guard_cascade(t, maxt=18):
    """2-cell carry ripple (fix_shamod.py, Sep 20): the row-end guard must not
    drop the carry when t+c overflows 30 bits (tN+c overflow was silently lost)."""
    s = f"(if (!= c 0) (begin (set! v (+ t{t} c)) (set! t{t} (band v {M})) (set! c (shr v {LIMB}))"
    t1 = t + 1
    if t1 <= maxt:
        s += f" (if (!= c 0) (begin (set! v (+ t{t1} c)) (set! t{t1} (band v {M})) (set! c (shr v {LIMB}))"
        t2 = t + 2
        if t2 <= maxt:
            s += f" (if (!= c 0) (begin (set! v (+ t{t2} c)) (set! t{t2} (band v {M}))) 0)"
        s += ") 0)"
    s += ") 0)"
    return s

# ═══ fe-mul (REDC mod m) — emitted twice: mod p and mod n ═══
def emit_mulmod(name, const_p, const_pp):
    lines = ["(define (%s x0 x1 x2 x3 x4 x5 x6 x7 x8 y)" % name]
    params = ["(t%d 0)" % i for i in range(19)] + ["(m%d 0)" % i for i in range(NL)]
    params += ["(v 0)", "(c 0)", "(g 0)", "(dbr 0)", "(dhi 0)", "(dv 0)"] + \
              ["(d%d 0)" % k for k in range(10)]
    lines.append("  (let (" + " ".join(params) + ")")
    lines.append("    (begin")
    body = []
    for i in range(NL):
        body.append("(set! c 0)")
        for j in range(NL):
            body.append("(set! v (+ (+ t%d (wrap-mul x%d (vec-nth y %d))) c))" % (i + j, i, j))
            body.append("(set! t%d (band v %d))" % (i + j, M))
            body.append("(set! c (shr v %d))" % LIMB)
        body.append(guard_cascade(i + NL))
    for i in range(NL):
        body.append("(set! c 0)")
        for j in range(NL - i):
            body.append("(set! v (+ (+ m%d (wrap-mul t%d (vec-nth (%s 0) %d))) c))" % (i + j, i, const_pp, j))
            body.append("(set! m%d (band v %d))" % (i + j, M))
            body.append("(set! c (shr v %d))" % LIMB)
    for i in range(NL):
        body.append("(set! c 0)")
        for j in range(NL):
            body.append("(set! v (+ (+ t%d (wrap-mul m%d (vec-nth (%s 0) %d))) c))" % (i + j, i, const_p, j))
            body.append("(set! t%d (band v %d))" % (i + j, M))
            body.append("(set! c (shr v %d))" % LIMB)
        body.append(guard_cascade(i + NL))
    for rnd in range(2):
        aget = (lambda k: ("t%d" % (9 + k))) if rnd == 0 else (lambda k: "d%d" % k)
        body.extend(cond_sub_p_stmts(aget, "d", const_p))
    body.append("(list d0 d1 d2 d3 d4 d5 d6 d7 d8)")
    lines.extend("    " + b for b in body)
    lines.append(")))")
    w("\n".join(lines))
    w()

emit_mulmod("fe-mul", "c-p", "c-pp")     # field mod p
emit_mulmod("fe-muln", "c-n", "c-npp")   # scalars mod n

# ═══ fe-add / fe-sub (mod p) ═══
def emit_addsub(name, is_add, const_p="c-p"):
    lines = ["(define (%s a0 a1 a2 a3 a4 a5 a6 a7 a8 b)" % name]
    params = ["(v 0)", "(c 0)", "(br 0)", "(hi 0)", "(g 0)", "(dbr 0)", "(dhi 0)", "(dv 0)"]
    if not is_add:
        params += ["(t%d 0)" % i for i in range(10)]
    params += ["(d%d 0)" % k for k in range(10)]
    lines.append("  (let (" + " ".join(params) + ")")
    lines.append("    (begin")
    lines.append("    (set! c 0)")
    for i in range(NL):
        src_b = "(vec-nth b %d)" % i if is_add else "(vec-nth (%s 0) %d)" % (const_p, i)
        lines.append("    (set! v (+ (+ a%d %s) c))" % (i, src_b))
        lines.append("    (set! d%d (band v %d))" % (i, M))
        lines.append("    (set! c (shr v %d))" % LIMB)
    if is_add:
        lines.append("    (set! d9 c)")
    else:
        lines.append("    (set! t9 c)")
        lines.append("    (set! br 0)")
        for i in range(NL):
            lines.append("    (set! v (+ (- (- t%d (vec-nth b %d)) br) 1073741824))" % (i, i))
            lines.append("    (set! hi (shr v 30))")
            lines.append("    (set! br (if (= hi 0) 1 0))")
            lines.append("    (set! d%d (if (= br 1) v (- v 1073741824)))" % i)
        lines.append("    (set! d9 (- t9 br))")
    lines.extend("    " + s for s in cond_sub_p_stmts(lambda k: "d%d" % k, "d", const_p))
    lines.append("    (list d0 d1 d2 d3 d4 d5 d6 d7 d8)")
    lines.append(")))")
    w("\n".join(lines))
    w()

emit_addsub("fe-add", True)
# fe-sub: a − b = a + b·(p−1) (mod p) — composed ONLY from fe-add/fe-mul,
# the two primitives bit-verified against the python oracle under compiled
# wasm. The direct borrow-chain emitter (below, unused) produces scrambled
# limbs in the inlayer build; kept for reference, not emitted.
w("(define (fe-sub a0 a1 a2 a3 a4 a5 a6 a7 a8 b)")
w("  (fe-add a0 a1 a2 a3 a4 a5 a6 a7 a8")
w("          (fe-mul (vec-nth b 0) (vec-nth b 1) (vec-nth b 2) (vec-nth b 3)")
w("                  (vec-nth b 4) (vec-nth b 5) (vec-nth b 6) (vec-nth b 7)")
w("                  (vec-nth b 8) (c-pm1 0))))")
w()

# ═══ fe-eq / fe-zero? ═══
expr = "(= a8 b8)"
for i in range(NL - 2, -1, -1):
    expr = "(and (= a%d b%d) %s)" % (i, i, expr)
bexpr = expr
for i in range(NL):
    bexpr = bexpr.replace("(= a%d b%d)" % (i, i), "(= a%d (vec-nth b %d))" % (i, i))
w("(define (fe-eq a0 a1 a2 a3 a4 a5 a6 a7 a8 b)")
w("  (if %s 1 0))" % bexpr)
zexpr = "(= a8 0)"
for i in range(NL - 2, -1, -1):
    zexpr = "(and (= a%d 0) %s)" % (i, zexpr)
w("(define (fe-zero? a0 a1 a2 a3 a4 a5 a6 a7 a8)")
w("  (if %s 1 0))" % zexpr)
w()

# ═══ scalar geq / ops mod n ═══
w("(define (sc-geq-n a0 a1 a2 a3 a4 a5 a6 a7 a8)")
w("  %s)" % geq_chain_msb(lambda k: "a%d" % k, lambda k: "(vec-nth (c-n 0) %d)" % k, 8))
w()

def emit_sc_reduce():
    lines = ["(define (sc-reduce a0 a1 a2 a3 a4 a5 a6 a7 a8)"]
    params = ["(v 0)", "(hi 0)", "(br 0)", "(g 0)"] + ["(d%d 0)" % i for i in range(NL)]
    lines.append("  (let (" + " ".join(params) + ")")
    lines.append("    (begin")
    lines.append("    (set! g %s)" % geq_chain_msb(lambda k: "a%d" % k, lambda k: "(vec-nth (c-n 0) %d)" % k, 8))
    lines.append("    (if (= g 1)")
    lines.append("      (begin")
    lines.append("      (set! br 0)")
    for i in range(NL):
        lines.append("      (set! v (+ (- (- a%d (vec-nth (c-n 0) %d)) br) 1073741824))" % (i, i))
        lines.append("      (set! hi (shr v 30))")
        lines.append("      (set! br (if (= hi 0) 1 0))")
        lines.append("      (set! d%d (if (= br 1) v (- v 1073741824)))" % i)
    lines.append("      0)")
    lines.append("      0)")
    for i in range(NL):
        lines.append("    (set! d%d (if (= g 1) d%d a%d))" % (i, i, i))
    lines.append("    (list d0 d1 d2 d3 d4 d5 d6 d7 d8)")
    lines.append(")))")
    w("\n".join(lines))
    w()

emit_sc_reduce()

def emit_sc_n_minus():
    lines = ["(define (sc-n-minus a0 a1 a2 a3 a4 a5 a6 a7 a8)"]
    params = ["(v 0)", "(hi 0)", "(br 0)"] + ["(d%d 0)" % i for i in range(NL)]
    lines.append("  (let (" + " ".join(params) + ")")
    lines.append("    (begin")
    lines.append("    (set! br 0)")
    for i in range(NL):
        lines.append("    (set! v (+ (- (- (vec-nth (c-n 0) %d) a%d) br) 1073741824))" % (i, i))
        lines.append("    (set! hi (shr v 30))")
        lines.append("    (set! br (if (= hi 0) 1 0))")
        lines.append("    (set! d%d (if (= br 1) v (- v 1073741824)))" % i)
    lines.append("    (list d0 d1 d2 d3 d4 d5 d6 d7 d8)")
    lines.append(")))")
    w("\n".join(lines))
    w()

emit_sc_n_minus()

# k + s mod n (both < n, so sum < 2n: add then single conditional reduce)
def emit_sc_addmod():
    lines = ["(define (sc-addmod a0 a1 a2 a3 a4 a5 a6 a7 a8 b)"]
    params = ["(v 0)", "(c 0)", "(g 0)", "(dbr 0)", "(dhi 0)", "(dv 0)"] + ["(d%d 0)" % i for i in range(10)] + ["(r%d 0)" % i for i in range(NL)]
    lines.append("  (let (" + " ".join(params) + ")")
    lines.append("    (begin")
    lines.append("    (set! c 0)")
    for i in range(NL):
        lines.append("    (set! v (+ (+ a%d (vec-nth b %d)) c))" % (i, i))
        lines.append("    (set! d%d (band v %d))" % (i, M))
        lines.append("    (set! c (shr v %d))" % LIMB)
    lines.append("    (set! d9 c)")
    lines.extend("    " + s for s in cond_sub_p_stmts(lambda k: "d%d" % k, "d", "c-n"))
    lines.append("    (list d0 d1 d2 d3 d4 d5 d6 d7 d8)")
    lines.append(")))")
    w("\n".join(lines))
    w()

emit_sc_addmod()

# ═══ fe-sqrt (x^d1, montgomery in/out) ═══
w("(define (fe-sqrt x0 x1 x2 x3 x4 x5 x6 x7 x8)")
w("  (let ((x (list x0 x1 x2 x3 x4 x5 x6 x7 x8)))")
w("    (loop ((acc (c-onem 0)) (i 254))")
w("      (let ((a2 %s))" % fe2("fe-mul", "acc", "acc"))
w("        (let ((a3 (if (= (band (shr (vec-nth (c-d1 0) (/ i 30)) (mod i 30)) 1) 1)")
w("                      %s a2)))" % fe2("fe-mul", "a2", "x"))
w("          (if (= i 0) a3 (recur a3 (- i 1))))))))")
w()

# ═══ conversions: fe <-> big-endian words ═══
def word_expr(k, prefix):
    parts = []
    for i in range(NL):
        shift = 32 * k - 30 * i
        if shift == 0:
            parts.append("(band %s%d 4294967295)" % (prefix, i))
        elif 0 < shift < 30:
            parts.append("(shr %s%d %d)" % (prefix, i, shift))
        elif -32 < shift < 0:
            # compiled wasm: negative shift counts mask mod 64; positive-count
            # shl of the pre-masked low bits is safe (count < 30, value < 2^30)
            off = -shift
            parts.append("(shl (band %s%d 4294967295) %d)" % (prefix, i, off))
    return parts[0] if len(parts) == 1 else "(band (+ %s) 4294967295)" % " ".join(parts)

w("(define (fe-words-be a)")
w("  (let (%s)" % " ".join("(a%d (vec-nth a %d))" % (i, i) for i in range(NL)))
w("    (list %s)))" % " ".join(word_expr(k, "a") for k in range(7, -1, -1)))
w()

def limb_from_words(k):
    parts = []
    lk = 30 * k
    for wi in range(8):
        lo = 32 * (7 - wi)
        if lo < lk + LIMB and lo + 32 > lk:
            shift = lk - lo
            if shift == 0:
                parts.append("(band w%d %d)" % (wi, M))
            elif shift > 0:
                # right-shift; mask keeps each summed piece strictly 30-bit
                # (boundary case shift==30: w7's top 2 bits into limb 1)
                parts.append("(band (shr w%d %d) %d)" % (wi, shift, M))
            else:
                # compiled wasm: negative shift counts mask mod 64 (wrong
                # direction); pre-mask kept bits, positive-count shl, sum.
                off = -shift
                parts.append("(shl (band w%d %d) %d)" % (wi, (1 << (LIMB - off)) - 1, off))
    return parts[0] if len(parts) == 1 else "(+ %s)" % " ".join(parts)

w("(define (words-limbs w0 w1 w2 w3 w4 w5 w6 w7)")
w("  (list %s))" % " ".join(limb_from_words(k) for k in range(NL)))
w()

open("/tmp/nostr_probe/sign_lib.lisp", "w").write("\n".join(L) + "\n")
print("LIB emitted:", len(L), "lines")
