#!/usr/bin/env python3
"""rlm-qlearn — tabular Q-learning over escalation actions (Dream v3).

Mines banked trace worlds for (state, action) decisions recorded per node
by the runtime's Q-layer, applies Q-updates, and regenerates
scripts/rlm-tasks/q-table.lisp for the runtime to consult.

Reward: -0.05 per step, +1.0 terminal bonus if the world completed,
+0.05 shaping for distinct code (exploration bonus).
γ=0.85, α=0.25. Worlds without s/a fields (pre-Q traces) are skipped.

The hand-coded ladder remains the fallback for unseen states and is
itself an action ('ladder') the learner can prefer. No LLM, no human.
"""
import json, os, glob, random

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TRACES = os.path.join(REPO, "data", "rlm", "traces")
QOUT = os.path.join(REPO, "scripts", "rlm-tasks", "q-table.lisp")
LEDGER = os.path.join(REPO, "data", "rlm", "dream", "ledger.jsonl")

ACTIONS = ["none", "temp08", "temp10", "doc", "hint", "ban",
           "budget2", "stop", "ladder"]
ALPHA, GAMMA = 0.25, 0.85
STEP_R, SOLVE_R, FAIL_R, NOVEL_R = -0.05, 1.0, -0.2, 0.05


def load_q(path=QOUT.replace("q-table.lisp", "q-values.json")):
    if os.path.exists(path):
        return json.load(open(path))
    return {}


def save_q(q, path=QOUT.replace("q-table.lisp", "q-values.json")):
    json.dump(q, open(path, "w"), indent=0)


def episodes():
    import hashlib
    seen = set()
    paths = glob.glob(os.path.join(TRACES, "*", "*.json")) + \
        glob.glob(os.path.join(TRACES, "*.json"))
    for p in paths:
        raw = open(p, "rb").read()
        h = hashlib.sha256(raw).hexdigest()
        if h in seen:  # dated copy + base file have identical content
            continue
        seen.add(h)
        try:
            w = json.loads(raw.decode().replace("\\", "\\\\"))
        except Exception:
            continue
        nodes = w.get("nodes", [])
        if not nodes or not all("s" in n and "a" in n for n in nodes):
            continue  # pre-Q world
        yield w, nodes


def learn(q):
    visits = {}
    for w, nodes in episodes():
        completed = bool(w.get("completed"))
        seen_codes = set()
        T = len(nodes)
        for t, n in enumerate(nodes):
            s, a = n["s"], n["a"]
            if a not in ACTIONS:
                continue
            q.setdefault(s, {x: 0.0 for x in ACTIONS})
            visits[s] = visits.get(s, 0) + 1
            novel = n.get("code", "") not in seen_codes
            seen_codes.add(n.get("code", ""))
            if t == T - 1:
                r = STEP_R + (SOLVE_R if completed else FAIL_R) + \
                    (NOVEL_R if novel else 0)
                target = r
            else:
                r = STEP_R + (NOVEL_R if novel else 0)
                s2 = nodes[t + 1].get("s", "")
                nxt = q.get(s2, {})
                target = r + GAMMA * max([nxt.get(x, 0.0) for x in ACTIONS])
            q[s][a] += ALPHA * (target - q[s][a])
    return q, visits


def write_lisp(q, visits):
    lines = [
        ";; GENERATED by scripts/rlm-qlearn.py — do not hand-edit.",
        ";; Learned escalation policy (tabular Q). Unseen states fall",
        ";; back to 'ladder (the hand-coded bootstrap composite).",
        "(define Q-ENABLED true)",
        "(define Q-EPS 10)",
        "(define Q-TABLE (list",
    ]
    for s in sorted(q, key=lambda x: -visits.get(x, 0)):
        acts = sorted(q[s].items(), key=lambda kv: -kv[1])
        row = "  (list \"%s\" (list %s))" % (
            s, " ".join("(list '%s %s)" % (a, round(v, 4)) for a, v in acts))
        lines.append(row)
    lines.append("))")
    open(QOUT, "w").write("\n".join(lines) + "\n")


def main():
    q = load_q()
    q, visits = learn(q)
    n_states = len(q)
    write_lisp(q, visits)
    save_q(q)
    with open(LEDGER, "a") as f:
        f.write(json.dumps({"event": "qlearn", "ts": __import__("time").time(),
                            "states": n_states,
                            "episodes_seen": sum(1 for _ in episodes())}) + "\n")
    print(f"qlearn: {n_states} states, table written")


if __name__ == "__main__":
    main()
