// AFP CLMM port — TS twin (generated by gen_ts.py).
// Edit gen_ts.py, not this file — every name regenerates.
// u128 values are decimal STRINGS; all arithmetic via u128* fns (money-sealed).
// grug naming: GRID_LO = grid floor, CELL_TOP_i = grid top of cell i,
// CELL_L_i = liquidity in cell i, CELL_Q_i = gross units cell i eats per
// unit price, sqp = current sqrt-price. Keys ("s:...") are wire format —
// do NOT rename keys.

function sget(k: string): string {
  return near.storageGet(k) ?? "0";
}
function sput(k: string, v: string): void {
  near.storageSet(k, v);
}
function fail(m: string): void {
  near.log(m);
  near.abort(m);
}
// Splitter: AFP pool_combination optimality on DIFFERENT grids.
// p* equalizes the legs' ending price: qA(p*) + qB(p*) = y over merged
// breakpoints; y1 = qA(p*), leg B gets y-y1. Floors mirror the oracle.
const GRID_LO = "1000000000";
// merged-curve constants (pools A+B over shared breakpoints):
const ZONE1_Y = "130391173520561685055167000000000";   // deposit size that exactly fills zone 1
const ZONE2_Y = "220661985957873620862590000000000";   // deposit size that fills zones 1+2
const SUMQ_0 = "130391173520561685055167";     // merged Q on segment 0
const SUMQ_1 = "90270812437311935807423";     // merged Q on segment 1
const SUMQ_2 = "150451354062186559679038";     // merged Q on segment 2
const OUT_ZONE1 = "100300902708124373119359000000000";  // pool-A out when deposit = ZONE1_Y
const OUT_ZONE2 = "160481444332998996990974000000000";  // pool-A out when deposit = ZONE2_Y
const POOLA_Q1 = "100300902708124373119359"; // pool A gross-per-price, zone 1
const POOLA_Q2 = "60180541624874623871615"; // pool A gross-per-price, zone 2
const TGAS = 50000000000;
const POOLA = "pa.clmm.test.near";
const POOLB = "pb.clmm.test.near";
const SELF = "splt.clmm.test.near";
const SWAP_ARGS = '{"min_out":"0"}';

// equalized split: zone-solve p*, y1 = pool-A share of y (muldiv floors, mirrored)
function y1for(y: string): string {
  if (u128.lt(y, ZONE1_Y)) {
    return u128MulDiv(POOLA_Q1, y, SUMQ_0);
  }
  if (u128.lt(y, ZONE2_Y)) {
    return u128.add(OUT_ZONE1, u128MulDiv(POOLA_Q2, u128.sub(y, ZONE1_Y), SUMQ_1));
  }
  return u128.add(OUT_ZONE2, u128MulDiv(POOLA_Q2, u128.sub(y, ZONE2_Y), SUMQ_2));
}

export function split(): string {
  const deposit: Yocto = near.attachedDepositU128();
  const who = near.predecessorAccountId();
  if (u128.eq(deposit, "0")) { fail("ERR_ZERO"); }
  if (u128.eq(y1for(deposit), "0")) { fail("ERR_DUST"); }
  const split_a_raw = y1for(deposit);
  const split_a = u128.lt(deposit, split_a_raw) ? deposit : split_a_raw;
  const amount_b = u128.sub(deposit, split_a);
  const cb = '{"who":' + near.jsonQuote(who) + '}';
  near.log("split a=" + split_a);
  sput("sp:who", who);
  const prom_a = near.promiseCreate(POOLA, "swap", SWAP_ARGS, split_a, TGAS);
  near.promiseThen(prom_a, SELF, "on_a", cb, "0", TGAS);
  const prom_b = near.promiseCreate(POOLB, "swap", SWAP_ARGS, amount_b, TGAS);
  near.promiseThen(prom_b, SELF, "on_b", cb, "0", TGAS);
  return "queued";
}

function credit(failTag: string): void {
  const who = sget("sp:who");
  const out = near.promiseResult(0);
  if (out === "") { fail(failTag); }
  const pk = "paid:" + who;
  sput(pk, u128.add(sget(pk), out));
  near.log("leg out=" + out);
}

export function on_a(): string {
  credit("ERR_LEG_A");
  return near.promiseResult(0);
}

export function on_b(): string {
  credit("ERR_LEG_B");
  return near.promiseResult(0);
}

export function get_paid(): string {
  return sget("paid:" + near.predecessorAccountId());
}
