// AFP CLMM port — TS twin (generated by gen_ts.py).
// Edit gen_ts.py, not this file — every name regenerates.
// u128 values are decimal STRINGS; all arithmetic via u128* fns (money-sealed).
// grug naming: GRID_LO = grid floor, CELL_TOP_i = grid top of cell i,
// CELL_L_i = liquidity in cell i, CELL_Q_i = gross units cell i eats per
// unit price, sqp = current sqrt-price. Keys ("s:...") are wire format —
// do NOT rename keys.

function sget(k: string): string {
  return near.storageGet(k) ?? "0";
}
function sput(k: string, v: string): void {
  near.storageSet(k, v);
}
function fail(m: string): void {
  near.log(m);
  near.abort(m);
}
const GRID_LO = "1000000000";
const CELL_TOP_1 = "2000000000";
const CELL_TOP_2 = "4000000000";
const CELL_L_1 = "40000000000000000000000";
const CELL_L_2 = "90000000000000000000000";
const CELL_Q_1 = "40201005025125628140704";
const CELL_Q_2 = "90452261306532663316583";

// one cell step: price_move = min(y_left, cell_cap)/cell_q (floor);
// only price_move*cell_q units consumed; price_move=0 cannot advance
// price (dust stays for refund).
function step(cell_l: string, cell_q: string, cell_top: string): void {
  const sqp = sget("s:sqp");
  const y_left = sget("s:y");
  const out_total = sget("s:out");
  const cell_left = u128.sub(cell_top, sqp);
  const cell_cap = u128MulDiv(cell_q, cell_left, "1");
  const consumed = u128.lt(cell_cap, y_left) ? cell_cap : y_left;
  const price_move = u128.div(consumed, cell_q);
  const units_used = u128MulDiv(price_move, cell_q, "1");
  const price_next = u128.add(sqp, price_move);
  const amount_out = u128.eq(price_move, "0") ? "0"
    : u128MulDiv(cell_l, price_move, u128MulDiv(sqp, price_next, "1"));
  sput("s:out", u128.add(out_total, amount_out));
  sput("s:y", u128.sub(y_left, units_used));
  sput("s:sqp", price_next);
}

// walk: cell dispatch by sqp, dust guard `y_left < CELL_Q_i` per cell (lisp mirror)
function walk(): void {
  let guard = 0;
  while (u128.gt(sget("s:y"), "0")) {
    if (!u128.lt(sget("s:sqp"), CELL_TOP_2)) {
      break;
    }
    if (u128.lt(sget("s:sqp"), CELL_TOP_1)) {
      if (u128.lt(sget("s:y"), CELL_Q_1)) { break; }
      step(CELL_L_1, CELL_Q_1, CELL_TOP_1);
    } else if (u128.lt(sget("s:sqp"), CELL_TOP_2)) {
      if (u128.lt(sget("s:y"), CELL_Q_2)) { break; }
      step(CELL_L_2, CELL_Q_2, CELL_TOP_2);
    }
    guard = guard + 1;
    if (guard > 1000) { break; }
  }
}

export function swap(): string {
  const deposit: Yocto = near.attachedDepositU128();
  const caller = near.predecessorAccountId();
  const min_out = near.jsonGetStr("min_out") ?? "0";
  const start_raw = near.jsonGetStr("start") ?? "0";
  const start = u128.eq(start_raw, "0") ? GRID_LO : start_raw;
  if (u128.eq(deposit, "0")) { fail("ERR_ZERO"); }
  if (u128.lt(start, GRID_LO)) { fail("ERR_START"); }
  sput("s:sqp", start);
  sput("s:y", deposit);
  sput("s:out", "0");
  walk();
  const out = sget("s:out");
  const y_left = sget("s:y");
  const paid_key = "paid:" + caller;
  if (u128.lt(out, min_out)) { fail("ERR_SLIP"); }
  sput(paid_key, u128.add(sget(paid_key), out));
  sput("left:" + caller, y_left);
  near.log("swap out=" + out);
  return out;
}

export function get_paid(): string {
  return sget("paid:" + near.predecessorAccountId());
}

