#!/usr/bin/env python3
"""AFP CLMM port — TypeScript twins of the 9 lisp contracts (gen.py/gen3.py).

Templates (mirrors the lisp floor-for-floor; probe /tmp/tsprobe proven):
  POOL_TS   — N-cell while-walk grid pool (pa pb pd pc n1 n2 + pj's body)
  SPLT_TS   — zone-form equalized splitter (splt)
  SPLT3_TS  — 48-iter flat binary-search N-pool splitter (splt3)
Dialect rules learned via probe:
  * u128 predicates are REAL bools — use directly in if/while/ternary
  * 3-arg muldiv is the FREE fn u128MulDiv(a,b,d) (u128.mulDiv does NOT exist)
  * while/break/let-reassign/ternary all compile; no for-loops used
  * NO loop-carried u128-string mutation when 2+ values interlock
    (lo,hi <- mid <- (lo+hi): writes silently stop sticking after iter 1 —
    probe /tmp/bsprobe; unroll into unique-named const stages instead,
    same medicine as the lisp let* chain)
Deltas vs lisp twins (mock-visible): exports use underscores (get_paid);
promise-then callback names are on_a/on_b/on0.. (identifiers).
"""
import json
import os

import sys as _sys, os as _os; _sys.path.insert(0, _os.path.dirname(_os.path.dirname(_os.path.abspath(__file__))))
HERE = os.path.dirname(os.path.abspath(__file__))
sys_path = os.path
import sys
sys.path.insert(0, HERE)
import gen   # noqa: E402  (constants + Qceil + union_fee_chain)
import gen3  # noqa: E402  (G3, LIQS, QQ, CAPS, YS3)

TS = os.path.join(HERE, "ts")
TR = "trader.test.near"

# ── helpers shared by every template ────────────────────────────────────────
PRELUDE = """// AFP CLMM port — TS twin (generated by gen_ts.py).
// Edit gen_ts.py, not this file — every name regenerates.
// u128 values are decimal STRINGS; all arithmetic via u128* fns (money-sealed).
// grug naming: GRID_LO = grid floor, CELL_TOP_i = grid top of cell i,
// CELL_L_i = liquidity in cell i, CELL_Q_i = gross units cell i eats per
// unit price, sqp = current sqrt-price. Keys ("s:...") are wire format —
// do NOT rename keys.

function sget(k: string): string {
  return near.storageGet(k) ?? "0";
}
function sput(k: string, v: string): void {
  near.storageSet(k, v);
}
function fail(m: string): void {
  near.log(m);
  near.abort(m);
}
"""

STEP_TS = """// one cell step: price_move = min(y_left, cell_cap)/cell_q (floor);
// only price_move*cell_q units consumed; price_move=0 cannot advance
// price (dust stays for refund).
function step(cell_l: string, cell_q: string, cell_top: string): void {
  const sqp = sget("s:sqp");
  const y_left = sget("s:y");
  const out_total = sget("s:out");
  const cell_left = u128.sub(cell_top, sqp);
  const cell_cap = u128MulDiv(cell_q, cell_left, "1");
  const consumed = u128.lt(cell_cap, y_left) ? cell_cap : y_left;
  const price_move = u128.div(consumed, cell_q);
  const units_used = u128MulDiv(price_move, cell_q, "1");
  const price_next = u128.add(sqp, price_move);
  const amount_out = u128.eq(price_move, "0") ? "0"
    : u128MulDiv(cell_l, price_move, u128MulDiv(sqp, price_next, "1"));
  sput("s:out", u128.add(out_total, amount_out));
  sput("s:y", u128.sub(y_left, units_used));
  sput("s:sqp", price_next);
}
"""

POOL_BODY = """
{step}
// walk: cell dispatch by sqp, dust guard `y_left < CELL_Q_i` per cell (lisp mirror)
function walk(): void {{
  let guard = 0;
  while (u128.gt(sget("s:y"), "0")) {{
    if (!u128.lt(sget("s:sqp"), CELL_TOP_{{nc}})) {{
      break;
    }}
{arms}
    guard = guard + 1;
    if (guard > 1000) {{ break; }}
  }}
}}

export function swap(): string {{
  const deposit: Yocto = near.attachedDepositU128();
  const caller = near.predecessorAccountId();
  const min_out = near.jsonGetStr("min_out") ?? "0";
  const start_raw = near.jsonGetStr("start") ?? "0";
  const start = u128.eq(start_raw, "0") ? GRID_LO : start_raw;
  if (u128.eq(deposit, "0")) {{ fail("ERR_ZERO"); }}
  if (u128.lt(start, GRID_LO)) {{ fail("ERR_START"); }}
  sput("s:sqp", start);
  sput("s:y", deposit);
  sput("s:out", "0");
  walk();
  const out = sget("s:out");
  const y_left = sget("s:y");
  const paid_key = "paid:" + caller;
  if (u128.lt(out, min_out)) {{ fail("ERR_SLIP"); }}
  sput(paid_key, u128.add(sget(paid_key), out));
  sput("left:" + caller, y_left);
  near.log("swap out=" + out);
  return out;
}}

export function get_paid(): string {{
  return sget("paid:" + near.predecessorAccountId());
}}
{extra}
"""

FEE_EXTRA = """
const FEE_SCALE = "1000000000000000";
const FEE_NUM = "{fh0}";
const FEE_DEN = "{fd0}";

export function get_fee(): string {{
  return u128MulDiv(FEE_NUM, FEE_SCALE, FEE_DEN);
}}
"""


def pool_ts(name, grid, Ls, Qs, extra=""):
    n = len(Ls)
    assert len(grid) == n + 1 and len(Qs) == n, f"{name}: grid/L/Q shape"
    cl = ['const GRID_LO = "%s";' % grid[0]]
    cl += [f'const CELL_TOP_{i} = "{grid[i]}";' for i in range(1, n + 1)]
    cl += [f'const CELL_L_{i} = "{Ls[i - 1]}";' for i in range(1, n + 1)]
    cl += [f'const CELL_Q_{i} = "{Qs[i - 1]}";' for i in range(1, n + 1)]
    consts = "\n".join(cl) + "\n"
    body = (POOL_BODY.replace("{{", "{").replace("}}", "}")
            .replace("{step}", STEP_TS).replace("{extra}", extra))
    body = body.replace("{nc}", str(n)).replace("{arms}", _walk_arms(n))
    return write(name, PRELUDE + consts + body)


def _walk_arms(n):
    """Cell-dispatch arms: arm i active when sqp < G{i+1} (lisp mirror)."""
    out = []
    for i in range(n):
        head = "if" if i == 0 else "} else if"
        out.append(f'    {head} (u128.lt(sget("s:sqp"), CELL_TOP_{i + 1})) {{')
        out.append(f'      if (u128.lt(sget("s:y"), CELL_Q_{i + 1})) {{ break; }}')
        out.append(f'      step(CELL_L_{i + 1}, CELL_Q_{i + 1}, CELL_TOP_{i + 1});')
    out.append("    }")
    return "\n".join(out)


def write(name, src):
    import paths
    acct = name[:-3] if name.endswith("-ts") else name  # pa-ts -> pa
    d = paths.ts_dir(acct)
    os.makedirs(d, exist_ok=True)
    with open(os.path.join(d, "main.ts"), "w") as f:
        f.write(src)
    with open(os.path.join(d, "near.json"), "w") as f:
        json.dump({"name": name, "src": "main.ts",
                   "output": f"target/{paths.MAP[acct][1]}-ts.wasm"}, f)
    print("wrote", d)
    return d


# ── splt: zone-form equalized splitter (lisp splitter_src mirror) ───────────
def splt_ts():
    GA, GB, QA, QB = gen.GA, gen.GB, gen.QA, gen.QB
    w1, w2 = GA[1] - GA[0], GB[1] - GA[1]
    RS0, RS1, RS2 = QA[0] + QB[0], QA[1] + QB[0], QA[1] + QB[1]
    CUM1 = RS0 * w1
    YA1 = QA[0] * w1
    CUM2 = CUM1 + RS1 * w2
    YA2 = YA1 + QA[1] * w2
    src = PRELUDE + f"""// Splitter: AFP pool_combination optimality on DIFFERENT grids.
// p* equalizes the legs' ending price: qA(p*) + qB(p*) = y over merged
// breakpoints; y1 = qA(p*), leg B gets y-y1. Floors mirror the oracle.
const GRID_LO = "{GA[0]}";
// merged-curve constants (pools A+B over shared breakpoints):
const ZONE1_Y = "{CUM1}";   // deposit size that exactly fills zone 1
const ZONE2_Y = "{CUM2}";   // deposit size that fills zones 1+2
const SUMQ_0 = "{RS0}";     // merged Q on segment 0
const SUMQ_1 = "{RS1}";     // merged Q on segment 1
const SUMQ_2 = "{RS2}";     // merged Q on segment 2
const OUT_ZONE1 = "{YA1}";  // pool-A out when deposit = ZONE1_Y
const OUT_ZONE2 = "{YA2}";  // pool-A out when deposit = ZONE2_Y
const POOLA_Q1 = "{QA[0]}"; // pool A gross-per-price, zone 1
const POOLA_Q2 = "{QA[1]}"; // pool A gross-per-price, zone 2
const TGAS = 50000000000;
const POOLA = "pa.clmm.test.near";
const POOLB = "pb.clmm.test.near";
const SELF = "splt.clmm.test.near";
const SWAP_ARGS = '{{"min_out":"0"}}';

// equalized split: zone-solve p*, y1 = pool-A share of y (muldiv floors, mirrored)
function y1for(y: string): string {{
  if (u128.lt(y, ZONE1_Y)) {{
    return u128MulDiv(POOLA_Q1, y, SUMQ_0);
  }}
  if (u128.lt(y, ZONE2_Y)) {{
    return u128.add(OUT_ZONE1, u128MulDiv(POOLA_Q2, u128.sub(y, ZONE1_Y), SUMQ_1));
  }}
  return u128.add(OUT_ZONE2, u128MulDiv(POOLA_Q2, u128.sub(y, ZONE2_Y), SUMQ_2));
}}

export function split(): string {{
  const deposit: Yocto = near.attachedDepositU128();
  const who = near.predecessorAccountId();
  if (u128.eq(deposit, "0")) {{ fail("ERR_ZERO"); }}
  if (u128.eq(y1for(deposit), "0")) {{ fail("ERR_DUST"); }}
  const split_a_raw = y1for(deposit);
  const split_a = u128.lt(deposit, split_a_raw) ? deposit : split_a_raw;
  const amount_b = u128.sub(deposit, split_a);
  const cb = '{{"who":' + near.jsonQuote(who) + '}}';
  near.log("split a=" + split_a);
  sput("sp:who", who);
  const prom_a = near.promiseCreate(POOLA, "swap", SWAP_ARGS, split_a, TGAS);
  near.promiseThen(prom_a, SELF, "on_a", cb, "0", TGAS);
  const prom_b = near.promiseCreate(POOLB, "swap", SWAP_ARGS, amount_b, TGAS);
  near.promiseThen(prom_b, SELF, "on_b", cb, "0", TGAS);
  return "queued";
}}

function credit(failTag: string): void {{
  const who = sget("sp:who");
  const out = near.promiseResult(0);
  if (out === "") {{ fail(failTag); }}
  const pk = "paid:" + who;
  sput(pk, u128.add(sget(pk), out));
  near.log("leg out=" + out);
}}

export function on_a(): string {{
  credit("ERR_LEG_A");
  return near.promiseResult(0);
}}

export function on_b(): string {{
  credit("ERR_LEG_B");
  return near.promiseResult(0);
}}

export function get_paid(): string {{
  return sget("paid:" + near.predecessorAccountId());
}}
"""
    return write("splt-ts", src)


# ── splt3: 48-iter binary search N-pool splitter (gen3 mirror) ──────────────
def splt3_ts():
    G3, QQ, W3 = gen3.G3, gen3.QQ, gen3.W3
    caps = gen3.CAPS
    accts = ("pa.clmm.test.near", "n1.clmm.test.near", "n2.clmm.test.near")
    bsearch = _bsearch_stages()  # BEFORE the f-string: {bsearch} interpolates
    src = PRELUDE + f"""// splt3: N-pool composition (N=3, shared grid, fee {gen.NUM}/{gen.DEN}).
// Net is concave in y => optimum EQUALIZES ENDING PRICE p*:
//   sum_k qgross_k(p*) = y,  y_k = min(cap_k, qgross_k(p*)).
// 48-stage unrolled binary search (see NOTE); sums muldiv-free (mdiv by "1").
const GRID_LO = "{G3[0]}";
const GRID_MID = "{G3[1]}";
const GRID_HI = "{G3[2]}";
const CELL_W_1 = "{W3[0]}";   // price width of zone 1 (below mid)
const CELL_W_2 = "{W3[1]}";   // price width of zone 2 (above mid)
const POOL_CAP_0 = "{caps[0]}";
const POOL_CAP_1 = "{caps[1]}";
const POOL_CAP_2 = "{caps[2]}";
const Q0_LO = "{QQ[0][0]}";   // pool 0 gross-per-price, zone 1
const Q0_HI = "{QQ[0][1]}";   // pool 0 gross-per-price, zone 2
const Q1_LO = "{QQ[1][0]}";
const Q1_HI = "{QQ[1][1]}";
const Q2_LO = "{QQ[2][0]}";
const Q2_HI = "{QQ[2][1]}";
const POOL0 = "{accts[0]}";
const POOL1 = "{accts[1]}";
const POOL2 = "{accts[2]}";
const SELF = "splt3.clmm.test.near";
const TGAS = 50000000000;
const SWAP_ARGS = '{{"min_out":"0"}}';

// gross units pool k consumes walking GRID_LO -> price (exact: muldiv by "1")
function gross0(price: string): string {{
  if (u128.lt(GRID_MID, price)) {{
    return u128.add(u128MulDiv(Q0_LO, CELL_W_1, "1"), u128MulDiv(Q0_HI, u128.sub(price, GRID_MID), "1"));
  }}
  return u128MulDiv(Q0_LO, u128.sub(price, GRID_LO), "1");
}}
function gross1(price: string): string {{
  if (u128.lt(GRID_MID, price)) {{
    return u128.add(u128MulDiv(Q1_LO, CELL_W_1, "1"), u128MulDiv(Q1_HI, u128.sub(price, GRID_MID), "1"));
  }}
  return u128MulDiv(Q1_LO, u128.sub(price, GRID_LO), "1");
}}
function gross2(price: string): string {{
  if (u128.lt(GRID_MID, price)) {{
    return u128.add(u128MulDiv(Q2_LO, CELL_W_1, "1"), u128MulDiv(Q2_HI, u128.sub(price, GRID_MID), "1"));
  }}
  return u128MulDiv(Q2_LO, u128.sub(price, GRID_LO), "1");
}}
function sum_gross(price: string): string {{
  return u128.add(gross0(price), u128.add(gross1(price), gross2(price)));
}}
function min_cap(a: string, b: string): string {{
  return u128.lt(a, b) ? a : b;
}}

export function split(): string {{
  const deposit: Yocto = near.attachedDepositU128();
  const who = near.predecessorAccountId();
  if (u128.eq(deposit, "0")) {{ fail("ERR_ZERO"); }}
  // NOTE: no loop-carried u128-string mutation — when 2+ string lets
  // interlock through a loop (lo,hi <- mid <- (lo+hi)), writes silently
  // stop sticking after iteration 1 (frontend bug; probe /tmp/bsprobe).
  // Straight-line unique-named const stages, mirroring the lisp let* chain.
{bsearch}
  const price = hi48;
  const share0 = min_cap(gross0(price), deposit);
  const left1 = u128.sub(deposit, share0);
  const share1 = min_cap(gross1(price), left1);
  const left2 = u128.sub(left1, share1);
  const share2 = min_cap(gross2(price), left2);
  const cb = '{{"who":' + near.jsonQuote(who) + '}}';
  sput("s:lo", lo48);
  sput("s:hi", hi48);
  sput("s:p", price);
  sput("sp:who", who);
  sput("s:s0", share0);
  sput("s:s1", share1);
  sput("s:s2", share2);
  near.log("splt3 price=" + price);
  const prom0 = near.promiseCreate(POOL0, "swap", SWAP_ARGS, share0, TGAS);
  near.promiseThen(prom0, SELF, "on0", cb, "0", TGAS);
  const prom1 = near.promiseCreate(POOL1, "swap", SWAP_ARGS, share1, TGAS);
  near.promiseThen(prom1, SELF, "on1", cb, "0", TGAS);
  const prom2 = near.promiseCreate(POOL2, "swap", SWAP_ARGS, share2, TGAS);
  near.promiseThen(prom2, SELF, "on2", cb, "0", TGAS);
  return "queued";
}}

function credit(failTag: string): string {{
  const who = sget("sp:who");
  const out = near.promiseResult(0);
  if (out === "") {{ fail(failTag); }}
  const pk = "paid:" + who;
  const total = u128.add(sget(pk), out);
  sput(pk, total);
  return total;
}}

export function on0(): string {{
  return credit("ERR_P0");
}}
export function on1(): string {{
  return credit("ERR_P1");
}}
export function on2(): string {{
  const total = credit("ERR_P2");
  near.log("splt3 total=" + total);
  return total;
}}

export function get_paid(): string {{
  return sget("paid:" + near.predecessorAccountId());
}}

export function get_split(): string {{
  return sget("s:s0") + "," + sget("s:s1") + "," + sget("s:s2");
}}
"""
    return write("splt3-ts", src)


def _bsearch_stages(n=48):
    """Unrolled bsearch: unique-named const stages, zero mutation.

    The TS frontend silently drops reassignments when 2+ u128-string
    lets interlock through a loop (lo,hi <- mid <- (lo+hi)) — probe
    /tmp/bsprobe. Same medicine as the lisp let* chain.
    """
    out = [
        "  // unrolled binary search stages (no loop-carried string mutation)",
        "  const lo0 = GRID_LO;",
        "  const hi0 = GRID_HI;",
    ]
    for i in range(1, n + 1):
        out.append(f'  const mid{i} = u128MulDiv(u128.add(lo{i - 1}, hi{i - 1}), "1", "2");')
        out.append(f'  const go_up{i} = u128.lt(sum_gross(mid{i}), deposit);')
        out.append(f'  const lo{i} = go_up{i} ? u128.add(mid{i}, "1") : lo{i - 1};')
        out.append(f'  const hi{i} = go_up{i} ? hi{i - 1} : mid{i};')
    return "\n".join(out)


def main():
    pass
    # pools: [grid, net liq, gross book Q]
    LJ = gen.LJ
    pool_ts("pa-ts", gen.GA, gen.LA, gen.QA)
    pool_ts("pb-ts", gen.GB, gen.LB, gen.QB)
    pool_ts("pd-ts", gen.GJ, LJ, gen.QJ)
    pool_ts("pc-ts", gen.GA, gen.LC, gen.QC)
    pool_ts("n1-ts", gen3.G3, gen3.LIQS[1], gen3.QQ[1])
    pool_ts("n2-ts", gen3.G3, gen3.LIQS[2], gen3.QQ[2])
    # pj: fee-union join — gross book additivity QBK = QA+QC, fee Fh0/Fd0
    LK = [gen.LA[i] + gen.LC[i] for i in range(len(gen.LA))]
    QBK = [gen.QA[i] + gen.QC[i] for i in range(len(gen.QA))]
    fh0, fd0 = gen.union_fee_chain(gen.LA[0], gen.LC[0],
                                   gen.NUM, gen.DEN, gen.CNUM, gen.CDEN)
    pool_ts("pj-ts", gen.GA, LK, QBK,
            extra=FEE_EXTRA.format(fh0=fh0, fd0=fd0))
    splt_ts()
    splt3_ts()
    print("ALL-TS-WRITTEN")


if __name__ == "__main__":
    main()
