package outlayer:api@0.1.0;

interface outlayer {
    view: func(a1: s32, a2: s32, a3: s32, a4: s32, a5: s32, a6: s32, a7: s32, a8: s32) -> s32;
    call: func(a1: s32, a2: s32, a3: s32, a4: s32, a5: s32, a6: s32, a7: s32, a8: s32, a9: s32, a10: s32, a11: s32, a12: s32, a13: s32) -> s32;
    transfer: func(a1: s32, a2: s32, a3: s32, a4: s32, a5: s32, a6: s32, a7: s32, a8: s32, a9: s32, a10: s32) -> s32;
    http-get: func(a1: s32, a2: s32, a3: s32, a4: s32, a5: s32) -> s32;
    storage-set: func(a1: s32, a2: s32, a3: s32, a4: s32) -> s32;
    storage-get: func(a1: s32, a2: s32, a3: s32, a4: s32, a5: s32) -> s32;
    storage-has: func(a1: s32, a2: s32) -> s32;
    storage-delete: func(a1: s32, a2: s32) -> s32;
    storage-increment: func(a1: s32, a2: s32, a3: s32, a4: s32, a5: s32, a6: s32) -> s32;
    env-signer: func(a1: s32, a2: s32, a3: s32) -> s32;
    env-predecessor: func(a1: s32, a2: s32, a3: s32) -> s32;
    storage-decrement: func(a1: s32, a2: s32, a3: s32, a4: s32, a5: s32, a6: s32) -> s32;
    storage-set-if-absent: func(a1: s32, a2: s32, a3: s32, a4: s32) -> s32;
    storage-set-if-equals: func(a1: s32, a2: s32, a3: s32, a4: s32, a5: s32, a6: s32, a7: s32, a8: s32) -> s32;
    storage-list-keys: func(a1: s32, a2: s32, a3: s32, a4: s32, a5: s32) -> s32;
    storage-clear-all: func() -> s32;
    storage-set-worker: func(a1: s32, a2: s32, a3: s32, a4: s32) -> s32;
    storage-get-worker: func(a1: s32, a2: s32, a3: s32, a4: s32, a5: s32) -> s32;
    storage-set-worker-public: func(a1: s32, a2: s32, a3: s32, a4: s32) -> s32;
    storage-get-worker-from-project: func(a1: s32, a2: s32, a3: s32, a4: s32, a5: s32, a6: s32, a7: s32) -> s32;
}

world outlayer-world {
    import outlayer;
}
