;; splt3: N-pool composition (N=3, shared grid [1000000000, 2000000000, 4000000000], fee 3000000000000000/1000000000000000000).
;; Net is concave in y => equal-fee optimum EQUALIZES ENDING PRICE p*
;; across pools (leg-2 theorem, N-pool form): p* solves
;;   sum_k qgross_k(p*) = y,   y_k = min(cap_k, qgross_k(p*)).
;; Flat unrolled binary search over p* (48 iters); qgross sums are
;; muldiv-free exact products.  No split beats this beyond per-cell
;; muldiv dust (oracle: 33^3 grid + 20k random splits, zero violations).
(define G0 "1000000000")
(define G1 "2000000000")
(define G2 "4000000000")
(define Q00 "100300902708124373119359")
(define Q01 "60180541624874623871615")
(define Q10 "30090270812437311935808")
(define Q11 "80240722166499498495487")
(define Q20 "50150451354062186559680")
(define Q21 "30090270812437311935808")
(define W0 "1000000000")
(define W1 "2000000000")
(define POOL0 "pa.clmm.test.near")
(define POOL1 "n1.clmm.test.near")
(define POOL2 "n2.clmm.test.near")
(define SELF "splt3.clmm.test.near")
(define TGAS 50000000000)
(define SWAP_ARGS "{\\"min_out\\":\\"0\\"}")

(define (sput k v) (near/storage_set k v))
(define (sget k d) (default (near/storage_get k) d))
(define (fail m) (near/log m) (near/abort m))
(define (add a b) (u128/add a b))
(define (sub a b) (u128/sub a b))
(define (mdiv a b d) (u128/muldiv a b d))
(define (ult a b) (u128/lt a b))

;; gross units pool k consumes walking G0 -> p (exact: mdiv by "1")
;; MIRRORS model qgross: cell0 full below G1... NO: below G1 only the
;; G0->p part of cell 0; at/above G1 cell0 full + cell1 PART (p-G1),
;; never + full W1 (cap+partial overcounts by Q_k1*(G2-p) -- caught by
;; npool-two pins: search collapsed to G1+1, n2 attach 0, ERR_ZERO).
(define (qg k p)
  (if (ult G1 p)
      (add (mdiv (pickk k) W0 "1")
           (mdiv (pickk1 k) (sub p G1) "1"))
      (mdiv (pickk k) (sub p G0) "1")))

(define (pickk k)
  (if (u128/eq k "0") Q00 (if (u128/eq k "1") Q10 Q20)))

(define (pickk1 k)
  (if (u128/eq k "0") Q01 (if (u128/eq k "1") Q11 Q21)))

(define (sumq p)
  (add (qg "0" p) (add (qg "1" p) (qg "2" p))))

(define (mincap a b) (if (ult a b) a b))

(define (split)
  (let* ((y (near/attached_deposit_u128))
         (who (near/predecessor_account_id)))
    (begin
      (if (u128/eq y "0") (fail "ERR_ZERO") "ok")
      (sput "s:lo" G0)
      (sput "s:hi" G2)
      (let* ((lo (sget "s:lo" G0)) (hi (sget "s:hi" G2)) (mid (mdiv (add lo hi) "1" "2")) (s (sumq mid))) (begin (sput "s:lo" (if (ult s y) (add mid "1") lo)) (sput "s:hi" (if (ult s y) hi mid))))
      (let* ((lo (sget "s:lo" G0)) (hi (sget "s:hi" G2)) (mid (mdiv (add lo hi) "1" "2")) (s (sumq mid))) (begin (sput "s:lo" (if (ult s y) (add mid "1") lo)) (sput "s:hi" (if (ult s y) hi mid))))
      (let* ((lo (sget "s:lo" G0)) (hi (sget "s:hi" G2)) (mid (mdiv (add lo hi) "1" "2")) (s (sumq mid))) (begin (sput "s:lo" (if (ult s y) (add mid "1") lo)) (sput "s:hi" (if (ult s y) hi mid))))
      (let* ((lo (sget "s:lo" G0)) (hi (sget "s:hi" G2)) (mid (mdiv (add lo hi) "1" "2")) (s (sumq mid))) (begin (sput "s:lo" (if (ult s y) (add mid "1") lo)) (sput "s:hi" (if (ult s y) hi mid))))
      (let* ((lo (sget "s:lo" G0)) (hi (sget "s:hi" G2)) (mid (mdiv (add lo hi) "1" "2")) (s (sumq mid))) (begin (sput "s:lo" (if (ult s y) (add mid "1") lo)) (sput "s:hi" (if (ult s y) hi mid))))
      (let* ((lo (sget "s:lo" G0)) (hi (sget "s:hi" G2)) (mid (mdiv (add lo hi) "1" "2")) (s (sumq mid))) (begin (sput "s:lo" (if (ult s y) (add mid "1") lo)) (sput "s:hi" (if (ult s y) hi mid))))
      (let* ((lo (sget "s:lo" G0)) (hi (sget "s:hi" G2)) (mid (mdiv (add lo hi) "1" "2")) (s (sumq mid))) (begin (sput "s:lo" (if (ult s y) (add mid "1") lo)) (sput "s:hi" (if (ult s y) hi mid))))
      (let* ((lo (sget "s:lo" G0)) (hi (sget "s:hi" G2)) (mid (mdiv (add lo hi) "1" "2")) (s (sumq mid))) (begin (sput "s:lo" (if (ult s y) (add mid "1") lo)) (sput "s:hi" (if (ult s y) hi mid))))
      (let* ((lo (sget "s:lo" G0)) (hi (sget "s:hi" G2)) (mid (mdiv (add lo hi) "1" "2")) (s (sumq mid))) (begin (sput "s:lo" (if (ult s y) (add mid "1") lo)) (sput "s:hi" (if (ult s y) hi mid))))
      (let* ((lo (sget "s:lo" G0)) (hi (sget "s:hi" G2)) (mid (mdiv (add lo hi) "1" "2")) (s (sumq mid))) (begin (sput "s:lo" (if (ult s y) (add mid "1") lo)) (sput "s:hi" (if (ult s y) hi mid))))
      (let* ((lo (sget "s:lo" G0)) (hi (sget "s:hi" G2)) (mid (mdiv (add lo hi) "1" "2")) (s (sumq mid))) (begin (sput "s:lo" (if (ult s y) (add mid "1") lo)) (sput "s:hi" (if (ult s y) hi mid))))
      (let* ((lo (sget "s:lo" G0)) (hi (sget "s:hi" G2)) (mid (mdiv (add lo hi) "1" "2")) (s (sumq mid))) (begin (sput "s:lo" (if (ult s y) (add mid "1") lo)) (sput "s:hi" (if (ult s y) hi mid))))
      (let* ((lo (sget "s:lo" G0)) (hi (sget "s:hi" G2)) (mid (mdiv (add lo hi) "1" "2")) (s (sumq mid))) (begin (sput "s:lo" (if (ult s y) (add mid "1") lo)) (sput "s:hi" (if (ult s y) hi mid))))
      (let* ((lo (sget "s:lo" G0)) (hi (sget "s:hi" G2)) (mid (mdiv (add lo hi) "1" "2")) (s (sumq mid))) (begin (sput "s:lo" (if (ult s y) (add mid "1") lo)) (sput "s:hi" (if (ult s y) hi mid))))
      (let* ((lo (sget "s:lo" G0)) (hi (sget "s:hi" G2)) (mid (mdiv (add lo hi) "1" "2")) (s (sumq mid))) (begin (sput "s:lo" (if (ult s y) (add mid "1") lo)) (sput "s:hi" (if (ult s y) hi mid))))
      (let* ((lo (sget "s:lo" G0)) (hi (sget "s:hi" G2)) (mid (mdiv (add lo hi) "1" "2")) (s (sumq mid))) (begin (sput "s:lo" (if (ult s y) (add mid "1") lo)) (sput "s:hi" (if (ult s y) hi mid))))
      (let* ((lo (sget "s:lo" G0)) (hi (sget "s:hi" G2)) (mid (mdiv (add lo hi) "1" "2")) (s (sumq mid))) (begin (sput "s:lo" (if (ult s y) (add mid "1") lo)) (sput "s:hi" (if (ult s y) hi mid))))
      (let* ((lo (sget "s:lo" G0)) (hi (sget "s:hi" G2)) (mid (mdiv (add lo hi) "1" "2")) (s (sumq mid))) (begin (sput "s:lo" (if (ult s y) (add mid "1") lo)) (sput "s:hi" (if (ult s y) hi mid))))
      (let* ((lo (sget "s:lo" G0)) (hi (sget "s:hi" G2)) (mid (mdiv (add lo hi) "1" "2")) (s (sumq mid))) (begin (sput "s:lo" (if (ult s y) (add mid "1") lo)) (sput "s:hi" (if (ult s y) hi mid))))
      (let* ((lo (sget "s:lo" G0)) (hi (sget "s:hi" G2)) (mid (mdiv (add lo hi) "1" "2")) (s (sumq mid))) (begin (sput "s:lo" (if (ult s y) (add mid "1") lo)) (sput "s:hi" (if (ult s y) hi mid))))
      (let* ((lo (sget "s:lo" G0)) (hi (sget "s:hi" G2)) (mid (mdiv (add lo hi) "1" "2")) (s (sumq mid))) (begin (sput "s:lo" (if (ult s y) (add mid "1") lo)) (sput "s:hi" (if (ult s y) hi mid))))
      (let* ((lo (sget "s:lo" G0)) (hi (sget "s:hi" G2)) (mid (mdiv (add lo hi) "1" "2")) (s (sumq mid))) (begin (sput "s:lo" (if (ult s y) (add mid "1") lo)) (sput "s:hi" (if (ult s y) hi mid))))
      (let* ((lo (sget "s:lo" G0)) (hi (sget "s:hi" G2)) (mid (mdiv (add lo hi) "1" "2")) (s (sumq mid))) (begin (sput "s:lo" (if (ult s y) (add mid "1") lo)) (sput "s:hi" (if (ult s y) hi mid))))
      (let* ((lo (sget "s:lo" G0)) (hi (sget "s:hi" G2)) (mid (mdiv (add lo hi) "1" "2")) (s (sumq mid))) (begin (sput "s:lo" (if (ult s y) (add mid "1") lo)) (sput "s:hi" (if (ult s y) hi mid))))
      (let* ((lo (sget "s:lo" G0)) (hi (sget "s:hi" G2)) (mid (mdiv (add lo hi) "1" "2")) (s (sumq mid))) (begin (sput "s:lo" (if (ult s y) (add mid "1") lo)) (sput "s:hi" (if (ult s y) hi mid))))
      (let* ((lo (sget "s:lo" G0)) (hi (sget "s:hi" G2)) (mid (mdiv (add lo hi) "1" "2")) (s (sumq mid))) (begin (sput "s:lo" (if (ult s y) (add mid "1") lo)) (sput "s:hi" (if (ult s y) hi mid))))
      (let* ((lo (sget "s:lo" G0)) (hi (sget "s:hi" G2)) (mid (mdiv (add lo hi) "1" "2")) (s (sumq mid))) (begin (sput "s:lo" (if (ult s y) (add mid "1") lo)) (sput "s:hi" (if (ult s y) hi mid))))
      (let* ((lo (sget "s:lo" G0)) (hi (sget "s:hi" G2)) (mid (mdiv (add lo hi) "1" "2")) (s (sumq mid))) (begin (sput "s:lo" (if (ult s y) (add mid "1") lo)) (sput "s:hi" (if (ult s y) hi mid))))
      (let* ((lo (sget "s:lo" G0)) (hi (sget "s:hi" G2)) (mid (mdiv (add lo hi) "1" "2")) (s (sumq mid))) (begin (sput "s:lo" (if (ult s y) (add mid "1") lo)) (sput "s:hi" (if (ult s y) hi mid))))
      (let* ((lo (sget "s:lo" G0)) (hi (sget "s:hi" G2)) (mid (mdiv (add lo hi) "1" "2")) (s (sumq mid))) (begin (sput "s:lo" (if (ult s y) (add mid "1") lo)) (sput "s:hi" (if (ult s y) hi mid))))
      (let* ((lo (sget "s:lo" G0)) (hi (sget "s:hi" G2)) (mid (mdiv (add lo hi) "1" "2")) (s (sumq mid))) (begin (sput "s:lo" (if (ult s y) (add mid "1") lo)) (sput "s:hi" (if (ult s y) hi mid))))
      (let* ((lo (sget "s:lo" G0)) (hi (sget "s:hi" G2)) (mid (mdiv (add lo hi) "1" "2")) (s (sumq mid))) (begin (sput "s:lo" (if (ult s y) (add mid "1") lo)) (sput "s:hi" (if (ult s y) hi mid))))
      (let* ((lo (sget "s:lo" G0)) (hi (sget "s:hi" G2)) (mid (mdiv (add lo hi) "1" "2")) (s (sumq mid))) (begin (sput "s:lo" (if (ult s y) (add mid "1") lo)) (sput "s:hi" (if (ult s y) hi mid))))
      (let* ((lo (sget "s:lo" G0)) (hi (sget "s:hi" G2)) (mid (mdiv (add lo hi) "1" "2")) (s (sumq mid))) (begin (sput "s:lo" (if (ult s y) (add mid "1") lo)) (sput "s:hi" (if (ult s y) hi mid))))
      (let* ((lo (sget "s:lo" G0)) (hi (sget "s:hi" G2)) (mid (mdiv (add lo hi) "1" "2")) (s (sumq mid))) (begin (sput "s:lo" (if (ult s y) (add mid "1") lo)) (sput "s:hi" (if (ult s y) hi mid))))
      (let* ((lo (sget "s:lo" G0)) (hi (sget "s:hi" G2)) (mid (mdiv (add lo hi) "1" "2")) (s (sumq mid))) (begin (sput "s:lo" (if (ult s y) (add mid "1") lo)) (sput "s:hi" (if (ult s y) hi mid))))
      (let* ((lo (sget "s:lo" G0)) (hi (sget "s:hi" G2)) (mid (mdiv (add lo hi) "1" "2")) (s (sumq mid))) (begin (sput "s:lo" (if (ult s y) (add mid "1") lo)) (sput "s:hi" (if (ult s y) hi mid))))
      (let* ((lo (sget "s:lo" G0)) (hi (sget "s:hi" G2)) (mid (mdiv (add lo hi) "1" "2")) (s (sumq mid))) (begin (sput "s:lo" (if (ult s y) (add mid "1") lo)) (sput "s:hi" (if (ult s y) hi mid))))
      (let* ((lo (sget "s:lo" G0)) (hi (sget "s:hi" G2)) (mid (mdiv (add lo hi) "1" "2")) (s (sumq mid))) (begin (sput "s:lo" (if (ult s y) (add mid "1") lo)) (sput "s:hi" (if (ult s y) hi mid))))
      (let* ((lo (sget "s:lo" G0)) (hi (sget "s:hi" G2)) (mid (mdiv (add lo hi) "1" "2")) (s (sumq mid))) (begin (sput "s:lo" (if (ult s y) (add mid "1") lo)) (sput "s:hi" (if (ult s y) hi mid))))
      (let* ((lo (sget "s:lo" G0)) (hi (sget "s:hi" G2)) (mid (mdiv (add lo hi) "1" "2")) (s (sumq mid))) (begin (sput "s:lo" (if (ult s y) (add mid "1") lo)) (sput "s:hi" (if (ult s y) hi mid))))
      (let* ((lo (sget "s:lo" G0)) (hi (sget "s:hi" G2)) (mid (mdiv (add lo hi) "1" "2")) (s (sumq mid))) (begin (sput "s:lo" (if (ult s y) (add mid "1") lo)) (sput "s:hi" (if (ult s y) hi mid))))
      (let* ((lo (sget "s:lo" G0)) (hi (sget "s:hi" G2)) (mid (mdiv (add lo hi) "1" "2")) (s (sumq mid))) (begin (sput "s:lo" (if (ult s y) (add mid "1") lo)) (sput "s:hi" (if (ult s y) hi mid))))
      (let* ((lo (sget "s:lo" G0)) (hi (sget "s:hi" G2)) (mid (mdiv (add lo hi) "1" "2")) (s (sumq mid))) (begin (sput "s:lo" (if (ult s y) (add mid "1") lo)) (sput "s:hi" (if (ult s y) hi mid))))
      (let* ((lo (sget "s:lo" G0)) (hi (sget "s:hi" G2)) (mid (mdiv (add lo hi) "1" "2")) (s (sumq mid))) (begin (sput "s:lo" (if (ult s y) (add mid "1") lo)) (sput "s:hi" (if (ult s y) hi mid))))
      (let* ((lo (sget "s:lo" G0)) (hi (sget "s:hi" G2)) (mid (mdiv (add lo hi) "1" "2")) (s (sumq mid))) (begin (sput "s:lo" (if (ult s y) (add mid "1") lo)) (sput "s:hi" (if (ult s y) hi mid))))
      (let* ((lo (sget "s:lo" G0)) (hi (sget "s:hi" G2)) (mid (mdiv (add lo hi) "1" "2")) (s (sumq mid))) (begin (sput "s:lo" (if (ult s y) (add mid "1") lo)) (sput "s:hi" (if (ult s y) hi mid))))
      (let* ((lo (sget "s:lo" G0)) (hi (sget "s:hi" G2)) (mid (mdiv (add lo hi) "1" "2")) (s (sumq mid))) (begin (sput "s:lo" (if (ult s y) (add mid "1") lo)) (sput "s:hi" (if (ult s y) hi mid))))
      (sput "s:p" (sget "s:hi" G2))
      (let* ((p (sget "s:p" G2))
             (y0 (mincap (qg "0" p) y))
             (r1 (sub y y0))
             (y1 (mincap (qg "1" p) r1))
             (r2 (sub r1 y1))
             (y2 (mincap (qg "2" p) r2))
             (cb (str-cat (str-cat "{\"who\":\"") (str-cat who "\"}"))))
        (begin
          (sput "sp:who" who)
          (sput "s:s0" y0)
          (sput "s:s1" y1)
          (sput "s:s2" y2)
          (near/log (str-cat "splt3 p=" p))
          (let ((p0 (near/promise_create POOL0 "swap" SWAP_ARGS y0 TGAS)))
            (near/promise_then p0 SELF "on0" cb "0" TGAS)
            (let ((p1 (near/promise_create POOL1 "swap" SWAP_ARGS y1 TGAS)))
              (near/promise_then p1 SELF "on1" cb "0" TGAS)
              (let ((p2 (near/promise_create POOL2 "swap" SWAP_ARGS y2 TGAS)))
                (near/promise_then p2 SELF "on2" cb "0" TGAS)
                (near/return "queued")))))))))

(define (on0)
  (let* ((who (sget "sp:who" ""))
         (out (near/promise_result 0))
         (pk (str-cat "paid:" who)))
    (if (= out "")
        (fail "ERR_P0")
        (begin
          (sput pk (add (sget pk "0") out))
          (near/return out)))))

(define (on1)
  (let* ((who (sget "sp:who" ""))
         (out (near/promise_result 0))
         (pk (str-cat "paid:" who)))
    (if (= out "")
        (fail "ERR_P1")
        (begin
          (sput pk (add (sget pk "0") out))
          (near/return out)))))

(define (on2)
  (let* ((who (sget "sp:who" ""))
         (out (near/promise_result 0))
         (pk (str-cat "paid:" who))
         (total (add (sget pk "0") out)))
    (if (= out "")
        (fail "ERR_P2")
        (begin
          (sput pk total)
          (near/log (str-cat "splt3 total=" total))
          (near/return out)))))

(define (get-paid)
  (near/return (sget (str-cat "paid:" (near/predecessor_account_id)) "0")))

(define (get-split)
  (near/return (str-cat (sget "s:s0" "0")
                        (str-cat "," (str-cat (sget "s:s1" "0")
                                              (str-cat "," (sget "s:s2" "0")))))))

(export "split" split)
(export "on0" on0)
(export "on1" on1)
(export "on2" on2)
(export "get-paid" get-paid)
(export "get-split" get-split)
